export interface Property {
  id: string;
  title: string;
  description: string;
  price: number;
  currency: string;
  location: string;
  city: string;
  bedrooms: number;
  bathrooms: number;
  sqm: number;
  imageUrl: string;
  type: 'sale' | 'rent';
  propertyType: 'house' | 'apartment' | 'land';
  virtualTourUrl?: string;
  lat?: number;
  lng?: number;
}

export const mockProperties: Property[] = [
  {
    id: "prop-1",
    title: "Secure Apartment in Mukura",
    description: "A secure apartment located in Mukura, Huye. Fits mid-income budgets perfectly and offers great value for the area.",
    price: 127000,
    currency: "USD",
    location: "Mukura",
    city: "Huye",
    bedrooms: 4,
    bathrooms: 4,
    sqm: 220,
    imageUrl: "https://images.unsplash.com/photo-1507427100689-2bf8574e32d4?q=80&w=800&auto=format&fit=crop",
    type: "sale",
    propertyType: "apartment",
    virtualTourUrl: "https://my.matterport.com/show/?m=JGPnGQ6hosj",
    lat: -1.448,
    lng: 30.028
  },
  {
    id: "prop-2",
    title: "Cozy Apartment in Cyeza",
    description: "A cozy apartment located in Cyeza, Muhanga. Fits mid-income budgets perfectly and offers great value for the area.",
    price: 147000,
    currency: "USD",
    location: "Cyeza",
    city: "Muhanga",
    bedrooms: 4,
    bathrooms: 3,
    sqm: 88,
    imageUrl: "https://images.unsplash.com/photo-1720605739861-9f5110c7e529?q=80&w=800&auto=format&fit=crop",
    type: "sale",
    propertyType: "apartment",
    virtualTourUrl: "https://my.matterport.com/show/?m=JGPnGQ6hosj",
    lat: -1.778,
    lng: 30.355
  },
  {
    id: "prop-3",
    title: "Charming Semi-detached House in Ngoma",
    description: "A charming house located in Ngoma, Huye. Fits mid-income budgets perfectly and offers great value for the area.",
    price: 1000,
    currency: "USD/month",
    location: "Ngoma",
    city: "Huye",
    bedrooms: 3,
    bathrooms: 2,
    sqm: 125,
    imageUrl: "https://images.unsplash.com/photo-1682773083908-a0e9ffadd175?q=80&w=800&auto=format&fit=crop",
    type: "rent",
    propertyType: "house",
    virtualTourUrl: "https://my.matterport.com/show/?m=JGPnGQ6hosj",
    lat: -2.484,
    lng: 30.444
  },
  {
    id: "prop-4",
    title: "Secure Condo in Gacuriro",
    description: "A secure apartment located in Gacuriro, Kigali. Fits mid-income budgets perfectly and offers great value for the area.",
    price: 42000,
    currency: "USD",
    location: "Gacuriro",
    city: "Kigali",
    bedrooms: 3,
    bathrooms: 2,
    sqm: 160,
    imageUrl: "https://images.unsplash.com/photo-1667504320745-eade6c25e053?q=80&w=800&auto=format&fit=crop",
    type: "sale",
    propertyType: "apartment",
    virtualTourUrl: "https://my.matterport.com/show/?m=JGPnGQ6hosj",
    lat: -1.964,
    lng: 30.460
  },
  {
    id: "prop-5",
    title: "Spacious Family Home in Nyamabuye",
    description: "A spacious house located in Nyamabuye, Muhanga. Fits mid-income budgets perfectly and offers great value for the area.",
    price: 1400,
    currency: "USD/month",
    location: "Nyamabuye",
    city: "Muhanga",
    bedrooms: 2,
    bathrooms: 1,
    sqm: 161,
    imageUrl: "https://images.unsplash.com/photo-1708772565599-2c4e4b3ed9db?q=80&w=800&auto=format&fit=crop",
    type: "rent",
    propertyType: "house",
    virtualTourUrl: "https://my.matterport.com/show/?m=JGPnGQ6hosj",
    lat: -2.598,
    lng: 30.346
  },
  {
    id: "prop-6",
    title: "Stunning Villa in Kanombe",
    description: "A stunning house located in Kanombe, Kigali. Fits high-income budgets perfectly and offers great value for the area.",
    price: 600000,
    currency: "USD",
    location: "Kanombe",
    city: "Kigali",
    bedrooms: 4,
    bathrooms: 3,
    sqm: 924,
    imageUrl: "https://images.unsplash.com/photo-1689013398932-b576a11e07a1?q=80&w=800&auto=format&fit=crop",
    type: "sale",
    propertyType: "house",
    virtualTourUrl: "https://my.matterport.com/show/?m=JGPnGQ6hosj",
    lat: -2.090,
    lng: 30.237
  },
  {
    id: "prop-7",
    title: "Family Residential Plot in Mururu",
    description: "A family land located in Mururu, Rusizi. Fits mid-income budgets perfectly and offers great value for the area.",
    price: 22000,
    currency: "USD",
    location: "Mururu",
    city: "Rusizi",
    bedrooms: 0,
    bathrooms: 0,
    sqm: 801,
    imageUrl: "https://images.unsplash.com/photo-1708772565588-33785e13aa46?q=80&w=800&auto=format&fit=crop",
    type: "sale",
    propertyType: "land",
    virtualTourUrl: "https://my.matterport.com/show/?m=JGPnGQ6hosj",
    lat: -1.853,
    lng: 29.929
  },
  {
    id: "prop-8",
    title: "Secure Farm in Gisenyi",
    description: "A secure land located in Gisenyi, Rubavu. Fits mid-income budgets perfectly and offers great value for the area.",
    price: 500,
    currency: "USD/month",
    location: "Gisenyi",
    city: "Rubavu",
    bedrooms: 0,
    bathrooms: 0,
    sqm: 1216,
    imageUrl: "https://images.unsplash.com/photo-1682773083896-95176d8aecf8?q=80&w=800&auto=format&fit=crop",
    type: "rent",
    propertyType: "land",
    virtualTourUrl: "https://my.matterport.com/show/?m=JGPnGQ6hosj",
    lat: -2.635,
    lng: 30.148
  },
  {
    id: "prop-9",
    title: "Family Condo in Rugerero",
    description: "A family apartment located in Rugerero, Rubavu. Fits mid-income budgets perfectly and offers great value for the area.",
    price: 84000,
    currency: "USD",
    location: "Rugerero",
    city: "Rubavu",
    bedrooms: 4,
    bathrooms: 3,
    sqm: 221,
    imageUrl: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?q=80&w=800&auto=format&fit=crop",
    type: "sale",
    propertyType: "apartment",
    virtualTourUrl: "https://my.matterport.com/show/?m=JGPnGQ6hosj",
    lat: -1.904,
    lng: 30.544
  },
  {
    id: "prop-10",
    title: "Modern Apartment in Nyamyumba",
    description: "A modern apartment located in Nyamyumba, Rubavu. Fits mid-income budgets perfectly and offers great value for the area.",
    price: 60000,
    currency: "USD",
    location: "Nyamyumba",
    city: "Rubavu",
    bedrooms: 4,
    bathrooms: 4,
    sqm: 164,
    imageUrl: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?q=80&w=800&auto=format&fit=crop",
    type: "sale",
    propertyType: "apartment",
    virtualTourUrl: "https://my.matterport.com/show/?m=JGPnGQ6hosj",
    lat: -1.570,
    lng: 29.447
  },
  {
    id: "prop-11",
    title: "Secure Condo in Mukura",
    description: "A secure apartment located in Mukura, Huye. Fits mid-income budgets perfectly and offers great value for the area.",
    price: 650,
    currency: "USD/month",
    location: "Mukura",
    city: "Huye",
    bedrooms: 2,
    bathrooms: 2,
    sqm: 99,
    imageUrl: "https://images.unsplash.com/photo-1600607688969-a5bfcd646154?q=80&w=800&auto=format&fit=crop",
    type: "rent",
    propertyType: "apartment",
    virtualTourUrl: "https://my.matterport.com/show/?m=JGPnGQ6hosj",
    lat: -2.302,
    lng: 30.798
  },
  {
    id: "prop-12",
    title: "Standard Studio in Shyogwe",
    description: "A standard apartment located in Shyogwe, Muhanga. Fits low-income budgets perfectly and offers great value for the area.",
    price: 22000,
    currency: "USD",
    location: "Shyogwe",
    city: "Muhanga",
    bedrooms: 2,
    bathrooms: 2,
    sqm: 98,
    imageUrl: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?q=80&w=800&auto=format&fit=crop",
    type: "sale",
    propertyType: "apartment",
    virtualTourUrl: "https://my.matterport.com/show/?m=JGPnGQ6hosj",
    lat: -1.532,
    lng: 29.583
  },
  {
    id: "prop-13",
    title: "Spacious Semi-detached House in Matimba",
    description: "A spacious house located in Matimba, Nyagatare. Fits mid-income budgets perfectly and offers great value for the area.",
    price: 122000,
    currency: "USD",
    location: "Matimba",
    city: "Nyagatare",
    bedrooms: 2,
    bathrooms: 2,
    sqm: 194,
    imageUrl: "https://images.unsplash.com/photo-1518780664697-5b050e0bb626?q=80&w=800&auto=format&fit=crop",
    type: "sale",
    propertyType: "house",
    virtualTourUrl: "https://my.matterport.com/show/?m=JGPnGQ6hosj",
    lat: -1.393,
    lng: 29.892
  },
  {
    id: "prop-14",
    title: "Family Residential Plot in Ruhengeri",
    description: "A family land located in Ruhengeri, Musanze. Fits mid-income budgets perfectly and offers great value for the area.",
    price: 300,
    currency: "USD/month",
    location: "Ruhengeri",
    city: "Musanze",
    bedrooms: 0,
    bathrooms: 0,
    sqm: 328,
    imageUrl: "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?q=80&w=800&auto=format&fit=crop",
    type: "rent",
    propertyType: "land",
    virtualTourUrl: "https://my.matterport.com/show/?m=JGPnGQ6hosj",
    lat: -1.425,
    lng: 29.737
  },
  {
    id: "prop-15",
    title: "Affordable Room in Matimba",
    description: "A affordable apartment located in Matimba, Nyagatare. Fits low-income budgets perfectly and offers great value for the area.",
    price: 9300,
    currency: "USD",
    location: "Matimba",
    city: "Nyagatare",
    bedrooms: 2,
    bathrooms: 2,
    sqm: 31,
    imageUrl: "https://images.unsplash.com/photo-1605146768851-ea244b94238e?q=80&w=800&auto=format&fit=crop",
    type: "sale",
    propertyType: "apartment",
    virtualTourUrl: "https://my.matterport.com/show/?m=JGPnGQ6hosj",
    lat: -2.319,
    lng: 30.522
  },
  {
    id: "prop-16",
    title: "Affordable Basic Unit in Nyamabuye",
    description: "A affordable apartment located in Nyamabuye, Muhanga. Fits low-income budgets perfectly and offers great value for the area.",
    price: 21000,
    currency: "USD",
    location: "Nyamabuye",
    city: "Muhanga",
    bedrooms: 1,
    bathrooms: 1,
    sqm: 26,
    imageUrl: "https://images.unsplash.com/photo-1605810230434-7631ac76ec81?q=80&w=800&auto=format&fit=crop",
    type: "sale",
    propertyType: "apartment",
    virtualTourUrl: "https://my.matterport.com/show/?m=JGPnGQ6hosj",
    lat: -1.454,
    lng: 30.625
  },
  {
    id: "prop-17",
    title: "Family Farm in Tumba",
    description: "A family land located in Tumba, Huye. Fits mid-income budgets perfectly and offers great value for the area.",
    price: 42000,
    currency: "USD",
    location: "Tumba",
    city: "Huye",
    bedrooms: 0,
    bathrooms: 0,
    sqm: 238,
    imageUrl: "https://images.unsplash.com/photo-1582268611958-ebfd161ef9cf?q=80&w=800&auto=format&fit=crop",
    type: "sale",
    propertyType: "land",
    virtualTourUrl: "https://my.matterport.com/show/?m=JGPnGQ6hosj",
    lat: -2.497,
    lng: 29.979
  },
  {
    id: "prop-18",
    title: "Traditional Farming Land in Nyamyumba",
    description: "A traditional land located in Nyamyumba, Rubavu. Fits low-income budgets perfectly and offers great value for the area.",
    price: 10000,
    currency: "USD",
    location: "Nyamyumba",
    city: "Rubavu",
    bedrooms: 0,
    bathrooms: 0,
    sqm: 105,
    imageUrl: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?q=80&w=800&auto=format&fit=crop",
    type: "sale",
    propertyType: "land",
    virtualTourUrl: "https://my.matterport.com/show/?m=JGPnGQ6hosj",
    lat: -1.703,
    lng: 30.182
  },
  {
    id: "prop-19",
    title: "Elegant Prime Commercial Land in Kamembe",
    description: "A elegant land located in Kamembe, Rusizi. Fits high-income budgets perfectly and offers great value for the area.",
    price: 2100,
    currency: "USD/month",
    location: "Kamembe",
    city: "Rusizi",
    bedrooms: 0,
    bathrooms: 0,
    sqm: 2787,
    imageUrl: "https://images.unsplash.com/photo-1523217582562-09d0def993a6?q=80&w=800&auto=format&fit=crop",
    type: "rent",
    propertyType: "land",
    virtualTourUrl: "https://my.matterport.com/show/?m=JGPnGQ6hosj",
    lat: -1.533,
    lng: 30.394
  },
  {
    id: "prop-20",
    title: "Cozy Semi-detached House in Mururu",
    description: "A cozy house located in Mururu, Rusizi. Fits mid-income budgets perfectly and offers great value for the area.",
    price: 500,
    currency: "USD/month",
    location: "Mururu",
    city: "Rusizi",
    bedrooms: 2,
    bathrooms: 1,
    sqm: 97,
    imageUrl: "https://images.unsplash.com/photo-1598228726386-8a03bb3644f7?q=80&w=800&auto=format&fit=crop",
    type: "rent",
    propertyType: "house",
    virtualTourUrl: "https://my.matterport.com/show/?m=JGPnGQ6hosj",
    lat: -1.256,
    lng: 30.219
  },
  {
    id: "prop-21",
    title: "Standard House in Matimba",
    description: "A standard house located in Matimba, Nyagatare. Fits low-income budgets perfectly and offers great value for the area.",
    price: 200,
    currency: "USD/month",
    location: "Matimba",
    city: "Nyagatare",
    bedrooms: 3,
    bathrooms: 3,
    sqm: 48,
    imageUrl: "https://images.unsplash.com/photo-1507427100689-2bf8574e32d4?q=80&w=800&auto=format&fit=crop",
    type: "rent",
    propertyType: "house",
    virtualTourUrl: "https://my.matterport.com/show/?m=JGPnGQ6hosj",
    lat: -2.190,
    lng: 30.586
  },
  {
    id: "prop-22",
    title: "Cozy Development Land in Kacyiru",
    description: "A cozy land located in Kacyiru, Kigali. Fits mid-income budgets perfectly and offers great value for the area.",
    price: 50000,
    currency: "USD",
    location: "Kacyiru",
    city: "Kigali",
    bedrooms: 0,
    bathrooms: 0,
    sqm: 256,
    imageUrl: "https://images.unsplash.com/photo-1720605739861-9f5110c7e529?q=80&w=800&auto=format&fit=crop",
    type: "sale",
    propertyType: "land",
    virtualTourUrl: "https://my.matterport.com/show/?m=JGPnGQ6hosj",
    lat: -1.405,
    lng: 29.886
  },
  {
    id: "prop-23",
    title: "Spacious Family Home in Nyamirambo",
    description: "A spacious house located in Nyamirambo, Kigali. Fits mid-income budgets perfectly and offers great value for the area.",
    price: 146000,
    currency: "USD",
    location: "Nyamirambo",
    city: "Kigali",
    bedrooms: 4,
    bathrooms: 3,
    sqm: 182,
    imageUrl: "https://images.unsplash.com/photo-1682773083908-a0e9ffadd175?q=80&w=800&auto=format&fit=crop",
    type: "sale",
    propertyType: "house",
    virtualTourUrl: "https://my.matterport.com/show/?m=JGPnGQ6hosj",
    lat: -2.339,
    lng: 30.332
  },
  {
    id: "prop-24",
    title: "Standard Studio in Ruhengeri",
    description: "A standard apartment located in Ruhengeri, Musanze. Fits low-income budgets perfectly and offers great value for the area.",
    price: 250,
    currency: "USD/month",
    location: "Ruhengeri",
    city: "Musanze",
    bedrooms: 3,
    bathrooms: 3,
    sqm: 25,
    imageUrl: "https://images.unsplash.com/photo-1667504320745-eade6c25e053?q=80&w=800&auto=format&fit=crop",
    type: "rent",
    propertyType: "apartment",
    virtualTourUrl: "https://my.matterport.com/show/?m=JGPnGQ6hosj",
    lat: -1.794,
    lng: 30.496
  },
  {
    id: "prop-25",
    title: "Stunning Prime Commercial Land in Kamembe",
    description: "A stunning land located in Kamembe, Rusizi. Fits high-income budgets perfectly and offers great value for the area.",
    price: 369000,
    currency: "USD",
    location: "Kamembe",
    city: "Rusizi",
    bedrooms: 0,
    bathrooms: 0,
    sqm: 1463,
    imageUrl: "https://images.unsplash.com/photo-1708772565599-2c4e4b3ed9db?q=80&w=800&auto=format&fit=crop",
    type: "sale",
    propertyType: "land",
    virtualTourUrl: "https://my.matterport.com/show/?m=JGPnGQ6hosj",
    lat: -2.265,
    lng: 29.776
  },
  {
    id: "prop-26",
    title: "Renovated Residence in Nyamabuye",
    description: "A renovated house located in Nyamabuye, Muhanga. Fits mid-income budgets perfectly and offers great value for the area.",
    price: 113000,
    currency: "USD",
    location: "Nyamabuye",
    city: "Muhanga",
    bedrooms: 4,
    bathrooms: 3,
    sqm: 104,
    imageUrl: "https://images.unsplash.com/photo-1689013398932-b576a11e07a1?q=80&w=800&auto=format&fit=crop",
    type: "sale",
    propertyType: "house",
    virtualTourUrl: "https://my.matterport.com/show/?m=JGPnGQ6hosj",
    lat: -1.601,
    lng: 30.234
  },
  {
    id: "prop-27",
    title: "Family Bungalow in Nyagatare",
    description: "A family house located in Nyagatare, Nyagatare. Fits mid-income budgets perfectly and offers great value for the area.",
    price: 80000,
    currency: "USD",
    location: "Nyagatare",
    city: "Nyagatare",
    bedrooms: 2,
    bathrooms: 1,
    sqm: 235,
    imageUrl: "https://images.unsplash.com/photo-1708772565588-33785e13aa46?q=80&w=800&auto=format&fit=crop",
    type: "sale",
    propertyType: "house",
    virtualTourUrl: "https://my.matterport.com/show/?m=JGPnGQ6hosj",
    lat: -2.083,
    lng: 30.564
  },
  {
    id: "prop-28",
    title: "Renovated Condo in Rwimiyaga",
    description: "A renovated apartment located in Rwimiyaga, Nyagatare. Fits mid-income budgets perfectly and offers great value for the area.",
    price: 131000,
    currency: "USD",
    location: "Rwimiyaga",
    city: "Nyagatare",
    bedrooms: 4,
    bathrooms: 4,
    sqm: 91,
    imageUrl: "https://images.unsplash.com/photo-1682773083896-95176d8aecf8?q=80&w=800&auto=format&fit=crop",
    type: "sale",
    propertyType: "apartment",
    virtualTourUrl: "https://my.matterport.com/show/?m=JGPnGQ6hosj",
    lat: -1.820,
    lng: 29.903
  },
  {
    id: "prop-29",
    title: "Starter House in Ngoma",
    description: "A starter house located in Ngoma, Huye. Fits low-income budgets perfectly and offers great value for the area.",
    price: 7400,
    currency: "USD",
    location: "Ngoma",
    city: "Huye",
    bedrooms: 1,
    bathrooms: 1,
    sqm: 53,
    imageUrl: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?q=80&w=800&auto=format&fit=crop",
    type: "sale",
    propertyType: "house",
    virtualTourUrl: "https://my.matterport.com/show/?m=JGPnGQ6hosj",
    lat: -1.736,
    lng: 29.388
  },
  {
    id: "prop-30",
    title: "Secure Residential Plot in Cyeza",
    description: "A secure land located in Cyeza, Muhanga. Fits mid-income budgets perfectly and offers great value for the area.",
    price: 58000,
    currency: "USD",
    location: "Cyeza",
    city: "Muhanga",
    bedrooms: 0,
    bathrooms: 0,
    sqm: 1024,
    imageUrl: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?q=80&w=800&auto=format&fit=crop",
    type: "sale",
    propertyType: "land",
    virtualTourUrl: "https://my.matterport.com/show/?m=JGPnGQ6hosj",
    lat: -1.293,
    lng: 29.936
  },
  {
    id: "prop-31",
    title: "Cozy Residence in Cyeza",
    description: "A cozy house located in Cyeza, Muhanga. Fits mid-income budgets perfectly and offers great value for the area.",
    price: 45000,
    currency: "USD",
    location: "Cyeza",
    city: "Muhanga",
    bedrooms: 2,
    bathrooms: 2,
    sqm: 235,
    imageUrl: "https://images.unsplash.com/photo-1600607688969-a5bfcd646154?q=80&w=800&auto=format&fit=crop",
    type: "sale",
    propertyType: "house",
    virtualTourUrl: "https://my.matterport.com/show/?m=JGPnGQ6hosj",
    lat: -1.258,
    lng: 29.356
  },
  {
    id: "prop-32",
    title: "Modern Bungalow in Ngoma",
    description: "A modern house located in Ngoma, Huye. Fits mid-income budgets perfectly and offers great value for the area.",
    price: 103000,
    currency: "USD",
    location: "Ngoma",
    city: "Huye",
    bedrooms: 2,
    bathrooms: 2,
    sqm: 246,
    imageUrl: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?q=80&w=800&auto=format&fit=crop",
    type: "sale",
    propertyType: "house",
    virtualTourUrl: "https://my.matterport.com/show/?m=JGPnGQ6hosj",
    lat: -2.245,
    lng: 30.534
  },
  {
    id: "prop-33",
    title: "Cozy Family Home in Mururu",
    description: "A cozy house located in Mururu, Rusizi. Fits mid-income budgets perfectly and offers great value for the area.",
    price: 850,
    currency: "USD/month",
    location: "Mururu",
    city: "Rusizi",
    bedrooms: 2,
    bathrooms: 2,
    sqm: 97,
    imageUrl: "https://images.unsplash.com/photo-1518780664697-5b050e0bb626?q=80&w=800&auto=format&fit=crop",
    type: "rent",
    propertyType: "house",
    virtualTourUrl: "https://my.matterport.com/show/?m=JGPnGQ6hosj",
    lat: -2.466,
    lng: 30.098
  },
  {
    id: "prop-34",
    title: "Beautiful Executive Suite in Ngoma",
    description: "A beautiful apartment located in Ngoma, Huye. Fits high-income budgets perfectly and offers great value for the area.",
    price: 5400,
    currency: "USD/month",
    location: "Ngoma",
    city: "Huye",
    bedrooms: 6,
    bathrooms: 5,
    sqm: 898,
    imageUrl: "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?q=80&w=800&auto=format&fit=crop",
    type: "rent",
    propertyType: "apartment",
    virtualTourUrl: "https://my.matterport.com/show/?m=JGPnGQ6hosj",
    lat: -2.283,
    lng: 30.033
  },
  {
    id: "prop-35",
    title: "Renovated Residence in Ruhengeri",
    description: "A renovated house located in Ruhengeri, Musanze. Fits mid-income budgets perfectly and offers great value for the area.",
    price: 114000,
    currency: "USD",
    location: "Ruhengeri",
    city: "Musanze",
    bedrooms: 3,
    bathrooms: 3,
    sqm: 194,
    imageUrl: "https://images.unsplash.com/photo-1605146768851-ea244b94238e?q=80&w=800&auto=format&fit=crop",
    type: "sale",
    propertyType: "house",
    virtualTourUrl: "https://my.matterport.com/show/?m=JGPnGQ6hosj",
    lat: -1.935,
    lng: 30.420
  },
  {
    id: "prop-36",
    title: "Modest Farming Land in Gisozi",
    description: "A modest land located in Gisozi, Kigali. Fits low-income budgets perfectly and offers great value for the area.",
    price: 4200,
    currency: "USD",
    location: "Gisozi",
    city: "Kigali",
    bedrooms: 0,
    bathrooms: 0,
    sqm: 354,
    imageUrl: "https://images.unsplash.com/photo-1605810230434-7631ac76ec81?q=80&w=800&auto=format&fit=crop",
    type: "sale",
    propertyType: "land",
    virtualTourUrl: "https://my.matterport.com/show/?m=JGPnGQ6hosj",
    lat: -1.200,
    lng: 29.997
  },
  {
    id: "prop-37",
    title: "Affordable Shelter in Kimihurura",
    description: "A affordable house located in Kimihurura, Kigali. Fits low-income budgets perfectly and offers great value for the area.",
    price: 29000,
    currency: "USD",
    location: "Kimihurura",
    city: "Kigali",
    bedrooms: 1,
    bathrooms: 1,
    sqm: 76,
    imageUrl: "https://images.unsplash.com/photo-1582268611958-ebfd161ef9cf?q=80&w=800&auto=format&fit=crop",
    type: "sale",
    propertyType: "house",
    virtualTourUrl: "https://my.matterport.com/show/?m=JGPnGQ6hosj",
    lat: -1.318,
    lng: 29.579
  },
  {
    id: "prop-38",
    title: "Classic Residential Plot in Muhoza",
    description: "A classic land located in Muhoza, Musanze. Fits mid-income budgets perfectly and offers great value for the area.",
    price: 54000,
    currency: "USD",
    location: "Muhoza",
    city: "Musanze",
    bedrooms: 0,
    bathrooms: 0,
    sqm: 317,
    imageUrl: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?q=80&w=800&auto=format&fit=crop",
    type: "sale",
    propertyType: "land",
    virtualTourUrl: "https://my.matterport.com/show/?m=JGPnGQ6hosj",
    lat: -1.233,
    lng: 29.496
  },
  {
    id: "prop-39",
    title: "Premium Villa in Ngoma",
    description: "A premium house located in Ngoma, Huye. Fits high-income budgets perfectly and offers great value for the area.",
    price: 747000,
    currency: "USD",
    location: "Ngoma",
    city: "Huye",
    bedrooms: 6,
    bathrooms: 5,
    sqm: 856,
    imageUrl: "https://images.unsplash.com/photo-1523217582562-09d0def993a6?q=80&w=800&auto=format&fit=crop",
    type: "sale",
    propertyType: "house",
    virtualTourUrl: "https://my.matterport.com/show/?m=JGPnGQ6hosj",
    lat: -2.312,
    lng: 29.327
  },
  {
    id: "prop-40",
    title: "Traditional Studio in Gisenyi",
    description: "A traditional apartment located in Gisenyi, Rubavu. Fits low-income budgets perfectly and offers great value for the area.",
    price: 250,
    currency: "USD/month",
    location: "Gisenyi",
    city: "Rubavu",
    bedrooms: 2,
    bathrooms: 1,
    sqm: 80,
    imageUrl: "https://images.unsplash.com/photo-1598228726386-8a03bb3644f7?q=80&w=800&auto=format&fit=crop",
    type: "rent",
    propertyType: "apartment",
    virtualTourUrl: "https://my.matterport.com/show/?m=JGPnGQ6hosj",
    lat: -1.998,
    lng: 30.316
  },
  {
    id: "prop-41",
    title: "Premium Penthouse in Gisenyi",
    description: "A premium apartment located in Gisenyi, Rubavu. Fits high-income budgets perfectly and offers great value for the area.",
    price: 5000,
    currency: "USD/month",
    location: "Gisenyi",
    city: "Rubavu",
    bedrooms: 5,
    bathrooms: 5,
    sqm: 710,
    imageUrl: "https://images.unsplash.com/photo-1507427100689-2bf8574e32d4?q=80&w=800&auto=format&fit=crop",
    type: "rent",
    propertyType: "apartment",
    virtualTourUrl: "https://my.matterport.com/show/?m=JGPnGQ6hosj",
    lat: -2.487,
    lng: 30.177
  },
  {
    id: "prop-42",
    title: "Affordable Starter Home in Ruhengeri",
    description: "A affordable house located in Ruhengeri, Musanze. Fits low-income budgets perfectly and offers great value for the area.",
    price: 70,
    currency: "USD/month",
    location: "Ruhengeri",
    city: "Musanze",
    bedrooms: 1,
    bathrooms: 1,
    sqm: 32,
    imageUrl: "https://images.unsplash.com/photo-1720605739861-9f5110c7e529?q=80&w=800&auto=format&fit=crop",
    type: "rent",
    propertyType: "house",
    virtualTourUrl: "https://my.matterport.com/show/?m=JGPnGQ6hosj",
    lat: -2.607,
    lng: 29.459
  },
  {
    id: "prop-43",
    title: "Simple House in Mukura",
    description: "A simple house located in Mukura, Huye. Fits low-income budgets perfectly and offers great value for the area.",
    price: 50,
    currency: "USD/month",
    location: "Mukura",
    city: "Huye",
    bedrooms: 1,
    bathrooms: 1,
    sqm: 31,
    imageUrl: "https://images.unsplash.com/photo-1682773083908-a0e9ffadd175?q=80&w=800&auto=format&fit=crop",
    type: "rent",
    propertyType: "house",
    virtualTourUrl: "https://my.matterport.com/show/?m=JGPnGQ6hosj",
    lat: -1.992,
    lng: 30.650
  },
  {
    id: "prop-44",
    title: "Affordable Farming Land in Matimba",
    description: "A affordable land located in Matimba, Nyagatare. Fits low-income budgets perfectly and offers great value for the area.",
    price: 12000,
    currency: "USD",
    location: "Matimba",
    city: "Nyagatare",
    bedrooms: 0,
    bathrooms: 0,
    sqm: 123,
    imageUrl: "https://images.unsplash.com/photo-1667504320745-eade6c25e053?q=80&w=800&auto=format&fit=crop",
    type: "sale",
    propertyType: "land",
    virtualTourUrl: "https://my.matterport.com/show/?m=JGPnGQ6hosj",
    lat: -1.871,
    lng: 29.712
  },
  {
    id: "prop-45",
    title: "Charming Apartment in Muhoza",
    description: "A charming apartment located in Muhoza, Musanze. Fits mid-income budgets perfectly and offers great value for the area.",
    price: 111000,
    currency: "USD",
    location: "Muhoza",
    city: "Musanze",
    bedrooms: 2,
    bathrooms: 1,
    sqm: 105,
    imageUrl: "https://images.unsplash.com/photo-1708772565599-2c4e4b3ed9db?q=80&w=800&auto=format&fit=crop",
    type: "sale",
    propertyType: "apartment",
    virtualTourUrl: "https://my.matterport.com/show/?m=JGPnGQ6hosj",
    lat: -1.886,
    lng: 29.578
  },
  {
    id: "prop-46",
    title: "Spacious Flat in Kiyovu",
    description: "A spacious apartment located in Kiyovu, Kigali. Fits mid-income budgets perfectly and offers great value for the area.",
    price: 1000,
    currency: "USD/month",
    location: "Kiyovu",
    city: "Kigali",
    bedrooms: 4,
    bathrooms: 3,
    sqm: 246,
    imageUrl: "https://images.unsplash.com/photo-1689013398932-b576a11e07a1?q=80&w=800&auto=format&fit=crop",
    type: "rent",
    propertyType: "apartment",
    virtualTourUrl: "https://my.matterport.com/show/?m=JGPnGQ6hosj",
    lat: -2.415,
    lng: 29.686
  },
  {
    id: "prop-47",
    title: "Spacious Condo in Kimihurura",
    description: "A spacious apartment located in Kimihurura, Kigali. Fits mid-income budgets perfectly and offers great value for the area.",
    price: 126000,
    currency: "USD",
    location: "Kimihurura",
    city: "Kigali",
    bedrooms: 4,
    bathrooms: 3,
    sqm: 243,
    imageUrl: "https://images.unsplash.com/photo-1708772565588-33785e13aa46?q=80&w=800&auto=format&fit=crop",
    type: "sale",
    propertyType: "apartment",
    virtualTourUrl: "https://my.matterport.com/show/?m=JGPnGQ6hosj",
    lat: -2.509,
    lng: 29.832
  },
  {
    id: "prop-48",
    title: "Budget Compound House in Gihundwe",
    description: "A budget house located in Gihundwe, Rusizi. Fits low-income budgets perfectly and offers great value for the area.",
    price: 100,
    currency: "USD/month",
    location: "Gihundwe",
    city: "Rusizi",
    bedrooms: 2,
    bathrooms: 1,
    sqm: 94,
    imageUrl: "https://images.unsplash.com/photo-1682773083896-95176d8aecf8?q=80&w=800&auto=format&fit=crop",
    type: "rent",
    propertyType: "house",
    virtualTourUrl: "https://my.matterport.com/show/?m=JGPnGQ6hosj",
    lat: -2.159,
    lng: 30.048
  },
  {
    id: "prop-49",
    title: "Spacious Semi-detached House in Shyogwe",
    description: "A spacious house located in Shyogwe, Muhanga. Fits mid-income budgets perfectly and offers great value for the area.",
    price: 63000,
    currency: "USD",
    location: "Shyogwe",
    city: "Muhanga",
    bedrooms: 3,
    bathrooms: 3,
    sqm: 143,
    imageUrl: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?q=80&w=800&auto=format&fit=crop",
    type: "sale",
    propertyType: "house",
    virtualTourUrl: "https://my.matterport.com/show/?m=JGPnGQ6hosj",
    lat: -2.098,
    lng: 29.499
  },
  {
    id: "prop-50",
    title: "Spacious Serviced Apartment in Muhoza",
    description: "A spacious apartment located in Muhoza, Musanze. Fits mid-income budgets perfectly and offers great value for the area.",
    price: 97000,
    currency: "USD",
    location: "Muhoza",
    city: "Musanze",
    bedrooms: 3,
    bathrooms: 2,
    sqm: 175,
    imageUrl: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?q=80&w=800&auto=format&fit=crop",
    type: "sale",
    propertyType: "apartment",
    virtualTourUrl: "https://my.matterport.com/show/?m=JGPnGQ6hosj",
    lat: -1.319,
    lng: 29.414
  },
  {
    id: "prop-51",
    title: "Secure Condo in Nyamabuye",
    description: "A secure apartment located in Nyamabuye, Muhanga. Fits mid-income budgets perfectly and offers great value for the area.",
    price: 58000,
    currency: "USD",
    location: "Nyamabuye",
    city: "Muhanga",
    bedrooms: 4,
    bathrooms: 4,
    sqm: 159,
    imageUrl: "https://images.unsplash.com/photo-1600607688969-a5bfcd646154?q=80&w=800&auto=format&fit=crop",
    type: "sale",
    propertyType: "apartment",
    virtualTourUrl: "https://my.matterport.com/show/?m=JGPnGQ6hosj",
    lat: -2.314,
    lng: 30.046
  },
  {
    id: "prop-52",
    title: "Elegant Retreat in Nyamabuye",
    description: "A elegant house located in Nyamabuye, Muhanga. Fits high-income budgets perfectly and offers great value for the area.",
    price: 275000,
    currency: "USD",
    location: "Nyamabuye",
    city: "Muhanga",
    bedrooms: 6,
    bathrooms: 6,
    sqm: 989,
    imageUrl: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?q=80&w=800&auto=format&fit=crop",
    type: "sale",
    propertyType: "house",
    virtualTourUrl: "https://my.matterport.com/show/?m=JGPnGQ6hosj",
    lat: -1.837,
    lng: 29.871
  },
  {
    id: "prop-53",
    title: "Basic Compound House in Cyeza",
    description: "A basic house located in Cyeza, Muhanga. Fits low-income budgets perfectly and offers great value for the area.",
    price: 6100,
    currency: "USD",
    location: "Cyeza",
    city: "Muhanga",
    bedrooms: 2,
    bathrooms: 2,
    sqm: 29,
    imageUrl: "https://images.unsplash.com/photo-1518780664697-5b050e0bb626?q=80&w=800&auto=format&fit=crop",
    type: "sale",
    propertyType: "house",
    virtualTourUrl: "https://my.matterport.com/show/?m=JGPnGQ6hosj",
    lat: -1.556,
    lng: 29.879
  },
  {
    id: "prop-54",
    title: "Exclusive Mansion in Tumba",
    description: "A exclusive house located in Tumba, Huye. Fits high-income budgets perfectly and offers great value for the area.",
    price: 999000,
    currency: "USD",
    location: "Tumba",
    city: "Huye",
    bedrooms: 6,
    bathrooms: 5,
    sqm: 434,
    imageUrl: "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?q=80&w=800&auto=format&fit=crop",
    type: "sale",
    propertyType: "house",
    virtualTourUrl: "https://my.matterport.com/show/?m=JGPnGQ6hosj",
    lat: -1.837,
    lng: 30.424
  },
  {
    id: "prop-55",
    title: "Modern Semi-detached House in Gacuriro",
    description: "A modern house located in Gacuriro, Kigali. Fits mid-income budgets perfectly and offers great value for the area.",
    price: 136000,
    currency: "USD",
    location: "Gacuriro",
    city: "Kigali",
    bedrooms: 2,
    bathrooms: 1,
    sqm: 179,
    imageUrl: "https://images.unsplash.com/photo-1605146768851-ea244b94238e?q=80&w=800&auto=format&fit=crop",
    type: "sale",
    propertyType: "house",
    virtualTourUrl: "https://my.matterport.com/show/?m=JGPnGQ6hosj",
    lat: -1.932,
    lng: 30.791
  },
  {
    id: "prop-56",
    title: "Family Semi-detached House in Gisenyi",
    description: "A family house located in Gisenyi, Rubavu. Fits mid-income budgets perfectly and offers great value for the area.",
    price: 77000,
    currency: "USD",
    location: "Gisenyi",
    city: "Rubavu",
    bedrooms: 3,
    bathrooms: 2,
    sqm: 169,
    imageUrl: "https://images.unsplash.com/photo-1605810230434-7631ac76ec81?q=80&w=800&auto=format&fit=crop",
    type: "sale",
    propertyType: "house",
    virtualTourUrl: "https://my.matterport.com/show/?m=JGPnGQ6hosj",
    lat: -1.240,
    lng: 29.482
  },
  {
    id: "prop-57",
    title: "Classic Farm in Mururu",
    description: "A classic land located in Mururu, Rusizi. Fits mid-income budgets perfectly and offers great value for the area.",
    price: 550,
    currency: "USD/month",
    location: "Mururu",
    city: "Rusizi",
    bedrooms: 0,
    bathrooms: 0,
    sqm: 1210,
    imageUrl: "https://images.unsplash.com/photo-1582268611958-ebfd161ef9cf?q=80&w=800&auto=format&fit=crop",
    type: "rent",
    propertyType: "land",
    virtualTourUrl: "https://my.matterport.com/show/?m=JGPnGQ6hosj",
    lat: -1.274,
    lng: 30.318
  },
  {
    id: "prop-58",
    title: "Beautiful Mansion in Mukura",
    description: "A beautiful house located in Mukura, Huye. Fits high-income budgets perfectly and offers great value for the area.",
    price: 357000,
    currency: "USD",
    location: "Mukura",
    city: "Huye",
    bedrooms: 6,
    bathrooms: 5,
    sqm: 532,
    imageUrl: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?q=80&w=800&auto=format&fit=crop",
    type: "sale",
    propertyType: "house",
    virtualTourUrl: "https://my.matterport.com/show/?m=JGPnGQ6hosj",
    lat: -1.793,
    lng: 29.903
  },
  {
    id: "prop-59",
    title: "Cozy Residential Plot in Gisenyi",
    description: "A cozy land located in Gisenyi, Rubavu. Fits mid-income budgets perfectly and offers great value for the area.",
    price: 56000,
    currency: "USD",
    location: "Gisenyi",
    city: "Rubavu",
    bedrooms: 0,
    bathrooms: 0,
    sqm: 597,
    imageUrl: "https://images.unsplash.com/photo-1523217582562-09d0def993a6?q=80&w=800&auto=format&fit=crop",
    type: "sale",
    propertyType: "land",
    virtualTourUrl: "https://my.matterport.com/show/?m=JGPnGQ6hosj",
    lat: -2.192,
    lng: 30.224
  },
  {
    id: "prop-60",
    title: "Classic Serviced Apartment in Rugerero",
    description: "A classic apartment located in Rugerero, Rubavu. Fits mid-income budgets perfectly and offers great value for the area.",
    price: 148000,
    currency: "USD",
    location: "Rugerero",
    city: "Rubavu",
    bedrooms: 3,
    bathrooms: 3,
    sqm: 207,
    imageUrl: "https://images.unsplash.com/photo-1598228726386-8a03bb3644f7?q=80&w=800&auto=format&fit=crop",
    type: "sale",
    propertyType: "apartment",
    virtualTourUrl: "https://my.matterport.com/show/?m=JGPnGQ6hosj",
    lat: -1.452,
    lng: 30.120
  },
  {
    id: "prop-61",
    title: "Spacious Condo in Muhoza",
    description: "A spacious apartment located in Muhoza, Musanze. Fits mid-income budgets perfectly and offers great value for the area.",
    price: 54000,
    currency: "USD",
    location: "Muhoza",
    city: "Musanze",
    bedrooms: 2,
    bathrooms: 1,
    sqm: 194,
    imageUrl: "https://images.unsplash.com/photo-1507427100689-2bf8574e32d4?q=80&w=800&auto=format&fit=crop",
    type: "sale",
    propertyType: "apartment",
    virtualTourUrl: "https://my.matterport.com/show/?m=JGPnGQ6hosj",
    lat: -2.330,
    lng: 30.186
  },
  {
    id: "prop-62",
    title: "Affordable Annexe in Gisenyi",
    description: "A affordable house located in Gisenyi, Rubavu. Fits low-income budgets perfectly and offers great value for the area.",
    price: 20000,
    currency: "USD",
    location: "Gisenyi",
    city: "Rubavu",
    bedrooms: 1,
    bathrooms: 1,
    sqm: 71,
    imageUrl: "https://images.unsplash.com/photo-1720605739861-9f5110c7e529?q=80&w=800&auto=format&fit=crop",
    type: "sale",
    propertyType: "house",
    virtualTourUrl: "https://my.matterport.com/show/?m=JGPnGQ6hosj",
    lat: -1.359,
    lng: 30.276
  },
  {
    id: "prop-63",
    title: "Affordable Shelter in Mukura",
    description: "A affordable house located in Mukura, Huye. Fits low-income budgets perfectly and offers great value for the area.",
    price: 70,
    currency: "USD/month",
    location: "Mukura",
    city: "Huye",
    bedrooms: 2,
    bathrooms: 2,
    sqm: 89,
    imageUrl: "https://images.unsplash.com/photo-1682773083908-a0e9ffadd175?q=80&w=800&auto=format&fit=crop",
    type: "rent",
    propertyType: "house",
    virtualTourUrl: "https://my.matterport.com/show/?m=JGPnGQ6hosj",
    lat: -1.558,
    lng: 30.213
  },
  {
    id: "prop-64",
    title: "Basic Room in Cyeza",
    description: "A basic apartment located in Cyeza, Muhanga. Fits low-income budgets perfectly and offers great value for the area.",
    price: 150,
    currency: "USD/month",
    location: "Cyeza",
    city: "Muhanga",
    bedrooms: 2,
    bathrooms: 1,
    sqm: 95,
    imageUrl: "https://images.unsplash.com/photo-1667504320745-eade6c25e053?q=80&w=800&auto=format&fit=crop",
    type: "rent",
    propertyType: "apartment",
    virtualTourUrl: "https://my.matterport.com/show/?m=JGPnGQ6hosj",
    lat: -1.932,
    lng: 29.989
  },
  {
    id: "prop-65",
    title: "Stunning Retreat in Gisenyi",
    description: "A stunning house located in Gisenyi, Rubavu. Fits high-income budgets perfectly and offers great value for the area.",
    price: 4100,
    currency: "USD/month",
    location: "Gisenyi",
    city: "Rubavu",
    bedrooms: 5,
    bathrooms: 4,
    sqm: 563,
    imageUrl: "https://images.unsplash.com/photo-1708772565599-2c4e4b3ed9db?q=80&w=800&auto=format&fit=crop",
    type: "rent",
    propertyType: "house",
    virtualTourUrl: "https://my.matterport.com/show/?m=JGPnGQ6hosj",
    lat: -1.998,
    lng: 30.722
  },
  {
    id: "prop-66",
    title: "Traditional Farming Land in Mukura",
    description: "A traditional land located in Mukura, Huye. Fits low-income budgets perfectly and offers great value for the area.",
    price: 10000,
    currency: "USD",
    location: "Mukura",
    city: "Huye",
    bedrooms: 0,
    bathrooms: 0,
    sqm: 346,
    imageUrl: "https://images.unsplash.com/photo-1689013398932-b576a11e07a1?q=80&w=800&auto=format&fit=crop",
    type: "sale",
    propertyType: "land",
    virtualTourUrl: "https://my.matterport.com/show/?m=JGPnGQ6hosj",
    lat: -1.520,
    lng: 29.436
  },
  {
    id: "prop-67",
    title: "Charming Bungalow in Nyagatare",
    description: "A charming house located in Nyagatare, Nyagatare. Fits mid-income budgets perfectly and offers great value for the area.",
    price: 1000,
    currency: "USD/month",
    location: "Nyagatare",
    city: "Nyagatare",
    bedrooms: 4,
    bathrooms: 4,
    sqm: 196,
    imageUrl: "https://images.unsplash.com/photo-1708772565588-33785e13aa46?q=80&w=800&auto=format&fit=crop",
    type: "rent",
    propertyType: "house",
    virtualTourUrl: "https://my.matterport.com/show/?m=JGPnGQ6hosj",
    lat: -1.630,
    lng: 30.702
  },
  {
    id: "prop-68",
    title: "Spacious Bungalow in Rwimiyaga",
    description: "A spacious house located in Rwimiyaga, Nyagatare. Fits mid-income budgets perfectly and offers great value for the area.",
    price: 64000,
    currency: "USD",
    location: "Rwimiyaga",
    city: "Nyagatare",
    bedrooms: 2,
    bathrooms: 1,
    sqm: 109,
    imageUrl: "https://images.unsplash.com/photo-1682773083896-95176d8aecf8?q=80&w=800&auto=format&fit=crop",
    type: "sale",
    propertyType: "house",
    virtualTourUrl: "https://my.matterport.com/show/?m=JGPnGQ6hosj",
    lat: -2.313,
    lng: 30.197
  },
  {
    id: "prop-69",
    title: "Beautiful Estate in Gihundwe",
    description: "A beautiful house located in Gihundwe, Rusizi. Fits high-income budgets perfectly and offers great value for the area.",
    price: 739000,
    currency: "USD",
    location: "Gihundwe",
    city: "Rusizi",
    bedrooms: 3,
    bathrooms: 2,
    sqm: 824,
    imageUrl: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?q=80&w=800&auto=format&fit=crop",
    type: "sale",
    propertyType: "house",
    virtualTourUrl: "https://my.matterport.com/show/?m=JGPnGQ6hosj",
    lat: -2.226,
    lng: 29.398
  },
  {
    id: "prop-70",
    title: "Modern Residential Plot in Muhoza",
    description: "A modern land located in Muhoza, Musanze. Fits mid-income budgets perfectly and offers great value for the area.",
    price: 41000,
    currency: "USD",
    location: "Muhoza",
    city: "Musanze",
    bedrooms: 0,
    bathrooms: 0,
    sqm: 382,
    imageUrl: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?q=80&w=800&auto=format&fit=crop",
    type: "sale",
    propertyType: "land",
    virtualTourUrl: "https://my.matterport.com/show/?m=JGPnGQ6hosj",
    lat: -2.384,
    lng: 29.575
  },
  {
    id: "prop-71",
    title: "Classic Residential Plot in Muhoza",
    description: "A classic land located in Muhoza, Musanze. Fits mid-income budgets perfectly and offers great value for the area.",
    price: 550,
    currency: "USD/month",
    location: "Muhoza",
    city: "Musanze",
    bedrooms: 0,
    bathrooms: 0,
    sqm: 462,
    imageUrl: "https://images.unsplash.com/photo-1600607688969-a5bfcd646154?q=80&w=800&auto=format&fit=crop",
    type: "rent",
    propertyType: "land",
    virtualTourUrl: "https://my.matterport.com/show/?m=JGPnGQ6hosj",
    lat: -2.500,
    lng: 30.784
  },
  {
    id: "prop-72",
    title: "Traditional Room in Nyamabuye",
    description: "A traditional apartment located in Nyamabuye, Muhanga. Fits low-income budgets perfectly and offers great value for the area.",
    price: 27000,
    currency: "USD",
    location: "Nyamabuye",
    city: "Muhanga",
    bedrooms: 3,
    bathrooms: 2,
    sqm: 54,
    imageUrl: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?q=80&w=800&auto=format&fit=crop",
    type: "sale",
    propertyType: "apartment",
    virtualTourUrl: "https://my.matterport.com/show/?m=JGPnGQ6hosj",
    lat: -2.025,
    lng: 29.981
  },
  {
    id: "prop-73",
    title: "Spacious Development Land in Ruhengeri",
    description: "A spacious land located in Ruhengeri, Musanze. Fits mid-income budgets perfectly and offers great value for the area.",
    price: 74000,
    currency: "USD",
    location: "Ruhengeri",
    city: "Musanze",
    bedrooms: 0,
    bathrooms: 0,
    sqm: 741,
    imageUrl: "https://images.unsplash.com/photo-1518780664697-5b050e0bb626?q=80&w=800&auto=format&fit=crop",
    type: "sale",
    propertyType: "land",
    virtualTourUrl: "https://my.matterport.com/show/?m=JGPnGQ6hosj",
    lat: -2.325,
    lng: 29.624
  },
  {
    id: "prop-74",
    title: "Secure Bungalow in Mururu",
    description: "A secure house located in Mururu, Rusizi. Fits mid-income budgets perfectly and offers great value for the area.",
    price: 67000,
    currency: "USD",
    location: "Mururu",
    city: "Rusizi",
    bedrooms: 3,
    bathrooms: 3,
    sqm: 228,
    imageUrl: "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?q=80&w=800&auto=format&fit=crop",
    type: "sale",
    propertyType: "house",
    virtualTourUrl: "https://my.matterport.com/show/?m=JGPnGQ6hosj",
    lat: -1.276,
    lng: 29.678
  },
  {
    id: "prop-75",
    title: "Renovated Semi-detached House in Nyamyumba",
    description: "A renovated house located in Nyamyumba, Rubavu. Fits mid-income budgets perfectly and offers great value for the area.",
    price: 1100,
    currency: "USD/month",
    location: "Nyamyumba",
    city: "Rubavu",
    bedrooms: 2,
    bathrooms: 2,
    sqm: 110,
    imageUrl: "https://images.unsplash.com/photo-1605146768851-ea244b94238e?q=80&w=800&auto=format&fit=crop",
    type: "rent",
    propertyType: "house",
    virtualTourUrl: "https://my.matterport.com/show/?m=JGPnGQ6hosj",
    lat: -1.558,
    lng: 29.651
  },
  {
    id: "prop-76",
    title: "Beautiful Luxury Home in Ngoma",
    description: "A beautiful house located in Ngoma, Huye. Fits high-income budgets perfectly and offers great value for the area.",
    price: 329000,
    currency: "USD",
    location: "Ngoma",
    city: "Huye",
    bedrooms: 5,
    bathrooms: 4,
    sqm: 899,
    imageUrl: "https://images.unsplash.com/photo-1605810230434-7631ac76ec81?q=80&w=800&auto=format&fit=crop",
    type: "sale",
    propertyType: "house",
    virtualTourUrl: "https://my.matterport.com/show/?m=JGPnGQ6hosj",
    lat: -1.190,
    lng: 30.194
  },
  {
    id: "prop-77",
    title: "Beautiful Villa in Tumba",
    description: "A beautiful house located in Tumba, Huye. Fits high-income budgets perfectly and offers great value for the area.",
    price: 3200,
    currency: "USD/month",
    location: "Tumba",
    city: "Huye",
    bedrooms: 5,
    bathrooms: 4,
    sqm: 315,
    imageUrl: "https://images.unsplash.com/photo-1582268611958-ebfd161ef9cf?q=80&w=800&auto=format&fit=crop",
    type: "rent",
    propertyType: "house",
    virtualTourUrl: "https://my.matterport.com/show/?m=JGPnGQ6hosj",
    lat: -1.606,
    lng: 30.202
  },
  {
    id: "prop-78",
    title: "Secure Condo in Matimba",
    description: "A secure apartment located in Matimba, Nyagatare. Fits mid-income budgets perfectly and offers great value for the area.",
    price: 500,
    currency: "USD/month",
    location: "Matimba",
    city: "Nyagatare",
    bedrooms: 2,
    bathrooms: 2,
    sqm: 166,
    imageUrl: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?q=80&w=800&auto=format&fit=crop",
    type: "rent",
    propertyType: "apartment",
    virtualTourUrl: "https://my.matterport.com/show/?m=JGPnGQ6hosj",
    lat: -2.340,
    lng: 30.645
  },
  {
    id: "prop-79",
    title: "Classic Residence in Kanombe",
    description: "A classic house located in Kanombe, Kigali. Fits mid-income budgets perfectly and offers great value for the area.",
    price: 108000,
    currency: "USD",
    location: "Kanombe",
    city: "Kigali",
    bedrooms: 2,
    bathrooms: 2,
    sqm: 140,
    imageUrl: "https://images.unsplash.com/photo-1523217582562-09d0def993a6?q=80&w=800&auto=format&fit=crop",
    type: "sale",
    propertyType: "house",
    virtualTourUrl: "https://my.matterport.com/show/?m=JGPnGQ6hosj",
    lat: -1.869,
    lng: 29.881
  },
  {
    id: "prop-80",
    title: "Starter Room in Kinigi",
    description: "A starter apartment located in Kinigi, Musanze. Fits low-income budgets perfectly and offers great value for the area.",
    price: 50,
    currency: "USD/month",
    location: "Kinigi",
    city: "Musanze",
    bedrooms: 3,
    bathrooms: 2,
    sqm: 76,
    imageUrl: "https://images.unsplash.com/photo-1598228726386-8a03bb3644f7?q=80&w=800&auto=format&fit=crop",
    type: "rent",
    propertyType: "apartment",
    virtualTourUrl: "https://my.matterport.com/show/?m=JGPnGQ6hosj",
    lat: -2.479,
    lng: 29.981
  }
];
