// Prototype Seed Data for Execution Tracking Module

import { ExecutionProject } from "./types";

export function executionSeedProjects(): ExecutionProject[] {
  const now = new Date().toISOString();

  return [
    {
      id: "exec-build-kigali",
      name: "Kigali Family Home",
      sourceType: "build",
      sourceProjectId: "build-p1",
      sourceQuotationId: "quote-imara-1",
      customerName: "Jane Doe",
      customerId: "demo-user",
      customerEmail: "buyer@huzaestate.com",
      customerPhone: "+250 788 123 456",
      contractorName: "Imara Construction Ltd",
      contractorId: "imara-user",
      contractorEmail: "contractor@huzaestate.com",
      contractorPhone: "+250 788 999 888",
      location: "Nyarutarama, Kigali",
      designVersionName: "Modern Villa v2 (Approved)",
      approvedScopeSummary: "Full construction of a 4-bedroom luxury villa with pool and outdoor landscaping.",
      contractValue: 145000000, // 145M RWF
      originalContractValue: 145000000,
      currency: "RWF",
      startDate: "2026-06-01",
      targetCompletionDate: "2026-12-15",
      status: "active",
      overallProgressPercent: 35,
      latestProgressImageUrl: "https://images.unsplash.com/photo-1541888946425-d0fbb186a5b3?q=80&w=800&auto=format&fit=crop",
      nextRequiredAction: "Review upcoming Structural Frame inspection scheduled for Friday.",
      customerSetupConfirmed: true,
      contractorSetupConfirmed: true,
      leadProfessionalSetupConfirmed: true,
      communication: {
        primaryChannel: "Huza Messaging & Weekly On-Site Briefings",
        progressReportFrequency: "weekly",
        siteMeetingFrequency: "weekly",
        emergencyContacts: "Site Mgr: +250 788 000 111",
        changeApprovalContacts: "Jane Doe (Client)",
        inspectionContacts: "Eric Habimana (Structural Eng)",
      },
      team: [
        {
          id: "tm-1",
          userId: "demo-user",
          name: "Jane Doe",
          role: "customer",
          email: "buyer@huzaestate.com",
          phone: "+250 788 123 456",
          permissions: ["view", "approve_changes", "accept_handover"],
          startDate: "2026-06-01",
          contactPreferences: "Email & WhatsApp",
          isEmergencyContact: true,
          confirmed: true,
        },
        {
          id: "tm-2",
          userId: "imara-user",
          name: "Imara Construction Ltd",
          role: "contractor",
          email: "contractor@huzaestate.com",
          phone: "+250 788 999 888",
          company: "Imara Construction Ltd",
          permissions: ["update_schedule", "site_diary", "submit_milestones"],
          startDate: "2026-06-01",
          contactPreferences: "Phone call",
          isEmergencyContact: true,
          confirmed: true,
        },
        {
          id: "tm-3",
          userId: "aline-user",
          name: "Aline Uwase",
          role: "architect",
          email: "architect@huzaestate.com",
          phone: "+250 788 222 333",
          company: "Kigali Design Studio",
          permissions: ["review_substitutions", "rfi_response"],
          startDate: "2026-06-01",
          contactPreferences: "Email",
          isEmergencyContact: false,
          confirmed: true,
        },
        {
          id: "tm-4",
          userId: "eric-user",
          name: "Eric Habimana",
          role: "engineer",
          email: "structural@huzaestate.com",
          phone: "+250 788 444 555",
          company: "Rwanda Structural Consultants",
          permissions: ["perform_inspections", "signoff_technical"],
          startDate: "2026-06-01",
          contactPreferences: "Phone call",
          isEmergencyContact: true,
          confirmed: true,
        },
        {
          id: "tm-5",
          userId: "diane-user",
          name: "Diane Mukamana",
          role: "quantity_surveyor",
          email: "surveyor@huzaestate.com",
          phone: "+250 788 666 777",
          permissions: ["review_variations", "verify_milestone_claims"],
          startDate: "2026-06-01",
          contactPreferences: "Email",
          isEmergencyContact: false,
          confirmed: true,
        },
      ],
      approvals: [
        {
          id: "app-1",
          name: "City of Kigali Building Permit",
          category: "permit",
          status: "approved",
          referenceNumber: "KGL-BP-2026-089",
          issuingAuthority: "Kigali City Construction Permitting",
          approvalDate: "2026-05-15",
          expiryDate: "2028-05-15",
          supportingDocIds: ["doc-bp-1"],
          notes: "Approved for 2-storey residential building.",
        },
        {
          id: "app-2",
          name: "Environmental Impact Exemption",
          category: "environmental",
          status: "approved",
          referenceNumber: "REMA-ENV-554",
          issuingAuthority: "REMA Rwanda",
          approvalDate: "2026-05-10",
          supportingDocIds: [],
        },
        {
          id: "app-3",
          name: "WASAC & EUCL Utility Clearance",
          category: "utility",
          status: "approved",
          approvalDate: "2026-05-20",
          supportingDocIds: [],
        },
      ],
      workPackages: [
        { id: "wp-1", name: "Site Preparation & Substructure", phase: "Foundation and substructure", description: "Excavation, footings, reinforced concrete slab.", leadRole: "contractor", taskIds: ["tsk-101", "tsk-102"], progressPercent: 100 },
        { id: "wp-2", name: "Structural Frame & Walls", phase: "Structural work", description: "Columns, masonry infill, ground & upper storey beam casting.", leadRole: "contractor", taskIds: ["tsk-201", "tsk-202", "tsk-203"], progressPercent: 65 },
        { id: "wp-3", name: "Roofing Structure", phase: "Roofing", description: "Steel trusses, timber battens, iron sheet roofing.", leadRole: "contractor", taskIds: ["tsk-301"], progressPercent: 0 },
      ],
      tasks: [
        { id: "tsk-101", workPackageId: "wp-1", phase: "Foundation and substructure", title: "Excavation & Ground Preparation", description: "Site clearing and footing trench excavation.", plannedStart: "2026-06-01", plannedFinish: "2026-06-15", actualStart: "2026-06-01", actualFinish: "2026-06-14", assigneeName: "Imara Construction Ltd", assigneeRole: "contractor", progressPercent: 100, status: "completed", priority: "normal", dependencies: [] },
        { id: "tsk-102", workPackageId: "wp-1", phase: "Foundation and substructure", title: "Foundation Pour & Slab", description: "Pouring concrete footings and ground slab.", plannedStart: "2026-06-16", plannedFinish: "2026-07-05", actualStart: "2026-06-16", actualFinish: "2026-07-04", assigneeName: "Imara Construction Ltd", assigneeRole: "contractor", progressPercent: 100, status: "completed", priority: "high", dependencies: ["tsk-101"] },
        { id: "tsk-201", workPackageId: "wp-2", phase: "Structural work", title: "Ground Floor Concrete Columns", description: "Rebar tying, formwork and pouring columns.", plannedStart: "2026-07-06", plannedFinish: "2026-07-25", actualStart: "2026-07-06", actualFinish: "2026-07-24", assigneeName: "Imara Construction Ltd", assigneeRole: "contractor", progressPercent: 100, status: "completed", priority: "critical", dependencies: ["tsk-102"] },
        { id: "tsk-202", workPackageId: "wp-2", phase: "Structural work", title: "Masonry Brick Walls (Ground Floor)", description: "Laying hollow cement blocks and brickwork.", plannedStart: "2026-07-26", plannedFinish: "2026-08-20", actualStart: "2026-07-26", assigneeName: "Imara Construction Ltd", assigneeRole: "contractor", progressPercent: 70, status: "in_progress", priority: "normal", dependencies: ["tsk-201"] },
        { id: "tsk-203", workPackageId: "wp-2", phase: "Structural work", title: "First Floor Slab Formwork & Rebar", description: "Formwork setting and steel reinforcement placement.", plannedStart: "2026-08-21", plannedFinish: "2026-09-10", assigneeName: "Imara Construction Ltd", assigneeRole: "contractor", progressPercent: 20, status: "in_progress", priority: "high", dependencies: ["tsk-202"] },
        { id: "tsk-301", workPackageId: "wp-3", phase: "Roofing", title: "Roof Truss Fabrication & Erection", description: "Steel truss alignment and roofing sheet installation.", plannedStart: "2026-09-11", plannedFinish: "2026-09-30", assigneeName: "Imara Construction Ltd", assigneeRole: "contractor", progressPercent: 0, status: "not_started", priority: "normal", dependencies: ["tsk-203"] },
      ],
      milestones: [
        {
          id: "m-1",
          title: "Milestone 1: Substructure & Slab Completion",
          description: "Completion of all foundation footings, damp-proofing, plumbing rough-in under slab, and slab pour.",
          relatedTaskIds: ["tsk-101", "tsk-102"],
          plannedDate: "2026-07-05",
          actualCompletionDate: "2026-07-04",
          completionCriteria: ["Foundation inspection passed", "Concrete cube test report uploaded", "Slab level verified"],
          requiredEvidence: ["Inspection certificate", "Photo gallery of slab pour"],
          responsibleParty: "Imara Construction Ltd",
          contractValueAllocation: 29000000,
          status: "accepted",
          customerReviewNotes: "Reviewed and confirmed by client.",
          customerAcceptedAt: "2026-07-06",
          professionalReviewNotes: "Passed by Eric Habimana.",
          professionalApprovedAt: "2026-07-05",
          paymentEligibility: "eligible",
          submissionSummary: "Substructure work finished 1 day ahead of schedule.",
          submittedEvidenceUrls: ["https://images.unsplash.com/photo-1541888946425-d0fbb186a5b3?q=80&w=800&auto=format&fit=crop"],
        },
        {
          id: "m-2",
          title: "Milestone 2: Ground Floor Frame & First Floor Concrete Slab",
          description: "Column completion, brick masonry, first floor slab rebar placement and concrete casting.",
          relatedTaskIds: ["tsk-201", "tsk-202", "tsk-203"],
          plannedDate: "2026-09-10",
          completionCriteria: ["Structural engineer inspection signoff", "Masonry alignment check", "Rebar layout approval"],
          requiredEvidence: ["Structural inspection report", "Formwork verification photos"],
          responsibleParty: "Imara Construction Ltd",
          contractValueAllocation: 43500000,
          status: "in_progress",
          paymentEligibility: "eligibility_pending",
        },
      ],
      siteDiary: [
        {
          id: "sd-101",
          date: "2026-08-28",
          workPackageId: "wp-2",
          workCompleted: "Completed bricklaying for main living area east wall. Prepared rebar for 4 main columns.",
          workInProgress: "First floor slab formwork installation.",
          labourCount: 18,
          contractorTeams: ["Masonry Team A (8)", "Rebar Steel Fixers (6)", "Site Helpers (4)"],
          equipmentOnSite: ["1x Concrete Mixer 350L", "2x Plate Compactors", "Scaffolding sets"],
          materialsUsed: ["120 Bags Ciment de Rwanda 42.5N", "2,400 Clay bricks", "12mm High-yield Steel Rebar"],
          deliveriesReceived: ["15 Tons River sand from Nyabarongo"],
          siteConditions: "Dry, clean, safety perimeter clear.",
          weatherSummary: "Sunny, 27°C, light breeze",
          visitors: ["Aline Uwase (Architect) - Site walk at 11:00 AM"],
          inspectionsHeld: ["Internal quality check on brick mortar mix ratio"],
          delaysEncountered: "None",
          incidents: "Nil",
          safetyObservations: "All workers wearing helmets, boots, and high-visibility vests.",
          photoUrls: ["https://images.unsplash.com/photo-1541888946425-d0fbb186a5b3?q=80&w=800&auto=format&fit=crop"],
          videoUrls: [],
          notes: "Architect approved brick mortar color tone.",
          submittedBy: "Jean Paul Ndayisaba (Site Supervisor)",
          submittedByRole: "site_supervisor",
          submittedAt: "2026-08-28T17:30:00Z",
          status: "locked",
          amendments: [],
          comments: [
            { id: "sdc-1", authorName: "Jane Doe", authorRole: "customer", timestamp: "2026-08-28T18:45:00Z", text: "Great progress on the living room walls!" },
          ],
        },
      ],
      progressReports: [
        {
          id: "pr-1",
          reportType: "weekly_report",
          periodStart: "2026-08-21",
          periodEnd: "2026-08-28",
          plannedProgressPercent: 33,
          actualProgressPercent: 35,
          completedWorkSummary: "Finished main ground floor masonry walls up to beam level. Assembled 70% of first floor slab formwork.",
          currentWorkSummary: "Fixing upper steel reinforcement and beam stirrups.",
          upcomingWorkSummary: "Concrete casting for first floor slab scheduled for September 5.",
          delaysAndBlockers: "Minor delay in gravel delivery resolved.",
          risksAndMitigations: "Rain forecast next week — tarpaulins secured for fresh masonry.",
          decisionsRequired: "Confirmation of window frame recess dimensions from architect.",
          evidencePhotoUrls: ["https://images.unsplash.com/photo-1541888946425-d0fbb186a5b3?q=80&w=800&auto=format&fit=crop"],
          updatedCompletionForecast: "On track for Dec 15, 2026",
          submittedBy: "Imara Construction Ltd",
          submittedAt: "2026-08-28T18:00:00Z",
          isAiObservation: true,
        },
      ],
      materials: [
        {
          id: "mat-1",
          materialName: "Ciment de Rwanda 42.5N",
          specification: "High strength Portland cement CEM I 42.5N",
          quantity: 400,
          unit: "bags",
          sourceSupplier: "Cimerwa Ltd",
          requiredDate: "2026-08-15",
          orderedDate: "2026-08-10",
          actualDeliveryDate: "2026-08-14",
          status: "delivered",
          inspectionStatus: "passed",
          storageLocationOnSite: "Dry covered storage shed A",
          relatedTaskId: "tsk-202",
          deliveryPhotos: ["https://images.unsplash.com/photo-1589939705384-5185137a7f0f?q=80&w=800&auto=format&fit=crop"],
          supportingDocIds: ["doc-mat-inv-1"],
        },
        {
          id: "mat-2",
          materialName: "High-Yield Steel Rebar 16mm",
          specification: "BS 4449 Grade 500B Deformed Steel Rebar",
          quantity: 3.5,
          unit: "tons",
          sourceSupplier: "Kigali Steel Works",
          requiredDate: "2026-08-20",
          orderedDate: "2026-08-15",
          actualDeliveryDate: "2026-08-22",
          status: "delivered",
          inspectionStatus: "passed",
          storageLocationOnSite: "Rebar yard rack B",
          relatedTaskId: "tsk-203",
          supportingDocIds: [],
        },
      ],
      substitutions: [
        {
          id: "sub-1",
          originalMaterial: "Standard Clay Facing Bricks (Imported)",
          proposedReplacement: "Ruliba High-Density Clay Bricks (Local)",
          reason: "Imported bricks delayed at border customs by 3 weeks. Local Ruliba bricks meet structural load standards.",
          costImpact: -850000, // Cost savings of 850k RWF
          scheduleImpactDays: -5, // Saves 5 days delay
          performanceDifference: "Equal compressive strength (15 MPa). Slightly higher thermal mass.",
          appearanceDifference: "Warm terra-cotta tone, matches architectural design render.",
          warrantyDifference: "Manufacturer 20-year structural clay warranty.",
          samplePhotoUrls: ["https://images.unsplash.com/photo-1590069261209-f8e9b8642343?q=80&w=800&auto=format&fit=crop"],
          submittedBy: "Imara Construction Ltd",
          submittedAt: "2026-08-25T10:00:00Z",
          status: "under_review",
          professionalReviewer: "Aline Uwase (Architect)",
          professionalNotes: "Recommending approval — sample block passes aesthetic and strength checks.",
        },
      ],
      inspections: [
        {
          id: "insp-1",
          type: "foundation",
          title: "Substructure & Slab Reinforcement Inspection",
          relatedMilestoneId: "m-1",
          requestedBy: "Imara Construction Ltd",
          assignedInspectorName: "Eric Habimana",
          assignedInspectorRole: "engineer",
          scheduledDate: "2026-07-04",
          completedDate: "2026-07-04",
          locationOnSite: "Ground slab footings and rebar grid",
          checklist: [
            { id: "chk-1", label: "Trench depth and soil compaction verified", passed: true },
            { id: "chk-2", label: "Damp-proof membrane continuity check", passed: true },
            { id: "chk-3", label: "Rebar spacing and cover blocks placement", passed: true },
          ],
          evidencePhotoUrls: ["https://images.unsplash.com/photo-1541888946425-d0fbb186a5b3?q=80&w=800&auto=format&fit=crop"],
          findings: "Rebar cover and lap lengths strictly conform to structural drawings. Approved to pour concrete.",
          reinspectionRequired: false,
          outcome: "passed",
          inspectorDeclarationConfirmed: true,
        },
        {
          id: "insp-2",
          type: "structural_frame",
          title: "First Floor Slab Formwork & Structural Rebar Audit",
          relatedMilestoneId: "m-2",
          requestedBy: "Imara Construction Ltd",
          assignedInspectorName: "Eric Habimana",
          assignedInspectorRole: "engineer",
          scheduledDate: "2026-09-04",
          locationOnSite: "First floor slab deck",
          checklist: [
            { id: "chk-10", label: "Formwork props rigidity & bracing", passed: null },
            { id: "chk-11", label: "Beam rebar cage dimensions", passed: null },
            { id: "chk-12", label: "Electrical conduit routing embedded in slab", passed: null },
          ],
          evidencePhotoUrls: [],
          findings: "Scheduled for upcoming site audit.",
          reinspectionRequired: false,
          outcome: "scheduled",
          inspectorDeclarationConfirmed: false,
        },
      ],
      changeRequests: [],
      changeOrders: [],
      issues: [
        {
          id: "iss-1",
          issueReference: "RFI-01",
          type: "design_clarification",
          priority: "normal",
          title: "Window Frame Recess Detail Clarification",
          description: "Contractor needs structural drawing detail for double-glazed aluminum window frame recesses on 1st floor elevation.",
          raisedByName: "Jean Paul Ndayisaba",
          raisedByRole: "site_supervisor",
          assignedToName: "Aline Uwase",
          assignedToRole: "architect",
          relatedTaskId: "tsk-202",
          attachmentUrls: [],
          dueDate: "2026-09-02",
          status: "response_required",
          createdAt: "2026-08-27T14:00:00Z",
        },
      ],
      defects: [],
      handoverChecklist: {
        scopeCompleted: false,
        approvedChangesCompleted: false,
        requiredInspectionsPassed: false,
        openDefectsAddressed: false,
        siteCleaned: false,
        wasteRemoved: false,
        utilitiesTested: false,
        customerWalkthroughCompleted: false,
        documentsUploaded: false,
        warrantiesProvided: false,
        maintenanceInfoProvided: false,
      },
      handoverStatus: "not_started",
      warranties: [],
      warrantyIssues: [],
      documents: [
        {
          id: "doc-bp-1",
          name: "Approved_Building_Permit_KGL_2026.pdf",
          category: "approvals_permits",
          accessLabel: "customer_and_team",
          fileType: "pdf",
          sizeBytes: 2450000,
          uploadedByName: "Jane Doe",
          uploadedByRole: "customer",
          uploadedAt: "2026-05-16T09:00:00Z",
          version: "1.0",
        },
        {
          id: "doc-spec-1",
          name: "Architectural_Structural_Drawings_v2.pdf",
          category: "baseline_design",
          accessLabel: "customer_and_team",
          fileType: "pdf",
          sizeBytes: 8120000,
          uploadedByName: "Aline Uwase",
          uploadedByRole: "architect",
          uploadedAt: "2026-05-20T11:30:00Z",
          version: "2.0",
        },
      ],
      activity: [
        {
          id: "act-1",
          executionId: "exec-build-kigali",
          timestamp: "2026-08-28T18:00:00Z",
          actorName: "Imara Construction Ltd",
          actorRole: "contractor",
          type: "progress_report_submitted",
          summary: "Submitted Weekly Progress Report for Aug 21 - Aug 28.",
          relatedTab: "progress",
        },
        {
          id: "act-2",
          executionId: "exec-build-kigali",
          timestamp: "2026-08-28T17:30:00Z",
          actorName: "Jean Paul Ndayisaba",
          actorRole: "site_supervisor",
          type: "site_diary_submitted",
          summary: "Submitted daily site diary entry for Aug 28.",
          relatedTab: "site-diary",
        },
        {
          id: "act-3",
          executionId: "exec-build-kigali",
          timestamp: "2026-08-25T10:00:00Z",
          actorName: "Imara Construction Ltd",
          actorRole: "contractor",
          type: "substitution_requested",
          summary: "Raised material substitution request for Ruliba Clay Bricks.",
          relatedTab: "materials",
        },
      ],
      createdAt: "2026-05-25T10:00:00Z",
      updatedAt: "2026-08-28T18:00:00Z",
    },

    {
      id: "exec-renovate-gacuriro",
      name: "Gacuriro Family Home Refresh",
      sourceType: "renovate",
      sourceProjectId: "renovate-p1",
      sourceQuotationId: "quote-imara-renovate",
      customerName: "Jane Doe",
      customerId: "demo-user",
      customerEmail: "buyer@huzaestate.com",
      customerPhone: "+250 788 123 456",
      contractorName: "Imara Construction Ltd",
      contractorId: "imara-user",
      contractorEmail: "contractor@huzaestate.com",
      contractorPhone: "+250 788 999 888",
      location: "Gacuriro, Kigali",
      designVersionName: "Modern Nordic Renovation Concept",
      approvedScopeSummary: "Kitchen remodeling, bath plumbing upgrade, electrical rewire & interior painting.",
      contractValue: 28200000, // 28.2M RWF (26.5M initial + 1.7M approved change order)
      originalContractValue: 26500000,
      currency: "RWF",
      startDate: "2026-07-15",
      targetCompletionDate: "2026-09-30",
      status: "active",
      overallProgressPercent: 55,
      latestProgressImageUrl: "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?q=80&w=800&auto=format&fit=crop",
      nextRequiredAction: "Verify corrected electrical junction box defect in guest bedroom.",
      customerSetupConfirmed: true,
      contractorSetupConfirmed: true,
      leadProfessionalSetupConfirmed: true,
      communication: {
        primaryChannel: "In-app Chat & Bi-weekly Walkthrough",
        progressReportFrequency: "weekly",
        siteMeetingFrequency: "biweekly",
        emergencyContacts: "Contractor: +250 788 999 888",
        changeApprovalContacts: "Jane Doe",
        inspectionContacts: "Eric Habimana",
      },
      team: [
        {
          id: "tm-r1",
          userId: "demo-user",
          name: "Jane Doe",
          role: "customer",
          email: "buyer@huzaestate.com",
          phone: "+250 788 123 456",
          permissions: ["view", "approve_changes", "accept_handover"],
          startDate: "2026-07-15",
          contactPreferences: "Email",
          isEmergencyContact: true,
          confirmed: true,
        },
        {
          id: "tm-r2",
          userId: "imara-user",
          name: "Imara Construction Ltd",
          role: "contractor",
          email: "contractor@huzaestate.com",
          phone: "+250 788 999 888",
          company: "Imara Construction Ltd",
          permissions: ["update_schedule", "site_diary"],
          startDate: "2026-07-15",
          contactPreferences: "Phone",
          isEmergencyContact: true,
          confirmed: true,
        },
        {
          id: "tm-r3",
          userId: "keza-user",
          name: "Keza Studio",
          role: "architect",
          email: "interior@huzaestate.com",
          phone: "+250 788 333 444",
          company: "Keza Interior Design",
          permissions: ["review_substitutions", "observations"],
          startDate: "2026-07-15",
          contactPreferences: "Email",
          isEmergencyContact: false,
          confirmed: true,
        },
        {
          id: "tm-r4",
          userId: "eric-user",
          name: "Eric Habimana",
          role: "engineer",
          email: "structural@huzaestate.com",
          phone: "+250 788 444 555",
          permissions: ["inspections"],
          startDate: "2026-07-15",
          contactPreferences: "Phone",
          isEmergencyContact: true,
          confirmed: true,
        },
      ],
      approvals: [
        {
          id: "app-r1",
          name: "Homeowner Association (HOA) Renovation Approval",
          category: "hoa",
          status: "approved",
          approvalDate: "2026-07-10",
          supportingDocIds: [],
        },
      ],
      workPackages: [
        { id: "wp-r1", name: "Demolition & Prep", phase: "Demolition", description: "Removing old tiles and cabinetry.", leadRole: "contractor", taskIds: ["tsk-r1"], progressPercent: 100 },
        { id: "wp-r2", name: "Plumbing & Electrical Rewiring", phase: "Plumbing and electrical", description: "Installing PPR pipes, new distribution board and conduit.", leadRole: "contractor", taskIds: ["tsk-r2", "tsk-r3"], progressPercent: 75 },
        { id: "wp-r3", name: "Tiling & Wall Finishes", phase: "Finishes", description: "Porcelain floor tiling and moisture-resistant painting.", leadRole: "contractor", taskIds: ["tsk-r4"], progressPercent: 20 },
      ],
      tasks: [
        { id: "tsk-r1", workPackageId: "wp-r1", phase: "Demolition", title: "Old Kitchen Tile & Cabinet Removal", description: "Stripping existing tiles and safely removing fixtures.", plannedStart: "2026-07-16", plannedFinish: "2026-07-22", actualStart: "2026-07-16", actualFinish: "2026-07-21", assigneeName: "Imara Construction Ltd", assigneeRole: "contractor", progressPercent: 100, status: "completed", priority: "normal", dependencies: [] },
        { id: "tsk-r2", workPackageId: "wp-r2", phase: "Plumbing and electrical", title: "Kitchen & Bath Plumbing Rough-in", description: "New hot/cold PPR lines and drain waste pipes.", plannedStart: "2026-07-23", plannedFinish: "2026-08-10", actualStart: "2026-07-23", actualFinish: "2026-08-09", assigneeName: "Imara Construction Ltd", assigneeRole: "contractor", progressPercent: 100, status: "completed", priority: "high", dependencies: ["tsk-r1"] },
        { id: "tsk-r3", workPackageId: "wp-r2", phase: "Plumbing and electrical", title: "Main DB Board & Electrical Conduit Routing", description: "Rewiring circuits for modern kitchen appliances.", plannedStart: "2026-08-11", plannedFinish: "2026-08-25", actualStart: "2026-08-11", assigneeName: "Imara Construction Ltd", assigneeRole: "contractor", progressPercent: 85, status: "delayed", priority: "high", delayReason: "Awaiting replacement circuit breaker components from supplier.", dependencies: ["tsk-r1"] },
        { id: "tsk-r4", workPackageId: "wp-r3", phase: "Finishes", title: "Porcelain Floor & Wall Tiling", description: "Laying 60x60 cm non-slip porcelain tiles in kitchen and bathroom.", plannedStart: "2026-08-26", plannedFinish: "2026-09-12", assigneeName: "Imara Construction Ltd", assigneeRole: "contractor", progressPercent: 20, status: "in_progress", priority: "normal", dependencies: ["tsk-r3"] },
      ],
      milestones: [
        {
          id: "mr-1",
          title: "Milestone 1: Demolition & Rough-in Utilities",
          description: "Demolition completed, wall channels cut, water lines pressure-tested.",
          relatedTaskIds: ["tsk-r1", "tsk-r2"],
          plannedDate: "2026-08-10",
          actualCompletionDate: "2026-08-09",
          completionCriteria: ["Plumbing pressure test certificate", "Electrical conduit inspection"],
          requiredEvidence: ["Pressure test photo"],
          responsibleParty: "Imara Construction Ltd",
          contractValueAllocation: 8500000,
          status: "accepted",
          customerAcceptedAt: "2026-08-12",
          paymentEligibility: "eligible",
        },
        {
          id: "mr-2",
          title: "Milestone 2: Tiling, Ceiling & Electrical Final Fix",
          description: "Tiling complete, ceiling skimmed, light fixtures and sockets installed.",
          relatedTaskIds: ["tsk-r3", "tsk-r4"],
          plannedDate: "2026-09-15",
          completionCriteria: ["Tile alignment audit", "Electrical isolation test"],
          requiredEvidence: ["Completed tiling photo gallery"],
          responsibleParty: "Imara Construction Ltd",
          contractValueAllocation: 11000000,
          status: "in_progress",
          paymentEligibility: "eligibility_pending",
        },
      ],
      siteDiary: [
        {
          id: "sdr-1",
          date: "2026-08-29",
          workPackageId: "wp-r3",
          workCompleted: "Laid 25 sqm of porcelain kitchen floor tiles.",
          workInProgress: "Grouting floor tiles and waterproofing shower recess.",
          labourCount: 5,
          contractorTeams: ["Tile Master Team (3)", "Plumbing Assistant (2)"],
          equipmentOnSite: ["1x Wet Tile Cutter", "Laser Level"],
          materialsUsed: ["8 Boxes 60x60 porcelain tiles", "3 Bags Tile Adhesive S1"],
          deliveriesReceived: [],
          siteConditions: "Clean workspace, dust extractors running.",
          weatherSummary: "Partly cloudy, 25°C",
          visitors: [],
          inspectionsHeld: [],
          delaysEncountered: "Circuit breaker shipment delayed by 2 days.",
          incidents: "None",
          safetyObservations: "Dust masks worn during tile cutting.",
          photoUrls: ["https://images.unsplash.com/photo-1584622650111-993a426fbf0a?q=80&w=800&auto=format&fit=crop"],
          videoUrls: [],
          notes: "Tiling alignment verified with laser level.",
          submittedBy: "Imara Construction Ltd",
          submittedByRole: "contractor",
          submittedAt: "2026-08-29T16:45:00Z",
          status: "locked",
          amendments: [],
          comments: [],
        },
      ],
      progressReports: [
        {
          id: "pr-r1",
          reportType: "weekly_report",
          periodStart: "2026-08-22",
          periodEnd: "2026-08-29",
          plannedProgressPercent: 60,
          actualProgressPercent: 55,
          completedWorkSummary: "Completed plumbing pressure testing and kitchen floor tiling prep.",
          currentWorkSummary: "Floor tiling in progress.",
          upcomingWorkSummary: "Bathroom wall tiling and kitchen cabinet installation.",
          delaysAndBlockers: "Circuit breaker component delivery delayed 2 days.",
          risksAndMitigations: "Mitigated by advancing floor tiling ahead of electrical final fix.",
          decisionsRequired: "Select countertop quartz color swatch.",
          evidencePhotoUrls: ["https://images.unsplash.com/photo-1584622650111-993a426fbf0a?q=80&w=800&auto=format&fit=crop"],
          updatedCompletionForecast: "Est Oct 2, 2026 (2-day variance)",
          submittedBy: "Imara Construction Ltd",
          submittedAt: "2026-08-29T17:15:00Z",
        },
      ],
      materials: [
        {
          id: "mat-r1",
          materialName: "Italian Porcelain Floor Tiles 60x60 cm",
          specification: "Matte finish porcelain tile, anti-slip R10 rating",
          quantity: 120,
          unit: "sqm",
          sourceSupplier: "Kigali Home Finishes",
          requiredDate: "2026-08-20",
          actualDeliveryDate: "2026-08-22",
          status: "delivered",
          inspectionStatus: "passed",
          supportingDocIds: [],
        },
      ],
      substitutions: [],
      inspections: [
        {
          id: "insp-r1",
          type: "plumbing_rough_in",
          title: "Plumbing Rough-in & Pressure Test Verification",
          requestedBy: "Imara Construction Ltd",
          assignedInspectorName: "Eric Habimana",
          assignedInspectorRole: "engineer",
          scheduledDate: "2026-08-09",
          completedDate: "2026-08-09",
          locationOnSite: "Kitchen & Guest Bathroom water lines",
          checklist: [
            { id: "chkr-1", label: "PPR pipe joint heat welds inspected", passed: true },
            { id: "chkr-2", label: "Hydrostatic 10 bar pressure test held for 2 hours", passed: true },
          ],
          evidencePhotoUrls: [],
          findings: "Pressure test held at 10 bar without drop for 2 hours. Approved.",
          reinspectionRequired: false,
          outcome: "passed",
          inspectorDeclarationConfirmed: true,
        },
      ],
      changeRequests: [
        {
          id: "cr-r1",
          changeReference: "CO-R01",
          origin: "customer",
          title: "Add Kitchen Island Electrical Outlets & LED Strip Recesses",
          description: "Customer requested pop-up power outlets in island countertop and under-cabinet dimmable LED channels.",
          reason: "Enhance kitchen functionality and mood lighting as requested during client walkthrough.",
          requestedByName: "Jane Doe",
          requestedByRole: "customer",
          affectedDesignElement: "Kitchen Island & Upper Cabinetry",
          affectedRoomsOrPackages: ["wp-r2", "wp-r3"],
          costImpact: 1700000, // +1.7M RWF
          scheduleImpactDays: 2,
          scopeImpactSummary: "Additional 2 dedicated circuits, LED aluminum profiles, pop-up power tower.",
          supportingDocIds: [],
          professionalRecommendation: "Recommended by Keza Studio. Electrical load calculation verified.",
          professionalReviewerName: "Keza Studio (Architect)",
          customerDecisionNotes: "Approved by client on Aug 18.",
          status: "implemented",
          createdAt: "2026-08-15T11:00:00Z",
          approvedAt: "2026-08-18T14:30:00Z",
        },
      ],
      changeOrders: [
        {
          id: "co-r1",
          changeRequestId: "cr-r1",
          changeReference: "CO-R01",
          title: "Add Kitchen Island Outlets & Under-Cabinet LED Channels",
          costDelta: 1700000,
          scheduleDeltaDays: 2,
          approvedByCustomerName: "Jane Doe",
          approvedAt: "2026-08-18T14:30:00Z",
          baselineContractValueBefore: 26500000,
          baselineContractValueAfter: 28200000,
          revisedCompletionDate: "2026-10-02",
        },
      ],
      issues: [],
      defects: [
        {
          id: "def-r1",
          defectReference: "SNG-R01",
          roomLocation: "Guest Bedroom",
          category: "Electrical",
          description: "Junction box cover plate missing and wiring uninsulated.",
          severity: "moderate",
          photoUrls: ["https://images.unsplash.com/photo-1584622650111-993a426fbf0a?q=80&w=800&auto=format&fit=crop"],
          reportedByName: "Jane Doe",
          assignedContractorName: "Imara Construction Ltd",
          targetCorrectionDate: "2026-09-02",
          correctionEvidencePhotoUrls: [],
          status: "ready_for_verification",
          createdAt: "2026-08-26T15:00:00Z",
        },
      ],
      handoverChecklist: {
        scopeCompleted: false,
        approvedChangesCompleted: false,
        requiredInspectionsPassed: true,
        openDefectsAddressed: false,
        siteCleaned: false,
        wasteRemoved: false,
        utilitiesTested: true,
        customerWalkthroughCompleted: false,
        documentsUploaded: false,
        warrantiesProvided: false,
        maintenanceInfoProvided: false,
      },
      handoverStatus: "not_started",
      warranties: [],
      warrantyIssues: [],
      documents: [],
      activity: [
        {
          id: "act-r1",
          executionId: "exec-renovate-gacuriro",
          timestamp: "2026-08-18T14:30:00Z",
          actorName: "Jane Doe",
          actorRole: "customer",
          type: "change_order_approved",
          summary: "Approved Change Order CO-R01 (+1,700,000 RWF).",
          relatedTab: "changes",
        },
      ],
      createdAt: "2026-07-01T10:00:00Z",
      updatedAt: "2026-08-29T17:15:00Z",
    },

    {
      id: "exec-handover-kiyovu",
      name: "Kiyovu Apartment Kitchen",
      sourceType: "renovate",
      sourceProjectId: "renovate-p2",
      sourceQuotationId: "quote-imara-kiyovu",
      customerName: "Jane Doe",
      customerId: "demo-user",
      customerEmail: "buyer@huzaestate.com",
      customerPhone: "+250 788 123 456",
      contractorName: "Imara Construction Ltd",
      contractorId: "imara-user",
      contractorEmail: "contractor@huzaestate.com",
      contractorPhone: "+250 788 999 888",
      location: "Kiyovu, Kigali",
      designVersionName: "Minimalist Kitchen Remodel",
      approvedScopeSummary: "Custom oak cabinetry, quartz countertops, plumbing upgrades and appliance installation.",
      contractValue: 18500000,
      originalContractValue: 18500000,
      currency: "RWF",
      startDate: "2026-05-01",
      targetCompletionDate: "2026-08-25",
      actualCompletionDate: "2026-08-28",
      status: "snagging",
      overallProgressPercent: 96,
      latestProgressImageUrl: "https://images.unsplash.com/photo-1556911220-e15b29be8c8f?q=80&w=800&auto=format&fit=crop",
      nextRequiredAction: "Complete final customer walkthrough and verify 2 open snag items.",
      customerSetupConfirmed: true,
      contractorSetupConfirmed: true,
      leadProfessionalSetupConfirmed: true,
      communication: {
        primaryChannel: "In-app & Phone",
        progressReportFrequency: "weekly",
        siteMeetingFrequency: "weekly",
        emergencyContacts: "Contractor: +250 788 999 888",
        changeApprovalContacts: "Jane Doe",
        inspectionContacts: "Eric Habimana",
      },
      team: [
        {
          id: "tm-h1",
          userId: "demo-user",
          name: "Jane Doe",
          role: "customer",
          email: "buyer@huzaestate.com",
          phone: "+250 788 123 456",
          permissions: ["view", "handover"],
          startDate: "2026-05-01",
          contactPreferences: "Email",
          isEmergencyContact: true,
          confirmed: true,
        },
        {
          id: "tm-h2",
          userId: "imara-user",
          name: "Imara Construction Ltd",
          role: "contractor",
          email: "contractor@huzaestate.com",
          phone: "+250 788 999 888",
          permissions: ["handover_prep"],
          startDate: "2026-05-01",
          contactPreferences: "Phone",
          isEmergencyContact: true,
          confirmed: true,
        },
      ],
      approvals: [],
      workPackages: [
        { id: "wp-h1", name: "Cabinetry & Countertops", phase: "Fixtures and cabinetry", description: "Oak cabinets & quartz slab.", leadRole: "contractor", taskIds: ["tsk-h1"], progressPercent: 100 },
        { id: "wp-h2", name: "Final Fix & Appliances", phase: "Testing and inspection", description: "Appliance testing & snag list.", leadRole: "contractor", taskIds: ["tsk-h2"], progressPercent: 90 },
      ],
      tasks: [
        { id: "tsk-h1", workPackageId: "wp-h1", phase: "Fixtures and cabinetry", title: "Custom Oak Cabinetry & Quartz Countertop Installation", description: "Fitting pre-fabricated oak units and sealing quartz slab joints.", plannedStart: "2026-06-15", plannedFinish: "2026-07-20", actualStart: "2026-06-15", actualFinish: "2026-07-18", assigneeName: "Imara Construction Ltd", assigneeRole: "contractor", progressPercent: 100, status: "completed", priority: "high", dependencies: [] },
        { id: "tsk-h2", workPackageId: "wp-h2", phase: "Testing and inspection", title: "Appliance Testing & Pre-Handover Cleaning", description: "Testing built-in oven, dishwasher, faucet pressure, and deep cleaning.", plannedStart: "2026-07-21", plannedFinish: "2026-08-25", actualStart: "2026-07-21", assigneeName: "Imara Construction Ltd", assigneeRole: "contractor", progressPercent: 90, status: "in_progress", priority: "normal", dependencies: ["tsk-h1"] },
      ],
      milestones: [
        {
          id: "mh-1",
          title: "Milestone 1: Cabinetry & Slab Installation",
          description: "All kitchen cabinets installed and quartz countertop leveled.",
          relatedTaskIds: ["tsk-h1"],
          plannedDate: "2026-07-20",
          actualCompletionDate: "2026-07-18",
          completionCriteria: ["Cabinet alignment check", "Seam seal check"],
          requiredEvidence: ["Cabinet gallery"],
          responsibleParty: "Imara Construction Ltd",
          contractValueAllocation: 12000000,
          status: "accepted",
          customerAcceptedAt: "2026-07-20",
          paymentEligibility: "eligible",
        },
        {
          id: "mh-2",
          title: "Milestone 2: Final Handover & Testing",
          description: "All appliances commissioned, snag items rectified, warranties handed over.",
          relatedTaskIds: ["tsk-h2"],
          plannedDate: "2026-08-25",
          completionCriteria: ["Final inspection passed", "Zero major defects", "Warranties signed"],
          requiredEvidence: ["Handover report"],
          responsibleParty: "Imara Construction Ltd",
          contractValueAllocation: 6500000,
          status: "submitted_for_review",
          paymentEligibility: "eligibility_pending",
        },
      ],
      siteDiary: [],
      progressReports: [],
      materials: [],
      substitutions: [],
      inspections: [
        {
          id: "insp-h1",
          type: "final_inspection",
          title: "Final Substantial Completion & Handover Inspection",
          relatedMilestoneId: "mh-2",
          requestedBy: "Imara Construction Ltd",
          assignedInspectorName: "Eric Habimana",
          assignedInspectorRole: "engineer",
          scheduledDate: "2026-08-26",
          completedDate: "2026-08-26",
          locationOnSite: "Kiyovu Apartment Kitchen",
          checklist: [
            { id: "chkh-1", label: "Cabinet door alignment and soft-close mechanism", passed: true },
            { id: "chkh-2", label: "Sink drain leak check and faucet pressure", passed: true },
            { id: "chkh-3", label: "Induction cooktop and oven electrical circuit test", passed: true },
            { id: "chkh-4", label: "Under-cabinet lighting LED function", passed: false, notes: "One corner LED strip flickers slightly." },
          ],
          evidencePhotoUrls: ["https://images.unsplash.com/photo-1556911220-e15b29be8c8f?q=80&w=800&auto=format&fit=crop"],
          findings: "Substantial completion achieved. Passed with minor cosmetic snagging items.",
          reinspectionRequired: false,
          outcome: "passed_with_observations",
          inspectorDeclarationConfirmed: true,
        },
      ],
      changeRequests: [],
      changeOrders: [],
      issues: [],
      defects: [
        {
          id: "def-h1",
          defectReference: "SNG-K01",
          roomLocation: "Kitchen Under-Cabinet Lighting",
          category: "Electrical / Lighting",
          description: "Left corner LED strip flickers when dimmed.",
          severity: "minor_cosmetic",
          photoUrls: ["https://images.unsplash.com/photo-1556911220-e15b29be8c8f?q=80&w=800&auto=format&fit=crop"],
          reportedByName: "Jane Doe",
          assignedContractorName: "Imara Construction Ltd",
          targetCorrectionDate: "2026-09-03",
          status: "open",
          createdAt: "2026-08-26T16:00:00Z",
        },
        {
          id: "def-h2",
          defectReference: "SNG-K02",
          roomLocation: "Pantry Cabinet",
          category: "Joinery",
          description: "Pantry door handle screw slightly loose.",
          severity: "minor_cosmetic",
          photoUrls: [],
          reportedByName: "Jane Doe",
          assignedContractorName: "Imara Construction Ltd",
          targetCorrectionDate: "2026-09-02",
          status: "correction_in_progress",
          createdAt: "2026-08-26T16:15:00Z",
        },
      ],
      handoverChecklist: {
        scopeCompleted: true,
        approvedChangesCompleted: true,
        requiredInspectionsPassed: true,
        openDefectsAddressed: false, // 2 open snag items
        siteCleaned: true,
        wasteRemoved: true,
        utilitiesTested: true,
        customerWalkthroughCompleted: true,
        documentsUploaded: true,
        warrantiesProvided: true,
        maintenanceInfoProvided: true,
      },
      handoverStatus: "snagging_in_progress",
      warranties: [
        {
          id: "war-1",
          title: "Oak Cabinetry Structural Warranty",
          itemOrSystem: "Kitchen Cabinetry & Joinery",
          supplierOrManufacturer: "Kigali Woodworks",
          warrantyPeriodMonths: 36,
          startDate: "2026-08-28",
          expiryDate: "2029-08-28",
          termsSummary: "Covers timber warping, hinge failure and finish delamination under normal residential use.",
          documentIds: ["doc-war-pdf"],
        },
        {
          id: "war-2",
          title: "Quartz Countertop Stain & Heat Warranty",
          itemOrSystem: "Engineered Quartz Slab",
          supplierOrManufacturer: "Silestone East Africa",
          warrantyPeriodMonths: 120,
          startDate: "2026-08-28",
          expiryDate: "2036-08-28",
          termsSummary: "10-year manufacturer warranty against permanent staining and structural cracking.",
          documentIds: [],
        },
      ],
      warrantyIssues: [],
      documents: [
        {
          id: "doc-war-pdf",
          name: "Kigali_Woodworks_Cabinetry_Warranty.pdf",
          category: "warranties",
          accessLabel: "customer_and_team",
          fileType: "pdf",
          sizeBytes: 1200000,
          uploadedByName: "Imara Construction Ltd",
          uploadedByRole: "contractor",
          uploadedAt: "2026-08-27T10:00:00Z",
          version: "1.0",
        },
      ],
      activity: [
        {
          id: "act-h1",
          executionId: "exec-handover-kiyovu",
          timestamp: "2026-08-26T16:00:00Z",
          actorName: "Jane Doe",
          actorRole: "customer",
          type: "defect_reported",
          summary: "Reported 2 minor snagging items during final walkthrough.",
          relatedTab: "handover",
        },
      ],
      createdAt: "2026-04-20T10:00:00Z",
      updatedAt: "2026-08-28T14:00:00Z",
    },
  ];
}
