import Link from "next/link";

export function PageFrame({ title, description, action, children }: { title: string; description: string; action?: React.ReactNode; children: React.ReactNode }) {
  return <div className="mx-auto max-w-[1440px] px-4 py-8 sm:px-8"><div className="mb-7 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><h2 className="text-2xl font-black text-slate-900 sm:text-3xl">{title}</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-500">{description}</p></div>{action}</div>{children}</div>;
}

export function Card({ children, className = "" }: { children: React.ReactNode; className?: string }) { return <section className={`rounded-2xl border border-slate-200 bg-white p-5 shadow-sm ${className}`}>{children}</section>; }
export function StatusPill({ status }: { status: string }) { const normalized = status.toLowerCase(); const style = normalized.includes("completed") || normalized.includes("approved") || normalized.includes("published") || normalized.includes("resolved") || normalized.includes("active") || normalized.includes("accepted") ? "bg-[#2ec440]/10 text-[#219b31]" : normalized.includes("declined") || normalized.includes("rejected") || normalized.includes("suspended") || normalized.includes("critical") || normalized.includes("closed") || normalized.includes("urgent") ? "bg-red-50 text-red-700" : normalized.includes("clarification") || normalized.includes("change") || normalized.includes("review") || normalized.includes("pending") || normalized.includes("awaiting") || normalized.includes("escalated") ? "bg-amber-50 text-amber-700" : "bg-blue-50 text-blue-700"; return <span className={`inline-flex rounded-full px-2.5 py-1 text-xs font-bold ${style}`}>{status.replace(/_/g, " ")}</span>; }
export const PrimaryButton = ({ children, ...props }: React.ButtonHTMLAttributes<HTMLButtonElement>) => <button {...props} className={`min-h-11 rounded-xl bg-slate-900 px-4 py-2.5 text-sm font-bold text-white shadow-lg transition-colors hover:bg-[#2ec440] disabled:cursor-not-allowed disabled:opacity-50 ${props.className ?? ""}`}>{children}</button>;
export const SecondaryButton = ({ children, ...props }: React.ButtonHTMLAttributes<HTMLButtonElement>) => <button {...props} className={`min-h-11 rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-sm font-bold text-slate-700 transition-colors hover:border-[#2ec440] hover:text-[#219b31] disabled:opacity-50 ${props.className ?? ""}`}>{children}</button>;
export const DestructiveButton = ({ children, ...props }: React.ButtonHTMLAttributes<HTMLButtonElement>) => <button {...props} className={`min-h-11 rounded-xl bg-red-600 px-4 py-2.5 text-sm font-bold text-white shadow-lg transition-colors hover:bg-red-700 disabled:cursor-not-allowed disabled:opacity-50 ${props.className ?? ""}`}>{children}</button>;
export const PrimaryLink = ({ href, children, className = "" }: { href: string; children: React.ReactNode; className?: string }) => <Link href={href} className={`inline-flex min-h-11 items-center justify-center rounded-xl bg-slate-900 px-4 py-2.5 text-sm font-bold text-white shadow-lg transition-colors hover:bg-[#2ec440] ${className}`}>{children}</Link>;
export function EmptyState({ title, description, action }: { title: string; description: string; action?: React.ReactNode }) { return <Card className="py-14 text-center"><div className="mx-auto mb-4 flex h-12 w-12 items-center justify-center rounded-full bg-slate-100 text-slate-500"><svg className="h-6 w-6" fill="none" stroke="currentColor" viewBox="0 0 24 24" aria-hidden="true"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M9 12h6m-3-3v6m9-3a9 9 0 11-18 0 9 9 0 0118 0z" /></svg></div><h3 className="font-black text-slate-900">{title}</h3><p className="mx-auto mt-2 max-w-md text-sm text-slate-500">{description}</p>{action && <div className="mt-5">{action}</div>}</Card>; }
export function AccessDeniedNote({ children }: { children: React.ReactNode }) { return <Card className="border-red-100 bg-red-50/60 py-10 text-center"><h3 className="font-black text-red-700">Access denied</h3><p className="mx-auto mt-2 max-w-md text-sm text-red-700/80">{children}</p></Card>; }
export function RequirePermission({ granted, children }: { granted: boolean; children: React.ReactNode }) { if (!granted) return <AccessDeniedNote>You do not have permission to view this section. Contact a Super Administrator if you believe this is a mistake.</AccessDeniedNote>; return <>{children}</>; }
export const fieldClass = "w-full rounded-xl border border-slate-200 bg-white px-3.5 py-3 text-sm text-slate-900 outline-none transition focus:border-[#2ec440] focus:ring-2 focus:ring-[#2ec440]/15";
export function formatDate(value: string) { return new Intl.DateTimeFormat("en-RW", { dateStyle: "medium" }).format(new Date(value)); }
export function formatDateTime(value: string) { return new Intl.DateTimeFormat("en-RW", { dateStyle: "medium", timeStyle: "short" }).format(new Date(value)); }
export function formatMoney(value: number, currency = "RWF") { return new Intl.NumberFormat("en-RW", { style: "currency", currency, maximumFractionDigits: 0 }).format(value); }
