import type { ProfessionalProfile } from "./types";

const now = new Date().toISOString();
const service = (id: string, name: string, description: string) => ({ id, name, description, deliveryTime: "2–4 business days", deliveryMode: "both" as const, priceAfterAssessment: true, requiredInformation: "Project brief, selected concept and included documents" });

export const DEMO_PROFILES: ProfessionalProfile[] = [
  { id: "pro-1", accountId: "aline-user", kind: "individual_professional", status: "approved", displayName: "Aline Uwase", legalName: "Aline Uwase", email: "architect@huzaestate.com", phone: "+250 788 100 101", country: "Rwanda", city: "Kigali", address: "Gasabo, Kigali", biography: "Residential architect focused on practical, climate-aware family homes.", yearsExperience: 11, languages: ["Kinyarwanda", "English", "French"], primarySpecialisation: "Architect", secondarySpecialisations: ["Accessibility Specialist"], registrationNumber: "DEMO-RA-1042", licensingBody: "Prototype registration record", services: [service("svc-arch", "Architectural review", "Review spatial planning, circulation and brief alignment."), service("svc-concept", "Concept review", "Review conceptual design directions and documentation gaps."), service("svc-permit", "Permit-readiness review", "Identify information commonly needed before a formal permit process.")], serviceAreas: ["Gasabo", "Kicukiro", "Nyarugenge"], travelRadiusKm: 35, remoteAvailable: true, onsiteAvailable: true, travelFeeApproach: "Quoted after location assessment", workingDays: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"], workingHours: "08:30–17:30", consultationDuration: 45, minimumNoticeHours: 24, acceptingNewWork: true, maximumActiveRequests: 6, responseTime: "Within 1 business day", pricingApproaches: ["Fixed review fee", "Hourly"], availability: "available", verificationLabel: "Demo verified", demoVerified: true, portfolio: [
    { id: "port-1a", title: "Nyarutarama Family Residence", projectType: "New build — house", location: "Nyarutarama, Kigali", year: "2024", description: "Full architectural design for a 4-bedroom family home, from concept through permit-ready drawings — climate-aware orientation and natural ventilation throughout.", services: "Architectural design, permit drawings", imageNames: [], testimonial: "Aline understood exactly what our family needed and kept the design grounded in our budget.", published: true },
    { id: "port-1b", title: "Kacyiru Mixed-Use Concept", projectType: "New build — mixed-use", location: "Kacyiru, Kigali", year: "2023", description: "Concept and schematic design for a ground-floor retail, upper-floor residential building.", services: "Concept design, circulation planning", imageNames: [], published: true },
  ], lastUpdatedAt: now },
  { id: "pro-structural", accountId: "eric-user", kind: "individual_professional", status: "approved", displayName: "Eric Habimana", legalName: "Eric Habimana", email: "eric@example.demo", phone: "+250 788 100 102", country: "Rwanda", city: "Kigali", address: "Kigali", biography: "Structural engineer supporting residential reviews and site inspections.", yearsExperience: 9, languages: ["Kinyarwanda", "English"], primarySpecialisation: "Structural Engineer", secondarySpecialisations: [], services: [service("svc-struct", "Structural review", "Review available structural information and assumptions."), service("svc-site", "Site inspection", "Document observations during a scheduled site visit."), service("svc-floor", "Additional-floor assessment", "Assess information required for a proposed additional floor.")], serviceAreas: ["Kigali"], travelRadiusKm: 50, remoteAvailable: true, onsiteAvailable: true, travelFeeApproach: "Distance based", workingDays: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"], workingHours: "08:00–17:00", consultationDuration: 60, minimumNoticeHours: 48, acceptingNewWork: true, maximumActiveRequests: 5, responseTime: "Within 2 business days", pricingApproaches: ["Quotation after assessment"], availability: "limited", verificationLabel: "Demo verified", demoVerified: true, portfolio: [
    { id: "port-2a", title: "Kimihurura Villa Structural Review", projectType: "Structural assessment", location: "Kimihurura, Kigali", year: "2024", description: "Full structural review and site inspection for a two-storey villa addition, including foundation load assessment.", services: "Structural review, site inspection", imageNames: [], testimonial: "Thorough and clear — flagged issues we would have missed before construction started.", published: true },
    { id: "port-2b", title: "Remera Additional-Floor Assessment", projectType: "Structural assessment", location: "Remera, Kigali", year: "2023", description: "Assessed existing structure's capacity to support a proposed third floor, with reinforcement recommendations.", services: "Additional-floor assessment", imageNames: [], published: true },
  ], lastUpdatedAt: now },
  { id: "pro-3", accountId: "diane-user", kind: "individual_professional", status: "approved", displayName: "Diane Mukamana", legalName: "Diane Mukamana", email: "surveyor@huzaestate.com", phone: "+250 788 100 103", country: "Rwanda", city: "Kigali", address: "Kigali", biography: "Quantity surveyor specialising in residential cost and scope reviews.", yearsExperience: 8, languages: ["Kinyarwanda", "English", "French"], primarySpecialisation: "Quantity Surveyor", secondarySpecialisations: [], services: [service("svc-cost", "Cost estimation", "Prepare a professional estimate separate from AI indicative figures."), service("svc-budget", "Budget review", "Review cost assumptions, allowances and contingency."), service("svc-scope", "Scope review", "Identify inclusions, exclusions and measurement gaps.")], serviceAreas: ["Kigali"], travelRadiusKm: 40, remoteAvailable: true, onsiteAvailable: true, travelFeeApproach: "Agreed before visit", workingDays: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"], workingHours: "09:00–17:00", consultationDuration: 45, minimumNoticeHours: 24, acceptingNewWork: true, maximumActiveRequests: 7, responseTime: "Within 1 business day", pricingApproaches: ["Fixed review fee", "Per square metre"], availability: "available", verificationLabel: "Demo verified", demoVerified: true, portfolio: [
    { id: "port-3a", title: "Gisozi Renovation Cost Review", projectType: "Cost estimation", location: "Gisozi, Kigali", year: "2024", description: "Independent cost estimate and budget review for a full home renovation, separate from the contractor's own figures.", services: "Cost estimation, budget review", imageNames: [], testimonial: "Gave us confidence our contractor's quote was fair before we signed anything.", published: true },
    { id: "port-3b", title: "Kabeza New-Build Scope Review", projectType: "Scope review", location: "Kabeza, Kigali", year: "2023", description: "Reviewed scope documentation for a new-build project, identifying measurement gaps and missing allowances.", services: "Scope review", imageNames: [], published: true },
  ], lastUpdatedAt: now },
  { id: "pro-interior", accountId: "keza-user", kind: "professional_firm", status: "approved", displayName: "Keza Studio", legalName: "Keza Studio Ltd", businessName: "Keza Studio", email: "keza@example.demo", phone: "+250 788 100 104", country: "Rwanda", city: "Kigali", address: "Kigali", biography: "Interior design studio for thoughtful renovation planning and material selection.", yearsExperience: 7, languages: ["Kinyarwanda", "English"], primarySpecialisation: "Interior Designer", secondarySpecialisations: [], services: [service("svc-int", "Interior design review", "Review function, materials, lighting and style consistency."), service("svc-mat", "Material selection", "Develop material recommendations."), service("svc-plan", "Renovation planning", "Review renovation areas and sequencing.")], serviceAreas: ["Kigali"], travelRadiusKm: 30, remoteAvailable: true, onsiteAvailable: true, travelFeeApproach: "Included within Kigali", workingDays: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"], workingHours: "09:00–17:30", consultationDuration: 60, minimumNoticeHours: 24, acceptingNewWork: true, maximumActiveRequests: 5, responseTime: "Within 1 business day", pricingApproaches: ["Fixed review fee"], availability: "available", verificationLabel: "Demo verified", demoVerified: true, portfolio: [
    { id: "port-4a", title: "Kiyovu Apartment Interior Refresh", projectType: "Interior design", location: "Kiyovu, Kigali", year: "2024", description: "Full interior design for a 2-bedroom apartment renovation — material palette, lighting plan and furniture layout.", services: "Interior design, material selection", imageNames: [], testimonial: "Keza Studio transformed our apartment on a modest budget without it feeling cheap.", published: true },
    { id: "port-4b", title: "Nyamirambo Villa Material Selection", projectType: "Interior design", location: "Nyamirambo, Kigali", year: "2023", description: "Material and finish selection for a whole-villa renovation, coordinated with the contractor's schedule.", services: "Material selection, renovation planning", imageNames: [], published: true },
  ], lastUpdatedAt: now },
  { id: "contractor-imara", accountId: "imara-user", kind: "contractor_company", status: "approved", displayName: "Imara Construction Ltd", legalName: "Imara Construction Ltd", businessName: "Imara Construction Ltd", email: "contractor@huzaestate.com", phone: "+250 788 100 105", country: "Rwanda", city: "Kigali", address: "Kicukiro, Kigali", biography: "General contractor preparing transparent residential renovation quotations.", yearsExperience: 13, languages: ["Kinyarwanda", "English"], primarySpecialisation: "General Contractor", secondarySpecialisations: ["Painting Contractor", "Flooring Contractor"], services: [service("svc-res", "Residential renovation", "Residential renovation delivery."), service("svc-full", "Full property renovation", "Multi-area renovation delivery."), service("svc-quote", "Contractor quotation", "Itemised contractor quotation after scope assessment.")], serviceAreas: ["Kigali", "Bugesera"], travelRadiusKm: 60, remoteAvailable: false, onsiteAvailable: true, travelFeeApproach: "Mobilisation quoted by project", workingDays: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"], workingHours: "07:30–17:30", consultationDuration: 60, minimumNoticeHours: 48, acceptingNewWork: true, maximumActiveRequests: 8, responseTime: "Within 2 business days", pricingApproaches: ["Quotation after assessment"], availability: "available", verificationLabel: "Demo verified", demoVerified: true, portfolio: [
    { id: "port-5a", title: "Kicukiro Full Home Renovation", projectType: "Full property renovation", location: "Kicukiro, Kigali", year: "2024", description: "Complete renovation of a 4-bedroom home — roofing, electrical, plumbing and finishes — delivered on the agreed schedule.", services: "Full property renovation", imageNames: [], testimonial: "Imara delivered on time and on budget — no surprises along the way.", published: true },
    { id: "port-5b", title: "Bugesera Residential Extension", projectType: "Residential renovation", location: "Bugesera", year: "2023", description: "Two-room extension and roof replacement for a family home outside Kigali.", services: "Residential renovation", imageNames: [], published: true },
  ], lastUpdatedAt: now },
];
