"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import { useState } from "react";
import ConfirmModal from "@/components/shared/ConfirmModal";
import { useAuth } from "@/lib/auth-context";
import { useProfessionalProfile } from "@/lib/professional/hooks";
import { ProfessionalService } from "@/lib/professional/service";
import type { ProfessionalKind, ProfessionalProfile } from "@/lib/professional/types";
import { useToast } from "@/lib/toast-context";
import { Card, PageFrame, PrimaryButton, SecondaryButton, StatusPill, fieldClass } from "./ui";

const steps = ["Profession", "Information", "Qualifications", "Services", "Service area", "Availability", "Pricing", "Portfolio", "Review"];
const specialisations = ["Architect", "Structural Engineer", "Electrical Engineer", "Plumbing and Mechanical Engineer", "Quantity Surveyor", "Interior Designer", "Sustainability Specialist", "Accessibility Specialist", "Building Inspector", "General Contractor", "Roofing Contractor", "Electrical Contractor", "Plumbing Contractor", "Kitchen Specialist", "Bathroom Specialist", "Painting Contractor", "Flooring Contractor", "Landscaping Contractor", "Other Specialist Contractor"];

export default function ApplicationWizard() {
  const { account } = useAuth(); const existing = useProfessionalProfile(account?.id); const router = useRouter(); const { showToast } = useToast();
  const [step, setStep] = useState(0); const [submitOpen, setSubmitOpen] = useState(false);
  const [values, setValues] = useState<Partial<ProfessionalProfile>>(() => existing ?? { kind: "individual_professional", status: "draft", displayName: account?.name ?? "", legalName: account?.name ?? "", email: account?.email ?? "", phone: "", country: "Rwanda", city: "Kigali", address: "", biography: "", yearsExperience: 0, languages: ["Kinyarwanda", "English"], primarySpecialisation: "Architect", secondarySpecialisations: [], services: [], serviceAreas: ["Kigali"], travelRadiusKm: 30, remoteAvailable: true, onsiteAvailable: true, travelFeeApproach: "", workingDays: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"], workingHours: "08:00–17:00", consultationDuration: 45, minimumNoticeHours: 24, acceptingNewWork: true, maximumActiveRequests: 5, responseTime: "Within 2 business days", pricingApproaches: ["Quotation after assessment"], availability: "available", portfolio: [] });
  const set = <K extends keyof ProfessionalProfile>(key: K, value: ProfessionalProfile[K]) => setValues((current) => ({ ...current, [key]: value }));
  const save = () => { if (!account) return; ProfessionalService.saveApplication(account.id, values); showToast("Application draft saved."); };
  const canContinue = values.primarySpecialisation && values.displayName && values.email;
  if (!account) return null;

  return <PageFrame title="Professional application" description="Complete the nine steps below. Your application remains a draft until you confirm submission.">
    <div className="mb-6 overflow-x-auto"><ol className="flex min-w-max gap-2" aria-label="Application progress">{steps.map((name, index) => <li key={name}><button onClick={() => setStep(index)} aria-current={index === step ? "step" : undefined} className={`rounded-full px-3 py-2 text-xs font-bold ${index === step ? "bg-slate-900 text-white" : index < step ? "bg-[#2ec440]/10 text-[#219b31]" : "bg-white text-slate-500"}`}>{index + 1}. {name}</button></li>)}</ol></div>
    <Card className="mx-auto max-w-4xl"><h3 className="text-xl font-black text-slate-900">{step + 1}. {steps[step]}</h3><p className="mt-1 text-sm text-slate-500">Fields marked by context are stored locally for this frontend prototype.</p>
      <div className="mt-6">
        {step === 0 && <div className="grid gap-4 sm:grid-cols-2"><label className="text-sm font-bold text-slate-700">Profile type<select className={`${fieldClass} mt-2`} value={values.kind} onChange={(e) => set("kind", e.target.value as ProfessionalKind)}><option value="individual_professional">Individual professional</option><option value="professional_firm">Professional firm</option><option value="contractor_company">Contractor company</option><option value="individual_specialist_contractor">Individual specialist contractor</option></select></label><label className="text-sm font-bold text-slate-700">Primary specialisation<select className={`${fieldClass} mt-2`} value={values.primarySpecialisation} onChange={(e) => set("primarySpecialisation", e.target.value)}>{specialisations.map((item) => <option key={item}>{item}</option>)}</select></label><fieldset className="sm:col-span-2"><legend className="text-sm font-bold text-slate-700">Secondary specialisations</legend><div className="mt-3 grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{specialisations.filter((item) => item !== values.primarySpecialisation).map((item) => <label key={item} className="flex items-center gap-2 rounded-xl border border-slate-200 p-3 text-sm"><input type="checkbox" className="accent-[#2ec440]" checked={values.secondarySpecialisations?.includes(item)} onChange={(e) => set("secondarySpecialisations", e.target.checked ? [...(values.secondarySpecialisations ?? []), item] : (values.secondarySpecialisations ?? []).filter((value) => value !== item))} />{item}</label>)}</div></fieldset></div>}
        {step === 1 && <div className="grid gap-4 sm:grid-cols-2">{[["legalName", "Full legal name"], ["displayName", "Public display name"], ["businessName", "Business name"], ["email", "Email"], ["phone", "Phone number"], ["country", "Country"], ["city", "City or district"], ["address", "Business address"], ["website", "Website"]].map(([key, name]) => <label key={key} className="text-sm font-bold text-slate-700">{name}<input className={`${fieldClass} mt-2`} value={String(values[key as keyof ProfessionalProfile] ?? "")} onChange={(e) => setValues((current) => ({ ...current, [key]: e.target.value }))} /></label>)}<label className="text-sm font-bold text-slate-700">Years of experience<input type="number" min="0" className={`${fieldClass} mt-2`} value={values.yearsExperience} onChange={(e) => set("yearsExperience", Number(e.target.value))} /></label><label className="text-sm font-bold text-slate-700 sm:col-span-2">Short professional biography<textarea className={`${fieldClass} mt-2 min-h-28`} value={values.biography} onChange={(e) => set("biography", e.target.value)} /></label><fieldset className="sm:col-span-2"><legend className="text-sm font-bold text-slate-700">Languages</legend><div className="mt-2 flex flex-wrap gap-3">{["Kinyarwanda", "English", "French", "Other"].map((language) => <label key={language} className="flex items-center gap-2 text-sm"><input type="checkbox" className="accent-[#2ec440]" checked={values.languages?.includes(language)} onChange={(e) => set("languages", e.target.checked ? [...(values.languages ?? []), language] : (values.languages ?? []).filter((item) => item !== language))} />{language}</label>)}</div></fieldset></div>}
        {step === 2 && <div className="grid gap-4 sm:grid-cols-2"><label className="text-sm font-bold text-slate-700">Professional registration number<input className={`${fieldClass} mt-2`} value={values.registrationNumber ?? ""} onChange={(e) => set("registrationNumber", e.target.value)} /></label><label className="text-sm font-bold text-slate-700">Licensing or membership body<input className={`${fieldClass} mt-2`} value={values.licensingBody ?? ""} onChange={(e) => set("licensingBody", e.target.value)} /></label><label className="text-sm font-bold text-slate-700">Licence expiry<input type="date" className={`${fieldClass} mt-2`} value={values.licenceExpiry ?? ""} onChange={(e) => set("licenceExpiry", e.target.value)} /></label><label className="text-sm font-bold text-slate-700 sm:col-span-2">Verification documents<input type="file" multiple accept=".pdf,.jpg,.jpeg,.png,.webp" className={`${fieldClass} mt-2`} onChange={(e) => { const profile = ProfessionalService.saveApplication(account.id, values).profiles.find((item) => item.accountId === account.id); if (!profile) return; Array.from(e.target.files ?? []).forEach((file) => ProfessionalService.addFile(profile.id, { name: file.name, mimeType: file.type, size: file.size, category: "verification", access: "verification_only", submitted: false })); showToast("Document metadata stored locally. No automatic verification occurred.", "info"); }} /><span className="mt-2 block text-xs font-normal text-slate-500">PDF, JPG, JPEG, PNG or WEBP. Files are not automatically verified.</span></label></div>}
        {step === 3 && <div><p className="text-sm text-slate-600">Add services you provide. Each can be refined later in your profile.</p><div className="mt-4 grid gap-3 sm:grid-cols-2">{["Concept review", "Architectural review", "Structural review", "Quantity surveying", "Cost estimation", "Electrical review", "Plumbing review", "Interior design", "Site inspection", "Permit-readiness review", "Contractor quotation", "Renovation execution", "Specialist installation"].map((name) => { const checked = values.services?.some((service) => service.name === name); return <label key={name} className="rounded-xl border border-slate-200 p-4"><span className="flex items-center gap-2 text-sm font-bold"><input type="checkbox" className="accent-[#2ec440]" checked={checked} onChange={(e) => set("services", e.target.checked ? [...(values.services ?? []), { id: `service-${name.toLowerCase().replace(/\W/g, "-")}`, name, description: `${name} service`, deliveryTime: "2–5 business days", deliveryMode: "both", priceAfterAssessment: true, requiredInformation: "Project brief and shared documents" }] : (values.services ?? []).filter((service) => service.name !== name))} />{name}</span><span className="mt-2 block text-xs font-normal text-slate-500">Remote or onsite · Price after assessment</span></label>; })}</div></div>}
        {step === 4 && <div className="grid gap-4 sm:grid-cols-2"><label className="text-sm font-bold text-slate-700">Cities or districts served<input className={`${fieldClass} mt-2`} value={values.serviceAreas?.join(", ")} onChange={(e) => set("serviceAreas", e.target.value.split(",").map((item) => item.trim()).filter(Boolean))} /></label><label className="text-sm font-bold text-slate-700">Travel radius (km)<input type="number" className={`${fieldClass} mt-2`} value={values.travelRadiusKm} onChange={(e) => set("travelRadiusKm", Number(e.target.value))} /></label><label className="flex items-center gap-2 text-sm font-bold"><input type="checkbox" checked={values.remoteAvailable} onChange={(e) => set("remoteAvailable", e.target.checked)} className="accent-[#2ec440]" />Remote service available</label><label className="flex items-center gap-2 text-sm font-bold"><input type="checkbox" checked={values.onsiteAvailable} onChange={(e) => set("onsiteAvailable", e.target.checked)} className="accent-[#2ec440]" />Onsite service available</label><label className="text-sm font-bold text-slate-700 sm:col-span-2">Travel fee approach<textarea className={`${fieldClass} mt-2`} value={values.travelFeeApproach} onChange={(e) => set("travelFeeApproach", e.target.value)} /></label></div>}
        {step === 5 && <div className="grid gap-4 sm:grid-cols-2"><label className="text-sm font-bold text-slate-700">Working hours<input className={`${fieldClass} mt-2`} value={values.workingHours} onChange={(e) => set("workingHours", e.target.value)} /></label><label className="text-sm font-bold text-slate-700">Consultation duration (minutes)<input type="number" className={`${fieldClass} mt-2`} value={values.consultationDuration} onChange={(e) => set("consultationDuration", Number(e.target.value))} /></label><label className="text-sm font-bold text-slate-700">Minimum notice (hours)<input type="number" className={`${fieldClass} mt-2`} value={values.minimumNoticeHours} onChange={(e) => set("minimumNoticeHours", Number(e.target.value))} /></label><label className="text-sm font-bold text-slate-700">Maximum active requests<input type="number" className={`${fieldClass} mt-2`} value={values.maximumActiveRequests} onChange={(e) => set("maximumActiveRequests", Number(e.target.value))} /></label><label className="text-sm font-bold text-slate-700">Expected response time<input className={`${fieldClass} mt-2`} value={values.responseTime} onChange={(e) => set("responseTime", e.target.value)} /></label><label className="flex items-center gap-2 text-sm font-bold"><input type="checkbox" checked={values.acceptingNewWork} onChange={(e) => set("acceptingNewWork", e.target.checked)} className="accent-[#2ec440]" />Currently accepting new work</label></div>}
        {step === 6 && <fieldset><legend className="text-sm font-bold text-slate-700">Pricing approach</legend><div className="mt-3 grid gap-3 sm:grid-cols-2">{["Fixed review fee", "Hourly", "Per square metre", "Percentage of project value", "Quotation after assessment", "Free initial consultation"].map((item) => <label key={item} className="flex items-center gap-2 rounded-xl border border-slate-200 p-3 text-sm"><input type="checkbox" className="accent-[#2ec440]" checked={values.pricingApproaches?.includes(item)} onChange={(e) => set("pricingApproaches", e.target.checked ? [...(values.pricingApproaches ?? []), item] : (values.pricingApproaches ?? []).filter((value) => value !== item))} />{item}</label>)}</div><p className="mt-4 text-xs text-slate-500">No payment is collected during this application.</p></fieldset>}
        {step === 7 && <div><p className="text-sm text-slate-600">Portfolio items remain unpublished unless you confirm publication from your approved profile.</p><div className="mt-4 grid gap-4 sm:grid-cols-2">{["Project title", "Project type", "Location", "Year", "Services provided"].map((name) => <label key={name} className="text-sm font-bold text-slate-700">{name}<input className={`${fieldClass} mt-2`} /></label>)}<label className="text-sm font-bold text-slate-700 sm:col-span-2">Description<textarea className={`${fieldClass} mt-2 min-h-24`} /></label><label className="text-sm font-bold text-slate-700 sm:col-span-2">Images<input type="file" accept=".jpg,.jpeg,.png,.webp" multiple className={`${fieldClass} mt-2`} /></label></div></div>}
        {step === 8 && <div className="space-y-4"><div className="grid gap-4 sm:grid-cols-2"><Summary name="Profile" value={`${values.displayName} · ${values.primarySpecialisation}`} /><Summary name="Location" value={`${values.city}, ${values.country}`} /><Summary name="Services" value={`${values.services?.length ?? 0} selected`} /><Summary name="Service area" value={values.serviceAreas?.join(", ") || "Not provided"} /><Summary name="Availability" value={values.acceptingNewWork ? values.responseTime ?? "Accepting work" : "Not accepting work"} /><Summary name="Pricing" value={values.pricingApproaches?.join(", ") || "Not provided"} /></div><div className="rounded-xl bg-amber-50 p-4 text-sm leading-6 text-amber-900">Submitting sets the application to <strong>Submitted</strong>. It does not approve the profile or grant a real verification badge.</div><label className="flex items-start gap-3 text-sm text-slate-700"><input required type="checkbox" className="mt-1 accent-[#2ec440]" />I confirm the information is accurate, documents are valid, HuzaEstate may review it, and a verification badge is not guaranteed.</label></div>}
      </div>
      <div className="mt-8 flex flex-col-reverse gap-3 border-t border-slate-100 pt-5 sm:flex-row sm:items-center sm:justify-between"><SecondaryButton onClick={save}>Save draft</SecondaryButton><div className="flex gap-3"><SecondaryButton disabled={step === 0} onClick={() => setStep((current) => current - 1)}>Back</SecondaryButton>{step < steps.length - 1 ? <PrimaryButton disabled={!canContinue} onClick={() => { save(); setStep((current) => current + 1); }}>Continue</PrimaryButton> : <PrimaryButton onClick={() => { save(); setSubmitOpen(true); }}>Review and submit</PrimaryButton>}</div></div>
    </Card>
    <ConfirmModal open={submitOpen} onClose={() => setSubmitOpen(false)} onConfirm={() => { ProfessionalService.saveApplication(account.id, values); ProfessionalService.submitApplication(account.id); showToast("Application submitted for review."); router.push("/professional/application/status"); }} title="Submit professional application?" description="Your application will be locked as a submitted prototype record and must be reviewed separately. It will not approve itself." confirmLabel="Submit application" />
  </PageFrame>;
}

function Summary({ name, value }: { name: string; value: string }) { return <div className="rounded-xl bg-slate-50 p-4"><p className="text-xs font-bold uppercase text-slate-400">{name}</p><p className="mt-2 text-sm font-bold text-slate-800">{value}</p></div>; }

export function ApplicationStatusPage() { const { account } = useAuth(); const profile = useProfessionalProfile(account?.id); if (!profile) return <PageFrame title="Application status" description="No professional application is associated with this account."><Card className="max-w-xl"><p className="text-sm text-slate-600">Start an application to create a professional or contractor profile.</p><Link href="/professional/application" className="mt-5 inline-flex rounded-xl bg-slate-900 px-4 py-3 text-sm font-bold text-white hover:bg-[#2ec440]">Start application</Link></Card></PageFrame>; return <PageFrame title="Application status" description="Track review progress and respond if HuzaEstate requests more information."><Card className="max-w-2xl"><div className="flex items-start justify-between gap-4"><div><h3 className="text-xl font-black text-slate-900">{profile.displayName}</h3><p className="mt-1 text-sm text-slate-500">{profile.primarySpecialisation} · submitted {profile.applicationSubmittedAt ? new Date(profile.applicationSubmittedAt).toLocaleDateString() : "as a draft"}</p></div><StatusPill status={profile.status} /></div><div className="mt-6 rounded-xl bg-slate-50 p-4 text-sm leading-6 text-slate-600">{profile.status === "approved" ? "Your professional workspace is available." : profile.status === "more_information_required" ? "Additional information is required before review can continue." : profile.status === "rejected" ? "This application was not approved. The record remains available for reference." : profile.status === "suspended" ? "Professional access is suspended pending review." : profile.status === "draft" ? "Your application has not been submitted." : "Your application is awaiting a separate prototype review. It cannot approve itself."}</div><div className="mt-5 flex flex-wrap gap-3">{profile.status === "approved" && <Link href="/professional" className="rounded-xl bg-slate-900 px-4 py-3 text-sm font-bold text-white hover:bg-[#2ec440]">Open workspace</Link>}{["draft", "more_information_required"].includes(profile.status) && <Link href="/professional/application" className="rounded-xl border border-slate-200 px-4 py-3 text-sm font-bold text-slate-700">Continue application</Link>}<Link href="/dashboard" className="rounded-xl border border-slate-200 px-4 py-3 text-sm font-bold text-slate-700">Customer Dashboard</Link></div></Card></PageFrame>; }
