"use client";

import Link from "next/link";
import { useState } from "react";
import { useAuth } from "@/lib/auth-context";
import { BuildProjectService } from "@/lib/build/projectService";
import { RenovationProjectService } from "@/lib/renovate/projectService";
import { useProfessionalProfile, useProfessionalState } from "@/lib/professional/hooks";
import { ProfessionalService } from "@/lib/professional/service";
import { Card, EmptyState, PageFrame, StatusPill } from "./ui";

const tabs = ["Overview", "Brief", "Shared Design", "Documents", "Review or Quotation", "Messages", "Activity"];
export default function ProjectDetail({ projectId }: { projectId: string }) { const { account } = useAuth(); const profile = useProfessionalProfile(account?.id); const state = useProfessionalState(); const [tab, setTab] = useState("Overview"); if (!profile) return null; const requests = ProfessionalService.getRequests(profile.id).filter((request) => request.projectId === projectId); if (!requests.length) return <PageFrame title="Project unavailable" description="This project was not shared with your professional profile."><EmptyState title="Access denied" description="Customer-only project information remains private." /></PageFrame>; const request = requests[0]; const build = request.projectType === "Build" ? BuildProjectService.getById(projectId) : undefined; const renovate = request.projectType === "Renovate" ? RenovationProjectService.getById(projectId) : undefined; const messages = state.messages.filter((item) => requests.some((r) => r.id === item.requestId)); return <PageFrame title={request.projectName} description="Restricted professional project workspace"><div className="mb-6 flex gap-1 overflow-x-auto border-b border-slate-200">{tabs.map((item) => <button key={item} onClick={() => setTab(item)} className={`whitespace-nowrap border-b-2 px-3 py-3 text-sm font-bold ${tab === item ? "border-[#2ec440] text-[#219b31]" : "border-transparent text-slate-500"}`}>{item}</button>)}</div>
  {tab === "Overview" && <div className="grid gap-5 md:grid-cols-2"><Card><h3 className="font-black text-slate-900">Project summary</h3><dl className="mt-4 space-y-3 text-sm"><Row name="Customer" value={request.customerName} /><Row name="Assigned service" value={request.requestType} /><Row name="Shared version" value={request.sharedVersion} /><Row name="Current deadline" value={new Date(request.desiredResponseDate).toLocaleDateString()} /><Row name="Request status" value={request.status} /></dl></Card><Card><h3 className="font-black text-slate-900">Next professional action</h3><div className="mt-4"><StatusPill status={request.status} /></div><p className="mt-4 text-sm text-slate-600">{request.professionalActionRequired ? "Open the request and respond to the customer." : "Continue the assigned review or quotation workflow."}</p><Link className="mt-5 inline-block font-bold text-[#219b31]" href={`/professional/requests/${request.id}`}>Open request</Link></Card></div>}
  {tab === "Brief" && <Card><h3 className="font-black text-slate-900">Shared brief</h3><p className="mt-4 whitespace-pre-line text-sm leading-7 text-slate-600">{build ? `${build.description}\n${build.brief.household.floors} floors · ${build.brief.household.rooms.map((room) => `${room.quantity} ${room.label}`).join(", ")}\nBudget: ${build.brief.budget.targetBudget?.toLocaleString() ?? "Not set"} ${build.brief.budget.currency}` : `${renovate?.brief.summary}\nAreas: ${renovate?.assessment.areas.map((area) => area.customLabel || area.areaKey.replace(/_/g, " ")).join(", ")}\nTimeline: ${renovate?.assessment.budgetTimeline.requiredCompletionDate || "Not set"}`}</p></Card>}
  {tab === "Shared Design" && <Card><div className="rounded-xl border border-dashed border-slate-300 bg-slate-50 p-10 text-center"><p className="font-black text-slate-900">Conceptual design viewer</p><p className="mt-2 text-sm text-slate-500">AI-generated content is conceptual and is not approved for construction.</p><p className="mt-4 text-sm font-bold text-[#219b31]">{request.sharedVersion}</p></div></Card>}
  {tab === "Documents" && <Card><h3 className="font-black text-slate-900">Included documents</h3><ul className="mt-4 divide-y divide-slate-100">{request.documentIds.map((doc) => <li key={doc} className="py-3 text-sm font-semibold text-slate-700">Shared document {doc.slice(0, 12)} <span className="text-xs font-normal text-slate-400">· Read only</span></li>)}</ul></Card>}
  {tab === "Review or Quotation" && <Card><h3 className="font-black text-slate-900">Assigned work</h3><div className="mt-4 space-y-3">{requests.map((item) => <Link key={`${item.id}-${item.source}`} href={item.quotationId ? `/professional/quotations/${item.quotationId}` : `/professional/reviews/${item.id}`} className="flex items-center justify-between rounded-xl border border-slate-200 p-4 hover:border-[#2ec440]"><span className="font-bold text-slate-800">{item.requestType}</span><StatusPill status={item.status} /></Link>)}</div></Card>}
  {tab === "Messages" && <Card><h3 className="font-black text-slate-900">Project messages</h3><div className="mt-4 space-y-3">{messages.map((message) => <div key={message.id} className="rounded-xl bg-slate-50 p-3 text-sm text-slate-700">{message.text}</div>)}{!messages.length && <p className="text-sm text-slate-500">No project messages yet.</p>}</div></Card>}
  {tab === "Activity" && <Card><h3 className="font-black text-slate-900">Shared-project activity</h3><p className="mt-4 text-sm text-slate-500">Only activity linked to your assigned work is shown.</p>{state.activity.filter((item) => requests.some((r) => item.href?.includes(r.id))).map((item) => <p key={item.id} className="mt-3 border-l-2 border-[#2ec440] pl-3 text-sm text-slate-700">{item.description}</p>)}</Card>}
  </PageFrame>; }
function Row({ name, value }: { name: string; value: string }) { return <div className="flex justify-between gap-4"><dt className="text-slate-400">{name}</dt><dd className="text-right font-bold text-slate-800">{value.replace(/_/g, " ")}</dd></div>; }
