"use client";

import { useMemo, useState } from "react";
import ConfirmModal from "@/components/shared/ConfirmModal";
import { useAuth } from "@/lib/auth-context";
import { RenovationProjectService } from "@/lib/renovate/projectService";
import { useProfessionalProfile, useProfessionalState } from "@/lib/professional/hooks";
import { ProfessionalService, quotationTotal } from "@/lib/professional/service";
import type { QuotationDraft, QuoteLine } from "@/lib/professional/types";
import { useToast } from "@/lib/toast-context";
import { Card, EmptyState, PageFrame, PrimaryButton, SecondaryButton, StatusPill, fieldClass, formatMoney } from "./ui";

const dateIn = (days: number) => new Date(Date.now() + days * 86400000).toISOString().slice(0, 10);
const blankLine = (): QuoteLine => ({ id: `line_${Date.now()}_${Math.random().toString(16).slice(2)}`, area: "General", category: "Materials and labour", description: "", quantity: 1, unit: "item", materialUnitCost: 0, labourUnitCost: 0, otherCost: 0, taxPct: 0, optional: false, notes: "" });

export default function QuotationWorkspace({ quotationId }: { quotationId: string }) {
  const { account } = useAuth(); const profile = useProfessionalProfile(account?.id); const state = useProfessionalState(); const { showToast } = useToast(); const [submitOpen, setSubmitOpen] = useState(false); const [preview, setPreview] = useState(false);
  const request = profile ? ProfessionalService.getRequests(profile.id).find((item) => item.quotationId === quotationId) : undefined; const project = request ? RenovationProjectService.getById(request.projectId) : undefined; const quotation = project?.quotations.find((item) => item.id === quotationId);
  const stored = state.quotationDrafts.find((item) => item.quotationId === quotationId); const initial = useMemo<QuotationDraft>(() => stored ?? { quotationId, lines: quotation?.materials.map((item, index) => ({ ...blankLine(), id: `material_${index}`, category: "Materials", description: item.label, materialUnitCost: item.amount })) ?? [blankLine()], issueDate: dateIn(0), validUntil: dateIn(30), proposedStartDate: dateIn(45), durationWeeks: quotation?.proposedDurationWeeks ?? 8, currency: "RWF", discount: 0, contingencyPct: 5, taxPct: 0, inclusions: quotation?.includedScope ?? [], exclusions: quotation?.excludedScope ?? [], customerMaterials: [], contractorMaterials: ["Materials listed in line items"], assumptions: quotation?.assumptions ?? [], warranty: quotation?.warrantyInfo ?? "12-month workmanship warranty", paymentSchedule: quotation?.paymentSchedule.split(",") ?? ["30% deposit", "40% at midpoint", "30% on handover"], terms: "Quotation is subject to confirmed measurements and agreed scope.", versions: [] }, [quotationId, stored, quotation]);
  const [draft, setDraft] = useState(initial); if (!profile || !request || !project || !quotation) return <PageFrame title="Quotation unavailable" description="This quotation does not exist or is not assigned to your contractor profile."><EmptyState title="Access denied" description="No unrelated customer or quotation information has been revealed." /></PageFrame>;
  const totals = quotationTotal(draft); const updateLine = (lineId: string, update: Partial<QuoteLine>) => setDraft((current) => ({ ...current, lines: current.lines.map((line) => line.id === lineId ? { ...line, ...update } : line) })); const save = () => { ProfessionalService.saveQuotationDraft(profile.id, draft); showToast("Quotation draft saved."); };
  return <PageFrame title={`Quotation for ${request.projectName}`} description={`${quotation.contractor.companyName} · ${request.customerName} · no payment is processed`} action={<StatusPill status={quotation.status} />}>
    <div className="mb-6 flex flex-wrap gap-3"><PrimaryButton onClick={save}>Save Draft</PrimaryButton><SecondaryButton onClick={() => setPreview((value) => !value)}>{preview ? "Edit Quotation" : "Preview Quotation"}</SecondaryButton><PrimaryButton onClick={() => setSubmitOpen(true)}>Submit Quotation</PrimaryButton></div>
    {preview ? <QuotationPreview draft={draft} total={totals.total} customer={request.customerName} project={request.projectName} contractor={quotation.contractor.companyName} /> : <div className="space-y-6"><Card><h3 className="text-lg font-black text-slate-900">Quotation information</h3><div className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><DateField label="Issue date" value={draft.issueDate} onChange={(value) => setDraft({ ...draft, issueDate: value })} /><DateField label="Valid until" value={draft.validUntil} onChange={(value) => setDraft({ ...draft, validUntil: value })} /><DateField label="Proposed start" value={draft.proposedStartDate} onChange={(value) => setDraft({ ...draft, proposedStartDate: value })} /><NumberField label="Duration (weeks)" value={draft.durationWeeks} onChange={(value) => setDraft({ ...draft, durationWeeks: value })} /></div></Card>
      <Card className="overflow-hidden p-0"><div className="flex flex-col gap-3 border-b border-slate-200 p-5 sm:flex-row sm:items-center sm:justify-between"><div><h3 className="text-lg font-black text-slate-900">Itemised line items</h3><p className="mt-1 text-sm text-slate-500">Edit on mobile using the stacked cards below.</p></div><SecondaryButton onClick={() => setDraft({ ...draft, lines: [...draft.lines, blankLine()] })}>Add Line</SecondaryButton></div><div className="grid gap-4 p-4">{draft.lines.map((line, index) => <div key={line.id} className="rounded-xl border border-slate-200 p-4"><div className="mb-4 flex items-center justify-between"><h4 className="font-black text-slate-900">Line {index + 1}</h4><div className="flex gap-2"><button className="text-xs font-bold text-slate-500 hover:text-[#219b31]" onClick={() => setDraft({ ...draft, lines: [...draft.lines, { ...line, id: blankLine().id }] })}>Duplicate</button><button className="text-xs font-bold text-red-600" onClick={() => setDraft({ ...draft, lines: draft.lines.filter((item) => item.id !== line.id) })}>Remove</button></div></div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><TextField label="Room or area" value={line.area} onChange={(value) => updateLine(line.id, { area: value })} /><TextField label="Work category" value={line.category} onChange={(value) => updateLine(line.id, { category: value })} /><label className="text-sm font-bold text-slate-700 sm:col-span-2">Description<input required className={`${fieldClass} mt-1`} value={line.description} onChange={(e) => updateLine(line.id, { description: e.target.value })} /></label><NumberField label="Quantity" value={line.quantity} onChange={(value) => updateLine(line.id, { quantity: value })} /><TextField label="Unit" value={line.unit} onChange={(value) => updateLine(line.id, { unit: value })} /><NumberField label="Unit material cost" value={line.materialUnitCost} onChange={(value) => updateLine(line.id, { materialUnitCost: value })} /><NumberField label="Unit labour cost" value={line.labourUnitCost} onChange={(value) => updateLine(line.id, { labourUnitCost: value })} /><NumberField label="Other cost" value={line.otherCost} onChange={(value) => updateLine(line.id, { otherCost: value })} /><label className="flex items-center gap-2 self-end pb-3 text-sm font-bold text-slate-700"><input type="checkbox" className="accent-[#2ec440]" checked={line.optional} onChange={(e) => updateLine(line.id, { optional: e.target.checked })} />Optional item</label><div className="self-end pb-3 text-right"><p className="text-xs text-slate-400">Line total</p><p className="font-black text-slate-900">{formatMoney(line.quantity * (line.materialUnitCost + line.labourUnitCost) + line.otherCost)}</p></div></div></div>)}</div></Card>
      <div className="grid gap-6 xl:grid-cols-[1fr_.55fr]"><Card><h3 className="text-lg font-black text-slate-900">Scope, assumptions and terms</h3><div className="mt-5 grid gap-4 sm:grid-cols-2"><ListField label="Included work" values={draft.inclusions} onChange={(values) => setDraft({ ...draft, inclusions: values })} /><ListField label="Excluded work" values={draft.exclusions} onChange={(values) => setDraft({ ...draft, exclusions: values })} /><ListField label="Customer-provided materials" values={draft.customerMaterials} onChange={(values) => setDraft({ ...draft, customerMaterials: values })} /><ListField label="Contractor-provided materials" values={draft.contractorMaterials} onChange={(values) => setDraft({ ...draft, contractorMaterials: values })} /><ListField label="Assumptions" values={draft.assumptions} onChange={(values) => setDraft({ ...draft, assumptions: values })} /><ListField label="Payment schedule" values={draft.paymentSchedule} onChange={(values) => setDraft({ ...draft, paymentSchedule: values })} /><TextField label="Warranty" value={draft.warranty} onChange={(value) => setDraft({ ...draft, warranty: value })} /><TextField label="Change-request process and terms" value={draft.terms} onChange={(value) => setDraft({ ...draft, terms: value })} /></div></Card><Card><h3 className="text-lg font-black text-slate-900">Totals</h3><dl className="mt-4 space-y-3 text-sm"><Total name="Materials" value={totals.materials} /><Total name="Labour" value={totals.labour} /><Total name="Other costs" value={totals.other} /><Total name="Optional items (excluded)" value={totals.optional} /><div className="grid grid-cols-2 gap-3"><NumberField label="Discount" value={draft.discount} onChange={(value) => setDraft({ ...draft, discount: value })} /><NumberField label="Contingency %" value={draft.contingencyPct} onChange={(value) => setDraft({ ...draft, contingencyPct: value })} /><NumberField label="Tax %" value={draft.taxPct} onChange={(value) => setDraft({ ...draft, taxPct: value })} /></div><Total name="Tax" value={totals.tax} /><div className="border-t border-slate-200 pt-4"><Total name="Quotation total" value={totals.total} strong /></div></dl></Card></div>
      <Card><h3 className="text-lg font-black text-slate-900">Version history</h3><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[620px] text-left text-sm"><thead><tr className="border-b border-slate-200 text-xs uppercase text-slate-400"><th className="py-3">Version</th><th>Submission date</th><th>Total</th><th>Main changes</th><th>Validity</th><th>Status</th></tr></thead><tbody>{draft.versions.map((version) => <tr key={version.version} className="border-b border-slate-100"><td className="py-3 font-bold">v{version.version}</td><td>{new Date(version.submittedAt).toLocaleDateString()}</td><td>{formatMoney(version.total)}</td><td>{version.changes}</td><td>{version.validUntil}</td><td>{version.status}</td></tr>)}</tbody></table>{!draft.versions.length && <p className="py-5 text-sm text-slate-500">No submitted versions yet.</p>}</div></Card></div>}
    <ConfirmModal open={submitOpen} onClose={() => setSubmitOpen(false)} onConfirm={() => { save(); ProfessionalService.submitQuotation(profile.id, quotationId, totals.total, draft.versions.length ? "Revised itemised quotation" : "Initial itemised quotation"); setSubmitOpen(false); showToast("Quotation submitted and locked as a new version."); }} title="Submit quotation version?" description={<span>Submit {formatMoney(totals.total)} to {request.customerName}, valid until {draft.validUntil}. This version will be locked. No payment is processed.</span>} confirmLabel={draft.versions.length ? "Submit Revised Quotation" : "Submit Quotation"}><label className="mt-4 flex items-start gap-2 text-sm text-slate-600"><input required type="checkbox" className="mt-1 accent-[#2ec440]" />I confirm the included scope, exclusions, payment schedule and attachments are ready for the customer.</label></ConfirmModal>
  </PageFrame>;
}

function QuotationPreview({ draft, total, customer, project, contractor }: { draft: QuotationDraft; total: number; customer: string; project: string; contractor: string }) { return <Card className="mx-auto max-w-4xl"><div className="flex flex-col justify-between gap-4 border-b border-slate-200 pb-5 sm:flex-row"><div><p className="text-xs font-black uppercase text-[#219b31]">Customer quotation preview</p><h3 className="mt-2 text-2xl font-black text-slate-900">{project}</h3><p className="mt-1 text-sm text-slate-500">Prepared by {contractor} for {customer}</p></div><div className="sm:text-right"><p className="text-xs text-slate-400">Total</p><p className="text-2xl font-black text-slate-900">{formatMoney(total, draft.currency)}</p><p className="mt-1 text-xs text-slate-500">Valid until {draft.validUntil}</p></div></div><table className="mt-5 w-full text-left text-sm"><thead><tr className="border-b border-slate-200"><th className="py-3">Description</th><th>Area</th><th className="text-right">Amount</th></tr></thead><tbody>{draft.lines.map((line) => <tr key={line.id} className="border-b border-slate-100"><td className="py-3">{line.description || "Untitled line"}{line.optional && <span className="ml-2 text-xs text-slate-400">Optional</span>}</td><td>{line.area}</td><td className="text-right">{formatMoney(line.quantity * (line.materialUnitCost + line.labourUnitCost) + line.otherCost)}</td></tr>)}</tbody></table><div className="mt-6 grid gap-5 sm:grid-cols-2"><div><h4 className="font-black text-slate-900">Included work</h4><ul className="mt-2 list-disc pl-5 text-sm text-slate-600">{draft.inclusions.map((item) => <li key={item}>{item}</li>)}</ul></div><div><h4 className="font-black text-slate-900">Excluded work</h4><ul className="mt-2 list-disc pl-5 text-sm text-slate-600">{draft.exclusions.map((item) => <li key={item}>{item}</li>)}</ul></div></div><p className="mt-6 rounded-xl bg-amber-50 p-4 text-sm text-amber-900">Prototype quotation only. No payment, escrow, contract or construction execution tracking is created.</p></Card>; }
function TextField({ label, value, onChange }: { label: string; value: string; onChange: (value: string) => void }) { return <label className="text-sm font-bold text-slate-700">{label}<input className={`${fieldClass} mt-1`} value={value} onChange={(e) => onChange(e.target.value)} /></label>; }
function DateField({ label, value, onChange }: { label: string; value: string; onChange: (value: string) => void }) { return <label className="text-sm font-bold text-slate-700">{label}<input type="date" className={`${fieldClass} mt-1`} value={value} onChange={(e) => onChange(e.target.value)} /></label>; }
function NumberField({ label, value, onChange }: { label: string; value: number; onChange: (value: number) => void }) { return <label className="text-sm font-bold text-slate-700">{label}<input type="number" min="0" className={`${fieldClass} mt-1`} value={value} onChange={(e) => onChange(Number(e.target.value))} /></label>; }
function ListField({ label, values, onChange }: { label: string; values: string[]; onChange: (values: string[]) => void }) { return <label className="text-sm font-bold text-slate-700">{label}<textarea className={`${fieldClass} mt-1 min-h-24`} value={values.join("\n")} onChange={(e) => onChange(e.target.value.split("\n").filter(Boolean))} /><span className="mt-1 block text-xs font-normal text-slate-400">One item per line</span></label>; }
function Total({ name, value, strong = false }: { name: string; value: number; strong?: boolean }) { return <div className={`flex justify-between gap-3 ${strong ? "text-lg font-black" : ""}`}><dt className="text-slate-500">{name}</dt><dd className="font-bold text-slate-900">{formatMoney(value)}</dd></div>; }
