"use client";
/* eslint-disable react-hooks/purity -- date defaults are local prototype form suggestions; mutations remain event-driven */

import Link from "next/link";
import { useState } from "react";
import Dialog from "@/components/Dialog";
import { useAuth } from "@/lib/auth-context";
import { BuildProjectService } from "@/lib/build/projectService";
import { RenovationProjectService } from "@/lib/renovate/projectService";
import { useProfessionalProfile, useProfessionalState } from "@/lib/professional/hooks";
import { ProfessionalService } from "@/lib/professional/service";
import { useToast } from "@/lib/toast-context";
import { Card, EmptyState, PageFrame, PrimaryButton, SecondaryButton, StatusPill, fieldClass, formatDate } from "./ui";

type Modal = "accept" | "clarify" | "decline" | "consult" | null;

export default function RequestDetail({ requestId }: { requestId: string }) {
  const { account } = useAuth(); const profile = useProfessionalProfile(account?.id); useProfessionalState(); const { showToast } = useToast(); const [modal, setModal] = useState<Modal>(null);
  const [question, setQuestion] = useState(""); const [category, setCategory] = useState("Missing document"); const [reason, setReason] = useState("Outside expertise"); const [note, setNote] = useState("");
  if (!profile) return null; const request = ProfessionalService.getRequest(profile.id, requestId);
  if (!request) return <PageFrame title="Request unavailable" description="This request does not exist or is not assigned to your professional profile."><EmptyState title="Access denied" description="No private project information has been revealed. Return to your request inbox." action={<Link href="/professional/requests" className="font-bold text-[#219b31]">Back to requests</Link>} /></PageFrame>;
  const build = request.source === "build_review" ? BuildProjectService.getById(request.projectId) : undefined; const renovate = request.source !== "build_review" ? RenovationProjectService.getById(request.projectId) : undefined;
  const docs = build ? build.documents.filter((doc) => request.documentIds.includes(doc.id)) : renovate?.documents.filter((doc) => request.documentIds.includes(doc.id)) ?? [];
  const active = !["declined", "cancelled", "completed"].includes(request.status);
  const act = (status: string, message: string) => { ProfessionalService.setRequestStatus(profile.id, request.id, status, message); setModal(null); showToast(message); };
  return <PageFrame title={request.projectName} description={`${request.requestType} · request ${request.id}`} action={<StatusPill status={request.status} />}>
    <div className="grid gap-6 xl:grid-cols-[1.2fr_.8fr]"><div className="space-y-6"><Card><h3 className="text-lg font-black text-slate-900">Request summary</h3><dl className="mt-5 grid grid-cols-2 gap-4 text-sm sm:grid-cols-3">{[["Customer", request.customerName], ["Project type", request.projectType], ["Location", request.location], ["Submitted", formatDate(request.submittedAt)], ["Response requested", formatDate(request.desiredResponseDate)], ["Shared version", request.sharedVersion]].map(([name, value]) => <div key={name}><dt className="text-xs font-bold uppercase text-slate-400">{name}</dt><dd className="mt-1 font-semibold text-slate-800">{value}</dd></div>)}</dl><div className="mt-5 rounded-xl bg-slate-50 p-4"><p className="text-xs font-bold uppercase text-slate-400">Customer questions</p><p className="mt-2 text-sm leading-6 text-slate-700">{request.questions || "No additional questions were provided."}</p></div></Card>
      <Card><div className="flex items-center justify-between"><h3 className="text-lg font-black text-slate-900">Shared project brief</h3>{request.safetyFlag && <span className="text-xs font-bold text-red-700">Safety information included</span>}</div>{build && <dl className="mt-5 grid gap-4 text-sm sm:grid-cols-2"><Brief name="Plot" value={`${build.brief.plot.areaSqm ?? "Unknown"} sqm · ${build.brief.plot.shape}`} /><Brief name="Rooms and floors" value={`${build.brief.household.floors} floors · ${build.brief.household.rooms.filter((r) => r.quantity > 0).map((r) => `${r.quantity} ${r.label}`).join(", ")}`} /><Brief name="Style" value={build.brief.style.primaryStyle?.replace(/_/g, " ") ?? "Not selected"} /><Brief name="Budget" value={`${build.brief.budget.targetBudget?.toLocaleString() ?? "Not set"} ${build.brief.budget.currency}`} /><Brief name="Sustainability" value={build.brief.sustainability.items.filter((item) => item.priority).map((item) => item.label).join(", ") || "No selected priorities"} /><Brief name="Accessibility" value={build.brief.accessibility.items.filter((item) => item.priority).map((item) => item.label).join(", ") || "No selected priorities"} /></dl>}{renovate && <dl className="mt-5 grid gap-4 text-sm sm:grid-cols-2"><Brief name="Property" value={`${renovate.property.propertyType?.replace(/_/g, " ") ?? "Property"} · ${renovate.property.approxAreaSqm ?? "Unknown"} sqm`} /><Brief name="Renovation areas" value={renovate.assessment.areas.map((area) => area.customLabel || area.areaKey.replace(/_/g, " ")).join(", ")} /><Brief name="Existing condition" value={renovate.assessment.conditions.map((condition) => condition.conditionRating.replace(/_/g, " ")).join(", ") || "Shared in assessment"} /><Brief name="Keep, remove and change" value={renovate.assessment.keepRemoveChange.map((item) => `${item.listType}: ${item.item}`).join("; ")} /><Brief name="Budget and timeline" value={`${renovate.assessment.budgetTimeline.targetBudget?.toLocaleString() ?? "Not set"} ${renovate.assessment.budgetTimeline.currency} · ${renovate.assessment.budgetTimeline.requiredCompletionDate || "Timeline not set"}`} /><Brief name="Scope" value={`${renovate.scope.length} shared scope items`} /></dl>}</Card>
      <Card><h3 className="text-lg font-black text-slate-900">Shared documents</h3><div className="mt-4 divide-y divide-slate-100">{docs.map((doc) => <div key={doc.id} className="flex flex-col gap-3 py-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-sm font-bold text-slate-800">{doc.name}</p><p className="mt-1 text-xs text-slate-500">Customer owned · Included in this request</p></div><div className="flex gap-2"><SecondaryButton onClick={() => showToast("Prototype preview opened without changing the original.", "info")}>Preview</SecondaryButton><SecondaryButton onClick={() => showToast("Download recorded in the local prototype.")}>Download</SecondaryButton></div></div>)}{!docs.length && <p className="py-4 text-sm text-slate-500">No documents were included in this request.</p>}</div></Card></div>
      <aside className="space-y-6"><Card><h3 className="text-lg font-black text-slate-900">Request actions</h3><div className="mt-4 grid gap-3">{["submitted", "viewed", "clarification_requested", "requested"].includes(request.status) && <PrimaryButton onClick={() => setModal("accept")}>Accept Request</PrimaryButton>}{active && <SecondaryButton onClick={() => setModal("clarify")}>Ask for Clarification</SecondaryButton>}{active && <SecondaryButton onClick={() => setModal("consult")}>Propose Consultation</SecondaryButton>}{["accepted", "in_review", "changes_requested", "resubmitted"].includes(request.status) && request.source !== "renovate_quotation" && <Link href={`/professional/reviews/${request.id}`} className="inline-flex min-h-11 items-center justify-center rounded-xl bg-slate-900 px-4 text-sm font-bold text-white hover:bg-[#2ec440]">Open Review Workspace</Link>}{request.quotationId && <Link href={`/professional/quotations/${request.quotationId}`} className="inline-flex min-h-11 items-center justify-center rounded-xl bg-slate-900 px-4 text-sm font-bold text-white hover:bg-[#2ec440]">Prepare Quotation</Link>}{active && <button className="min-h-11 rounded-xl px-4 text-sm font-bold text-red-600 hover:bg-red-50" onClick={() => setModal("decline")}>Decline Request</button>}</div><p className="mt-4 text-xs leading-5 text-slate-500">Accepting does not create payment, a construction approval or a permit decision.</p></Card><Card><h3 className="text-lg font-black text-slate-900">Access boundary</h3><p className="mt-3 text-sm leading-6 text-slate-600">You can see only this request’s shared version and included documents. Originals remain customer-owned and cannot be replaced or deleted here.</p></Card></aside></div>
    <Dialog open={modal === "accept"} onClose={() => setModal(null)} labelledBy="accept-title" panelClassName="max-w-lg"><form className="p-6" onSubmit={(e) => { e.preventDefault(); act("accepted", "Request accepted. The customer can now see the updated status."); }}><h2 id="accept-title" className="text-xl font-black text-slate-900">Accept request</h2><p className="mt-2 text-sm text-slate-500">Confirm the service and expected response. No payment will be created.</p><label className="mt-5 block text-sm font-bold text-slate-700">Expected response date<input required type="date" className={`${fieldClass} mt-2`} defaultValue={new Date(Date.now() + 4 * 86400000).toISOString().slice(0, 10)} /></label><label className="mt-4 flex items-center gap-2 text-sm text-slate-700"><input type="checkbox" className="accent-[#2ec440]" />Onsite visit required</label><label className="mt-4 block text-sm font-bold text-slate-700">Initial note<textarea className={`${fieldClass} mt-2`} placeholder="Optional customer-visible note" /></label><ModalActions close={() => setModal(null)} submit="Accept Request" /></form></Dialog>
    <Dialog open={modal === "clarify"} onClose={() => setModal(null)} labelledBy="clarify-title" panelClassName="max-w-lg"><form className="p-6" onSubmit={(e) => { e.preventDefault(); ProfessionalService.addClarification(profile.id, request.id, { question, category, blocksWork: true, requestedResponseDate: new Date(Date.now() + 2 * 86400000).toISOString() }); setModal(null); showToast("Clarification sent to the customer."); }}><h2 id="clarify-title" className="text-xl font-black text-slate-900">Ask for clarification</h2><label className="mt-5 block text-sm font-bold text-slate-700">Category<select className={`${fieldClass} mt-2`} value={category} onChange={(e) => setCategory(e.target.value)}>{["Missing document", "Missing measurement", "Design requirement", "Budget", "Existing condition", "Safety", "Timeline", "Scope", "Other"].map((item) => <option key={item}>{item}</option>)}</select></label><label className="mt-4 block text-sm font-bold text-slate-700">Question<textarea required className={`${fieldClass} mt-2 min-h-28`} value={question} onChange={(e) => setQuestion(e.target.value)} /></label><label className="mt-4 flex items-center gap-2 text-sm text-slate-700"><input defaultChecked type="checkbox" className="accent-[#2ec440]" />Response required before work continues</label><ModalActions close={() => setModal(null)} submit="Send Clarification" /></form></Dialog>
    <Dialog open={modal === "decline"} onClose={() => setModal(null)} labelledBy="decline-title" panelClassName="max-w-lg"><form className="p-6" onSubmit={(e) => { e.preventDefault(); ProfessionalService.declineRequest(profile.id, request.id, reason, note); setModal(null); showToast("Request declined. The record was preserved."); }}><h2 id="decline-title" className="text-xl font-black text-slate-900">Decline request</h2><label className="mt-5 block text-sm font-bold text-slate-700">Reason<select className={`${fieldClass} mt-2`} value={reason} onChange={(e) => setReason(e.target.value)}>{["Outside expertise", "Outside service area", "Insufficient availability", "Missing required information", "Conflict of interest", "Project risk", "Budget mismatch", "Other"].map((item) => <option key={item}>{item}</option>)}</select></label><label className="mt-4 block text-sm font-bold text-slate-700">Internal note<textarea className={`${fieldClass} mt-2`} value={note} onChange={(e) => setNote(e.target.value)} /><span className="mt-1 block text-xs font-normal text-slate-500">This note is not shown to the customer.</span></label><ModalActions close={() => setModal(null)} submit="Decline Request" destructive /></form></Dialog>
    <Dialog open={modal === "consult"} onClose={() => setModal(null)} labelledBy="consult-title" panelClassName="max-w-lg"><form className="p-6" onSubmit={(e) => { e.preventDefault(); ProfessionalService.addConsultation(profile.id, { requestId: request.id, type: "Design review meeting", startsAt: new Date(Date.now() + 3 * 86400000).toISOString(), durationMinutes: 45, timezone: "Africa/Kigali", method: "Demo video meeting information", purpose: "Discuss the shared project information.", preparation: "Review the shared brief and documents.", status: "proposed" }); setModal(null); showToast("Consultation proposed."); }}><h2 id="consult-title" className="text-xl font-black text-slate-900">Propose consultation</h2><p className="mt-2 text-sm text-slate-500">A demo meeting record will be created; no external meeting link is generated.</p><label className="mt-5 block text-sm font-bold text-slate-700">Consultation type<select className={`${fieldClass} mt-2`}><option>Video consultation</option><option>Phone consultation</option><option>Onsite visit</option><option>Design review meeting</option><option>Measurement visit</option><option>Inspection</option><option>Quotation walkthrough</option></select></label><label className="mt-4 block text-sm font-bold text-slate-700">Proposed date and time<input type="datetime-local" required className={`${fieldClass} mt-2`} defaultValue={new Date(Date.now() + 3 * 86400000).toISOString().slice(0, 16)} /></label><ModalActions close={() => setModal(null)} submit="Propose Consultation" /></form></Dialog>
  </PageFrame>;
}

function Brief({ name, value }: { name: string; value: string }) { return <div><dt className="text-xs font-bold uppercase text-slate-400">{name}</dt><dd className="mt-1 leading-6 text-slate-700">{value}</dd></div>; }
function ModalActions({ close, submit, destructive = false }: { close: () => void; submit: string; destructive?: boolean }) { return <div className="mt-6 flex flex-col-reverse gap-3 sm:flex-row sm:justify-end"><SecondaryButton type="button" onClick={close}>Cancel</SecondaryButton><PrimaryButton type="submit" className={destructive ? "bg-red-600 hover:bg-red-700" : ""}>{submit}</PrimaryButton></div>; }
