"use client";

import { useState } from "react";
import ConfirmModal from "@/components/shared/ConfirmModal";
import Dialog from "@/components/Dialog";
import { useAuth } from "@/lib/auth-context";
import { BuildProjectService } from "@/lib/build/projectService";
import { RenovationProjectService } from "@/lib/renovate/projectService";
import { useProfessionalProfile, useProfessionalState } from "@/lib/professional/hooks";
import { ProfessionalService } from "@/lib/professional/service";
import type { Annotation } from "@/lib/professional/types";
import { useToast } from "@/lib/toast-context";
import { Card, EmptyState, PageFrame, PrimaryButton, SecondaryButton, StatusPill, fieldClass, formatMoney } from "./ui";

const checklistByRole: Record<string, string[]> = {
  Architect: ["Brief alignment", "Room relationships", "Circulation", "Privacy", "Natural light", "Ventilation", "Site response", "Accessibility", "Future expansion", "Documentation gaps"],
  "Structural Engineer": ["Structural information available", "Structural assumptions identified", "Additional floor implications", "Large openings", "Long spans", "Foundation information", "Site inspection requirement"],
  "Quantity Surveyor": ["Floor area", "Finish level", "Scope completeness", "Material assumptions", "Labour assumptions", "Contingency", "Exclusions", "Cost risks"],
  "Interior Designer": ["Functional layout", "Storage", "Materials", "Lighting", "Furniture circulation", "Maintenance", "Style consistency", "Accessibility"],
};
const outcomes = ["Suitable for further development", "Suitable with recommendations", "Changes required", "Additional information required", "Site inspection required", "Outside review scope"];

export default function ReviewWorkspace({ reviewId }: { reviewId: string }) {
  const { account } = useAuth(); const profile = useProfessionalProfile(account?.id); const state = useProfessionalState(); const { showToast } = useToast(); const [commentOpen, setCommentOpen] = useState(false); const [submitOpen, setSubmitOpen] = useState(false);
  const [outcome, setOutcome] = useState("Suitable with recommendations"); const [summary, setSummary] = useState(""); const [annotationType, setAnnotationType] = useState<Annotation["type"]>("pin"); const [annotationText, setAnnotationText] = useState("");
  const [comment, setComment] = useState({ title: "", description: "", category: "Design requirement", severity: "recommendation" as "info" | "recommendation" | "issue" | "critical", recommendation: "", customerActionRequired: false });
  if (!profile) return null; const request = ProfessionalService.getRequest(profile.id, reviewId); if (!request || request.source === "renovate_quotation") return <PageFrame title="Review unavailable" description="This review does not exist or is not assigned to your profile."><EmptyState title="Access denied" description="No customer project information has been revealed." /></PageFrame>;
  const draft = state.reviewDrafts.find((item) => item.requestId === reviewId) ?? { requestId: reviewId, checklist: {}, privateNotes: "", annotations: [], lockedVersions: [] };
  const buildReview = request.source === "build_review" ? BuildProjectService.getById(request.projectId)?.reviewRequests.find((item) => item.id === reviewId) : undefined; const renovateReview = request.source === "renovate_review" ? RenovationProjectService.getById(request.projectId)?.reviewRequests.find((item) => item.id === reviewId) : undefined; const feedback = buildReview?.feedback ?? renovateReview?.feedback ?? [];
  const checklist = checklistByRole[profile.primarySpecialisation] ?? ["Shared brief reviewed", "Documents reviewed", "Assumptions identified", "Information gaps recorded", "Customer questions answered", "Recommendations prepared"];
  const criticalCount = feedback.filter((item) => item.severity === "critical" && !item.addressed).length; const isQS = profile.primarySpecialisation === "Quantity Surveyor";
  const estimate = draft.professionalEstimate ?? { low: 0, expected: 0, high: 0, contingencyPct: 10, exclusions: [] };
  const saveDraft = (update = {}) => { ProfessionalService.saveReviewDraft(profile.id, reviewId, { ...draft, ...update }); showToast("Review draft saved privately."); };
  return <PageFrame title={`${request.requestType} workspace`} description={`${request.projectName} · ${request.customerName} · ${request.sharedVersion}`} action={<StatusPill status={request.status} />}>
    <div className="mb-6 flex flex-wrap gap-3"><PrimaryButton onClick={() => ProfessionalService.setRequestStatus(profile.id, reviewId, "in_review", "Professional started the review.")}>Start Review</PrimaryButton><SecondaryButton onClick={() => saveDraft()}>Save Draft</SecondaryButton><PrimaryButton onClick={() => setSubmitOpen(true)}>Submit Review</PrimaryButton></div>
    <div className="grid gap-6 xl:grid-cols-[1fr_.75fr]"><div className="space-y-6"><Card><div className="flex items-start justify-between gap-4"><div><h3 className="text-lg font-black text-slate-900">Role-specific checklist</h3><p className="mt-1 text-sm text-slate-500">Checklist completion records review coverage; it does not certify compliance.</p></div><span className="text-xs font-bold text-slate-400">{Object.values(draft.checklist).filter(Boolean).length}/{checklist.length}</span></div><div className="mt-4 grid gap-2 sm:grid-cols-2">{checklist.map((item) => <label key={item} className="flex items-start gap-3 rounded-xl border border-slate-200 p-3 text-sm font-semibold text-slate-700"><input type="checkbox" className="mt-0.5 h-4 w-4 accent-[#2ec440]" checked={draft.checklist[item] ?? false} onChange={(e) => ProfessionalService.saveReviewDraft(profile.id, reviewId, { ...draft, checklist: { ...draft.checklist, [item]: e.target.checked } })} />{item}</label>)}</div></Card>
      <Card><div className="flex items-center justify-between"><div><h3 className="text-lg font-black text-slate-900">Review comments</h3><p className="mt-1 text-sm text-slate-500">Customer-visible findings remain linked to this review version.</p></div><SecondaryButton onClick={() => setCommentOpen(true)}>Add Comment</SecondaryButton></div><div className="mt-4 space-y-3">{feedback.map((item) => { const customerReply = (item as { reply?: string; response?: string }).reply ?? (item as { reply?: string; response?: string }).response; return <article key={item.id} className="rounded-xl border border-slate-200 p-4"><div className="flex flex-wrap items-center justify-between gap-2"><h4 className="font-black text-slate-900">{item.title ?? item.category ?? "Review comment"}</h4><StatusPill status={item.severity} /></div><p className="mt-2 text-sm leading-6 text-slate-600">{item.comment}</p>{item.recommendation && <p className="mt-2 text-sm font-semibold text-slate-800">Recommendation: {item.recommendation}</p>}{customerReply && <div className="mt-3 rounded-lg bg-[#2ec440]/5 p-3 text-sm text-slate-700"><span className="font-bold text-[#219b31]">Customer reply: </span>{customerReply}</div>}<div className="mt-3 flex flex-wrap items-center justify-between gap-2"><p className="text-xs text-slate-400">{item.addressed ? "Addressed" : item.customerActionRequired ? "Customer action required" : "Open"}</p>{!item.addressed && <button className="text-xs font-bold text-[#219b31] hover:underline" onClick={() => { const markAddressed = <R extends { feedback: Array<{ id: string; addressed: boolean }> }>(review: R): R => ({ ...review, feedback: review.feedback.map((entry) => entry.id === item.id ? { ...entry, addressed: true } : entry) }); if (request.source === "build_review") BuildProjectService.updateReview(request.projectId, reviewId, markAddressed, "Professional marked a comment addressed."); else RenovationProjectService.updateReview(request.projectId, reviewId, markAddressed, "Professional marked a comment addressed."); }}>Mark addressed</button>}</div></article>; })}{!feedback.length && <p className="text-sm text-slate-500">No review comments yet.</p>}</div></Card>
      <Card><h3 className="text-lg font-black text-slate-900">Visual annotations</h3><p className="mt-1 text-sm text-slate-500">Annotations are stored as a separate overlay and never alter the shared image.</p><div className="mt-4 grid gap-4 lg:grid-cols-[1fr_240px]"><div className="relative min-h-72 overflow-hidden rounded-xl bg-gradient-to-br from-slate-100 to-slate-200" aria-label="Conceptual shared image annotation area"><div className="absolute inset-0 flex items-center justify-center text-center text-sm font-bold text-slate-400">Shared conceptual image<br />Annotation preview</div>{draft.annotations.map((item) => <button key={item.id} title={item.text} aria-label={`${item.type} annotation: ${item.text}`} className={`absolute flex h-8 w-8 items-center justify-center rounded-full text-xs font-black text-white shadow-lg ${item.severity === "critical" ? "bg-red-600" : item.severity === "important" ? "bg-amber-500" : "bg-[#2ec440]"}`} style={{ left: `${item.x}%`, top: `${item.y}%` }}>{item.type === "pin" ? "●" : item.type === "arrow" ? "→" : "□"}</button>)}</div><div><label className="text-sm font-bold text-slate-700">Annotation type<select className={`${fieldClass} mt-2`} value={annotationType} onChange={(e) => setAnnotationType(e.target.value as Annotation["type"])}><option value="pin">Pin comment</option><option value="rectangle">Rectangle highlight</option><option value="arrow">Arrow</option><option value="text">Text note</option></select></label><label className="mt-4 block text-sm font-bold text-slate-700">Accessible note<textarea className={`${fieldClass} mt-2 min-h-24`} value={annotationText} onChange={(e) => setAnnotationText(e.target.value)} /></label><SecondaryButton className="mt-4 w-full" onClick={() => { if (!annotationText.trim()) return; const annotation: Annotation = { id: `annotation_${Date.now()}`, type: annotationType, x: 20 + (draft.annotations.length * 17) % 65, y: 18 + (draft.annotations.length * 13) % 65, text: annotationText.trim(), severity: "recommendation", published: false }; ProfessionalService.saveReviewDraft(profile.id, reviewId, { ...draft, annotations: [...draft.annotations, annotation] }); setAnnotationText(""); }}>Add draft annotation</SecondaryButton></div></div></Card>
      {isQS && <Card><h3 className="text-lg font-black text-slate-900">Quantity surveyor estimate</h3><p className="mt-1 text-sm text-slate-500">This professional estimate remains separate from the customer’s AI indicative estimate and any contractor quotation.</p><div className="mt-5 grid gap-4 sm:grid-cols-4"><MoneyField label="Low estimate" value={estimate.low} onChange={(value) => saveDraft({ professionalEstimate: { ...estimate, low: value } })} /><MoneyField label="Expected estimate" value={estimate.expected} onChange={(value) => saveDraft({ professionalEstimate: { ...estimate, expected: value } })} /><MoneyField label="High estimate" value={estimate.high} onChange={(value) => saveDraft({ professionalEstimate: { ...estimate, high: value } })} /><MoneyField label="Contingency %" value={estimate.contingencyPct} onChange={(value) => saveDraft({ professionalEstimate: { ...estimate, contingencyPct: value } })} /></div><p className="mt-4 text-sm font-bold text-slate-800">Expected professional estimate: {formatMoney(estimate.expected)}</p></Card>}</div>
      <aside className="space-y-6"><Card><h3 className="text-lg font-black text-slate-900">Review status</h3><dl className="mt-4 space-y-3 text-sm"><Info name="Deadline" value={new Date(request.desiredResponseDate).toLocaleDateString()} /><Info name="Published comments" value={String(feedback.length)} /><Info name="Critical unresolved" value={String(criticalCount)} /><Info name="Draft annotations" value={String(draft.annotations.filter((item) => !item.published).length)} /><Info name="Submitted versions" value={String(draft.lockedVersions.length)} /></dl></Card><Card><h3 className="text-lg font-black text-slate-900">Version comparison</h3><p className="mt-3 text-sm text-slate-600">Previous: {request.sharedVersion}</p><p className="mt-2 text-sm text-slate-600">Revised: {request.status === "resubmitted" ? "Customer resubmission" : "No revised version shared"}</p><p className="mt-3 text-xs text-slate-500">Open comments remain preserved across review versions and can be marked addressed, partially addressed, not addressed or no longer applicable in a follow-up.</p></Card><Card><h3 className="text-lg font-black text-slate-900">Professional-only notes</h3><textarea className={`${fieldClass} mt-3 min-h-32`} value={draft.privateNotes} onChange={(e) => ProfessionalService.saveReviewDraft(profile.id, reviewId, { ...draft, privateNotes: e.target.value })} placeholder="Private working notes are not visible to the customer." /></Card></aside></div>
    <Dialog open={commentOpen} onClose={() => setCommentOpen(false)} labelledBy="comment-title" panelClassName="max-w-xl"><form className="p-6" onSubmit={(e) => { e.preventDefault(); ProfessionalService.addReviewComment(profile.id, reviewId, comment); setCommentOpen(false); setComment({ title: "", description: "", category: "Design requirement", severity: "recommendation", recommendation: "", customerActionRequired: false }); showToast("Review comment added."); }}><h2 id="comment-title" className="text-xl font-black text-slate-900">Add review comment</h2><div className="mt-5 grid gap-4 sm:grid-cols-2"><label className="text-sm font-bold text-slate-700 sm:col-span-2">Title<input required className={`${fieldClass} mt-2`} value={comment.title} onChange={(e) => setComment({ ...comment, title: e.target.value })} /></label><label className="text-sm font-bold text-slate-700">Category<select className={`${fieldClass} mt-2`} value={comment.category} onChange={(e) => setComment({ ...comment, category: e.target.value })}>{["Design requirement", "Documentation", "Safety", "Budget", "Scope", "Accessibility", "Other"].map((item) => <option key={item}>{item}</option>)}</select></label><label className="text-sm font-bold text-slate-700">Severity<select className={`${fieldClass} mt-2`} value={comment.severity} onChange={(e) => setComment({ ...comment, severity: e.target.value as typeof comment.severity })}><option value="info">Information</option><option value="recommendation">Recommendation</option><option value="issue">Important</option><option value="critical">Critical Review Required</option></select></label><label className="text-sm font-bold text-slate-700 sm:col-span-2">Description<textarea required className={`${fieldClass} mt-2 min-h-24`} value={comment.description} onChange={(e) => setComment({ ...comment, description: e.target.value })} /></label><label className="text-sm font-bold text-slate-700 sm:col-span-2">Recommendation<textarea className={`${fieldClass} mt-2`} value={comment.recommendation} onChange={(e) => setComment({ ...comment, recommendation: e.target.value })} /></label><label className="flex items-center gap-2 text-sm font-semibold sm:col-span-2"><input type="checkbox" className="accent-[#2ec440]" checked={comment.customerActionRequired} onChange={(e) => setComment({ ...comment, customerActionRequired: e.target.checked })} />Customer action required</label></div><div className="mt-6 flex justify-end gap-3"><SecondaryButton type="button" onClick={() => setCommentOpen(false)}>Cancel</SecondaryButton><PrimaryButton type="submit">Add Comment</PrimaryButton></div></form></Dialog>
    <ConfirmModal open={submitOpen} onClose={() => setSubmitOpen(false)} onConfirm={() => { const ok = ProfessionalService.submitReview(profile.id, reviewId, outcome, summary); if (ok) { setSubmitOpen(false); showToast("Review submitted and locked. Future changes require an addendum."); } }} title="Submit review version?" description={<span>This publishes {feedback.length} comment{feedback.length === 1 ? "" : "s"}, including {criticalCount} unresolved critical comment{criticalCount === 1 ? "" : "s"}. The submitted version is locked and later changes require an addendum.</span>} confirmLabel="Submit Review"><label className="block text-sm font-bold text-slate-700">Review outcome<select className={`${fieldClass} mt-2`} value={outcome} onChange={(e) => setOutcome(e.target.value)}>{outcomes.map((item) => <option key={item}>{item}</option>)}</select></label><label className="mt-4 block text-sm font-bold text-slate-700">Customer-visible summary<textarea required className={`${fieldClass} mt-2 min-h-24`} value={summary} onChange={(e) => setSummary(e.target.value)} /></label><label className="mt-4 flex items-start gap-2 text-sm text-slate-600"><input required type="checkbox" className="mt-1 accent-[#2ec440]" />I confirm this is a professional review within my stated scope and is not approval for construction.</label></ConfirmModal>
  </PageFrame>;
}

function Info({ name, value }: { name: string; value: string }) { return <div className="flex justify-between gap-4"><dt className="text-slate-400">{name}</dt><dd className="font-bold text-slate-800">{value}</dd></div>; }
function MoneyField({ label, value, onChange }: { label: string; value: number; onChange: (value: number) => void }) { return <label className="text-sm font-bold text-slate-700">{label}<input type="number" min="0" className={`${fieldClass} mt-2`} value={value} onChange={(e) => onChange(Number(e.target.value))} /></label>; }
