"use client";

import Link from "next/link";
import { useState } from "react";
import ConfirmModal from "@/components/shared/ConfirmModal";
import { useAuth } from "@/lib/auth-context";
import { useProfessionalProfile, useProfessionalState } from "@/lib/professional/hooks";
import { ProfessionalService } from "@/lib/professional/service";
import { useToast } from "@/lib/toast-context";
import { Card, EmptyState, PageFrame, PrimaryButton, PrimaryLink, SecondaryButton, StatusPill, fieldClass, formatDate } from "./ui";

function useWorkspace() { const { account } = useAuth(); const profile = useProfessionalProfile(account?.id); const state = useProfessionalState(); return { profile, state, requests: profile ? ProfessionalService.getRequests(profile.id) : [] }; }

export function DashboardPage() {
  const { profile, state, requests } = useWorkspace(); const { showToast } = useToast(); const [availabilityOpen, setAvailabilityOpen] = useState(false); const [nextAvailability, setNextAvailability] = useState(profile?.availability ?? "available");
  if (!profile) return null;
  const reviews = requests.filter((request) => request.source !== "renovate_quotation"); const quotes = requests.filter((request) => request.source === "renovate_quotation"); const active = requests.filter((request) => !["completed", "declined", "cancelled", "accepted"].includes(request.status));
  const stats = [["New requests", requests.filter((r) => r.status === "submitted" || r.status === "requested").length], ["Active reviews", reviews.filter((r) => ["accepted", "in_review", "changes_requested"].includes(r.status)).length], ["Quotations awaiting submission", quotes.filter((r) => !["submitted", "revised", "accepted"].includes(r.status)).length], ["Upcoming consultations", state.consultations.filter((c) => c.profileId === profile.id && ["proposed", "confirmed"].includes(c.status)).length], ["Completed work", requests.filter((r) => ["completed", "accepted"].includes(r.status)).length], ["Needs attention", requests.filter((r) => r.professionalActionRequired).length]];
  return <PageFrame title="Professional dashboard" description="Manage shared requests, reviews, quotations and consultations from one restricted workspace." action={<SecondaryButton onClick={() => setAvailabilityOpen(true)}>Change availability</SecondaryButton>}>
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-6">{stats.map(([name, value]) => <Card key={name} className="p-4"><p className="text-xs font-bold uppercase tracking-wide text-slate-400">{name}</p><p className="mt-2 text-3xl font-black text-slate-900">{value}</p></Card>)}</div>
    <div className="mt-6 grid gap-6 xl:grid-cols-[1.35fr_.65fr]"><Card><div className="mb-4 flex items-center justify-between"><h3 className="text-lg font-black text-slate-900">Priority work</h3><Link className="text-sm font-bold text-[#219b31]" href="/professional/requests">View all</Link></div>{active.length ? <div className="divide-y divide-slate-100">{active.slice(0, 5).map((request) => <Link key={`${request.id}-${request.source}`} href={`/professional/requests/${request.id}`} className="flex flex-col gap-2 py-4 first:pt-0 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-bold text-slate-900">{request.projectName}</p><p className="mt-1 text-sm text-slate-500">{request.requestType} · due {formatDate(request.desiredResponseDate)}</p></div><StatusPill status={request.status} /></Link>)}</div> : <p className="text-sm text-slate-500">No work needs attention.</p>}</Card>
    <Card><h3 className="text-lg font-black text-slate-900">Recent activity</h3><div className="mt-4 space-y-4">{state.activity.filter((item) => item.profileId === profile.id).slice(0, 5).map((item) => <div key={item.id} className="border-l-2 border-[#2ec440] pl-3"><p className="text-sm font-semibold text-slate-800">{item.description}</p><p className="mt-1 text-xs text-slate-400">{formatDate(item.createdAt)}</p></div>)}{!state.activity.some((item) => item.profileId === profile.id) && <p className="text-sm text-slate-500">Activity appears here as you work.</p>}</div></Card></div>
    <ConfirmModal open={availabilityOpen} onClose={() => setAvailabilityOpen(false)} onConfirm={() => { ProfessionalService.updateProfile(profile.id, { availability: nextAvailability as typeof profile.availability, acceptingNewWork: nextAvailability !== "unavailable" }); setAvailabilityOpen(false); showToast("Availability updated."); }} title="Change availability" description={active.length ? `You have ${active.length} active request${active.length === 1 ? "" : "s"}. Customers with existing work can still contact you.` : "Choose how your profile should appear to customers."} confirmLabel="Update availability"><label className="block text-sm font-bold text-slate-700">Availability<select className={`${fieldClass} mt-2`} value={nextAvailability} onChange={(e) => setNextAvailability(e.target.value as typeof nextAvailability)}><option value="available">Available</option><option value="limited">Limited availability</option><option value="unavailable">Not accepting new requests</option></select></label></ConfirmModal>
  </PageFrame>;
}

export function RequestsPage() {
  const { requests } = useWorkspace(); const [type, setType] = useState("all"); const [status, setStatus] = useState("all"); const filtered = requests.filter((request) => (type === "all" || request.source === type) && (status === "all" || request.status === status));
  return <PageFrame title="Request inbox" description="Only requests addressed to your profile are shown. List views exclude unnecessary private customer information."><div className="mb-5 flex flex-col gap-3 rounded-2xl border border-slate-200 bg-white p-4 sm:flex-row"><label className="text-sm font-bold text-slate-700">Request type<select className={`${fieldClass} mt-1 sm:min-w-56`} value={type} onChange={(e) => setType(e.target.value)}><option value="all">All request types</option><option value="build_review">Build review</option><option value="renovate_review">Renovation review</option><option value="renovate_quotation">Contractor quotation</option></select></label><label className="text-sm font-bold text-slate-700">Status<select className={`${fieldClass} mt-1 sm:min-w-52`} value={status} onChange={(e) => setStatus(e.target.value)}><option value="all">All statuses</option>{Array.from(new Set(requests.map((request) => request.status))).map((item) => <option key={item}>{item}</option>)}</select></label></div>{filtered.length ? <div className="grid gap-4">{filtered.map((request) => <Card key={`${request.id}-${request.source}`} className="p-0"><div className="grid gap-4 p-5 md:grid-cols-[1fr_auto] md:items-center"><div><div className="flex flex-wrap items-center gap-2"><span className="text-xs font-black uppercase tracking-wide text-[#219b31]">{request.projectType}</span><StatusPill status={request.status} />{request.safetyFlag && <span className="rounded-full bg-red-50 px-2.5 py-1 text-xs font-bold text-red-700">Safety information shared</span>}</div><h3 className="mt-3 text-lg font-black text-slate-900">{request.projectName}</h3><p className="mt-1 text-sm text-slate-500">{request.requestType} · {request.location} · {request.sharedVersion}</p><dl className="mt-4 grid grid-cols-2 gap-3 text-sm sm:grid-cols-4"><div><dt className="text-xs text-slate-400">Reference</dt><dd className="mt-1 font-semibold text-slate-700">{request.id.slice(0, 14)}</dd></div><div><dt className="text-xs text-slate-400">Customer</dt><dd className="mt-1 font-semibold text-slate-700">{request.customerName}</dd></div><div><dt className="text-xs text-slate-400">Submitted</dt><dd className="mt-1 font-semibold text-slate-700">{formatDate(request.submittedAt)}</dd></div><div><dt className="text-xs text-slate-400">Desired response</dt><dd className="mt-1 font-semibold text-slate-700">{formatDate(request.desiredResponseDate)}</dd></div></dl></div><PrimaryLink href={`/professional/requests/${request.id}`}>Open Request</PrimaryLink></div></Card>)}</div> : <EmptyState title="No matching requests" description="Try a different filter or check again when a customer shares work with you." />}</PageFrame>;
}

export function ProjectsPage() { const { requests } = useWorkspace(); const projects = Array.from(new Map(requests.map((request) => [request.projectId, request])).values()); return <PageFrame title="Shared projects" description="Restricted project views include only the versions, documents and messages explicitly shared through your requests.">{projects.length ? <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{projects.map((request) => <Card key={request.projectId}><span className="text-xs font-black uppercase tracking-wide text-[#219b31]">{request.projectType}</span><h3 className="mt-2 text-lg font-black text-slate-900">{request.projectName}</h3><p className="mt-2 text-sm text-slate-500">{request.requestType} · {request.location}</p><div className="mt-5 flex items-center justify-between"><StatusPill status={request.status} /><Link className="text-sm font-bold text-[#219b31]" href={`/professional/projects/${request.projectId}`}>Open project</Link></div></Card>)}</div> : <EmptyState title="No shared projects" description="A project appears here only after a customer shares it with your profile." />}</PageFrame>; }

export function ReviewsPage() { const { requests } = useWorkspace(); const reviews = requests.filter((request) => request.source !== "renovate_quotation"); return <PageFrame title="Professional reviews" description="Prepare role-appropriate checklists, comments, annotations and locked review submissions.">{reviews.length ? <div className="grid gap-4 md:grid-cols-2">{reviews.map((request) => <Card key={request.id}><div className="flex items-center justify-between gap-3"><div><p className="text-xs font-black uppercase text-[#219b31]">{request.requestType}</p><h3 className="mt-2 font-black text-slate-900">{request.projectName}</h3></div><StatusPill status={request.status} /></div><PrimaryLink href={`/professional/reviews/${request.id}`}>Open review workspace</PrimaryLink></Card>)}</div> : <EmptyState title="No reviews" description="Accepted review requests appear here." />}</PageFrame>; }

export function QuotationsPage() { const { requests } = useWorkspace(); const quotes = requests.filter((request) => request.quotationId); return <PageFrame title="Contractor quotations" description="Prepare and version itemised quotations. No payment is processed in this prototype.">{quotes.length ? <div className="grid gap-4">{quotes.map((request) => <Card key={request.quotationId}><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-xs font-black uppercase text-[#219b31]">Quotation {request.quotationId?.slice(0, 12)}</p><h3 className="mt-2 text-lg font-black text-slate-900">{request.projectName}</h3><p className="mt-1 text-sm text-slate-500">{request.location} · requested {formatDate(request.submittedAt)}</p></div><div className="flex items-center gap-3"><StatusPill status={request.status} /><PrimaryLink href={`/professional/quotations/${request.quotationId}`}>Prepare quotation</PrimaryLink></div></div></Card>)}</div> : <EmptyState title="No quotation requests" description="Quotation requests addressed to your contractor profile appear here." />}</PageFrame>; }

export function MessagesPage() { const { profile, state, requests } = useWorkspace(); const [selected, setSelected] = useState(requests[0]?.id ?? ""); const [text, setText] = useState(""); const { showToast } = useToast(); if (!profile) return null; const messages = state.messages.filter((message) => message.profileId === profile.id && message.requestId === selected); return <PageFrame title="Messages" description="Conversations are restricted to shared requests, projects, clarifications and consultations.">{requests.length ? <div className="grid min-h-[520px] overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm md:grid-cols-[280px_1fr]"><aside className="border-b border-slate-200 md:border-b-0 md:border-r"><h3 className="p-4 text-sm font-black text-slate-900">Conversations</h3>{requests.map((request) => <button key={`${request.id}-${request.source}`} onClick={() => setSelected(request.id)} className={`w-full border-t border-slate-100 p-4 text-left ${selected === request.id ? "bg-[#2ec440]/5" : "hover:bg-slate-50"}`}><p className="font-bold text-slate-900">{request.customerName}</p><p className="mt-1 truncate text-xs text-slate-500">{request.projectName} · {request.requestType}</p></button>)}</aside><section className="flex min-w-0 flex-col"><div className="flex-1 space-y-3 overflow-y-auto p-5">{messages.map((message) => <div key={message.id} className={`max-w-[85%] rounded-2xl px-4 py-3 text-sm ${message.sender === "professional" ? "ml-auto bg-slate-900 text-white" : message.sender === "system" ? "mx-auto bg-slate-100 text-slate-600" : "bg-[#2ec440]/10 text-slate-800"}`}><p>{message.text}</p><p className="mt-1 text-[11px] opacity-60">{formatDate(message.createdAt)}{message.sender === "system" ? " · System message" : ""}</p></div>)}{!messages.length && <p className="text-center text-sm text-slate-400">No messages in this request yet.</p>}</div><form className="flex gap-2 border-t border-slate-200 p-4" onSubmit={(e) => { e.preventDefault(); if (!text.trim()) return; ProfessionalService.sendMessage(profile.id, selected, text.trim()); setText(""); showToast("Message sent."); }}><label className="sr-only" htmlFor="message-input">Message</label><input id="message-input" className={fieldClass} value={text} onChange={(e) => setText(e.target.value)} placeholder="Write a request-related message…" /><PrimaryButton type="submit">Send</PrimaryButton></form></section></div> : <EmptyState title="No messages" description="Conversations appear after a shared request is created." />}</PageFrame>; }

export function CalendarPage() { const { profile, state, requests } = useWorkspace(); const { showToast } = useToast(); if (!profile) return null; const items = state.consultations.filter((item) => item.profileId === profile.id); return <PageFrame title="Consultations and calendar" description="Times use Africa/Kigali unless otherwise shown. Meeting information is demo-only and does not create an external meeting link." action={requests[0] ? <PrimaryButton onClick={() => { ProfessionalService.addConsultation(profile.id, { requestId: requests[0].id, type: "Video consultation", startsAt: new Date(Date.now() + 3 * 86400000).toISOString(), durationMinutes: 45, timezone: "Africa/Kigali", method: "Demo video meeting information", purpose: "Discuss the shared brief and open questions.", preparation: "Review the shared concept before joining.", status: "proposed" }); showToast("Consultation proposed."); }}>Propose consultation</PrimaryButton> : undefined}>{items.length ? <div className="space-y-4">{items.map((item) => <Card key={item.id}><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-xs font-black uppercase text-[#219b31]">{new Intl.DateTimeFormat("en-RW", { dateStyle: "full", timeStyle: "short", timeZone: item.timezone }).format(new Date(item.startsAt))}</p><h3 className="mt-2 text-lg font-black text-slate-900">{item.type}</h3><p className="mt-1 text-sm text-slate-500">{item.durationMinutes} minutes · {item.method}</p><p className="mt-2 text-sm text-slate-700">{item.purpose}</p></div><div className="flex flex-wrap items-center gap-2"><StatusPill status={item.status} />{item.status !== "completed" && item.status !== "cancelled" && <><SecondaryButton onClick={() => ProfessionalService.updateConsultation(profile.id, item.id, { status: "completed" })}>Mark completed</SecondaryButton><SecondaryButton onClick={() => ProfessionalService.updateConsultation(profile.id, item.id, { status: "cancelled" })}>Cancel</SecondaryButton></>}</div></div></Card>)}</div> : <EmptyState title="No consultations" description="Proposed and confirmed consultations appear in this accessible list view." />}</PageFrame>; }

export function DocumentsPage() { const { profile, state, requests } = useWorkspace(); const { showToast } = useToast(); if (!profile) return null; const own = state.files.filter((file) => file.ownerProfileId === profile.id); const shared = requests.flatMap((request) => request.documentIds.map((documentId) => ({ documentId, request }))); return <PageFrame title="Professional documents" description="Customer-owned files remain read-only. Professional drafts and submissions keep explicit access labels." action={<label className="inline-flex min-h-11 cursor-pointer items-center rounded-xl bg-slate-900 px-4 text-sm font-bold text-white hover:bg-[#2ec440]">Add working file<input className="sr-only" type="file" accept=".pdf,.jpg,.jpeg,.png,.webp" onChange={(e) => { const file = e.target.files?.[0]; if (!file) return; ProfessionalService.addFile(profile.id, { name: file.name, mimeType: file.type, size: file.size, category: "working", access: "professional_private", submitted: false }); showToast("Working file added locally."); e.currentTarget.value = ""; }} /></label>}><div className="space-y-6"><Card><h3 className="text-lg font-black text-slate-900">Shared customer documents</h3><div className="mt-4 divide-y divide-slate-100">{shared.map(({ documentId, request }) => <div key={`${request.id}-${documentId}`} className="flex items-center justify-between gap-3 py-3"><div><p className="text-sm font-bold text-slate-800">Shared document {documentId.slice(0, 10)}</p><p className="text-xs text-slate-500">{request.projectName} · Customer owned · Read only</p></div><SecondaryButton onClick={() => showToast("Prototype preview opened. Original file was not changed.", "info")}>Preview</SecondaryButton></div>)}{!shared.length && <p className="text-sm text-slate-500">No customer documents have been shared.</p>}</div></Card><Card><h3 className="text-lg font-black text-slate-900">Your files</h3><div className="mt-4 divide-y divide-slate-100">{own.map((file) => <div key={file.id} className="flex items-center justify-between gap-3 py-3"><div><p className="text-sm font-bold text-slate-800">{file.name}</p><p className="text-xs text-slate-500">{file.category} · {file.access.replace(/_/g, " ")}</p></div>{!file.submitted && <SecondaryButton onClick={() => ProfessionalService.removeOwnDraftFile(profile.id, file.id)}>Delete draft</SecondaryButton>}</div>)}{!own.length && <p className="text-sm text-slate-500">No professional files yet.</p>}</div></Card></div></PageFrame>; }

export function ProfilePage() { const { profile } = useWorkspace(); const { showToast } = useToast(); const [bio, setBio] = useState(profile?.biography ?? ""); if (!profile) return null; return <PageFrame title="Professional profile" description="Edit your service profile and preview the information customers can see. Verification documents are never public."><div className="grid gap-6 xl:grid-cols-[1fr_.8fr]"><Card><h3 className="text-lg font-black text-slate-900">Profile details</h3><div className="mt-5 grid gap-4 sm:grid-cols-2"><label className="text-sm font-bold text-slate-700">Display name<input className={`${fieldClass} mt-2`} defaultValue={profile.displayName} /></label><label className="text-sm font-bold text-slate-700">Primary specialisation<input className={`${fieldClass} mt-2`} value={profile.primarySpecialisation} readOnly /></label><label className="text-sm font-bold text-slate-700 sm:col-span-2">Professional biography<textarea className={`${fieldClass} mt-2 min-h-32`} value={bio} onChange={(e) => setBio(e.target.value)} /></label></div><PrimaryButton className="mt-5" onClick={() => { ProfessionalService.updateProfile(profile.id, { biography: bio }); showToast("Profile updated."); }}>Save profile</PrimaryButton><p className="mt-4 text-xs text-slate-500">Changing verified registration or identity information requires a new review and does not retain an unreviewed claim’s badge.</p></Card><Card><p className="text-xs font-black uppercase text-[#219b31]">Public profile preview</p><div className="mt-4 flex items-start justify-between gap-3"><div><h3 className="text-2xl font-black text-slate-900">{profile.displayName}</h3><p className="mt-1 text-sm text-slate-500">{profile.primarySpecialisation} · {profile.city}</p></div><StatusPill status={profile.verificationLabel} /></div><p className="mt-5 text-sm leading-6 text-slate-600">{profile.biography}</p><dl className="mt-5 grid grid-cols-2 gap-4 text-sm"><div><dt className="text-slate-400">Experience</dt><dd className="font-bold text-slate-800">{profile.yearsExperience} years</dd></div><div><dt className="text-slate-400">Response time</dt><dd className="font-bold text-slate-800">{profile.responseTime}</dd></div><div><dt className="text-slate-400">Languages</dt><dd className="font-bold text-slate-800">{profile.languages.join(", ")}</dd></div><div><dt className="text-slate-400">Availability</dt><dd className="font-bold text-slate-800">{profile.availability}</dd></div></dl><h4 className="mt-6 font-black text-slate-900">Services</h4><ul className="mt-3 space-y-2">{profile.services.map((service) => <li key={service.id} className="rounded-xl bg-slate-50 p-3 text-sm font-semibold text-slate-700">{service.name}</li>)}</ul></Card></div></PageFrame>; }

export function SettingsPage() { const { profile, state } = useWorkspace(); const { showToast } = useToast(); if (!profile) return null; const saved = state.settings[profile.id] ?? {}; const options = [["inApp", "In-app notifications"], ["email", "Email notifications (prototype preference only)"], ["newRequests", "New request alerts"], ["messages", "Message alerts"], ["deadlines", "Deadline reminders"], ["quotations", "Quotation alerts"], ["profileVisible", "Public profile visibility"]]; return <PageFrame title="Settings" description="Control workspace notifications, availability, privacy, role preference and local prototype data."><Card className="max-w-3xl"><h3 className="text-lg font-black text-slate-900">Notification and privacy preferences</h3><div className="mt-4 divide-y divide-slate-100">{options.map(([key, name]) => <label key={key} className="flex cursor-pointer items-center justify-between gap-4 py-4 text-sm font-semibold text-slate-700"><span>{name}</span><input type="checkbox" className="h-5 w-5 accent-[#2ec440]" defaultChecked={saved[key] !== false} onChange={(e) => ProfessionalService.updateSettings(profile.id, { [key]: e.target.checked })} /></label>)}</div><PrimaryButton className="mt-5" onClick={() => showToast("Prototype preferences saved.")}>Save preferences</PrimaryButton><p className="mt-3 text-xs text-slate-500">Email settings are stored locally; no email provider is connected.</p></Card></PageFrame>; }

export function ActivityPage() { const { profile, state } = useWorkspace(); const [category, setCategory] = useState("all"); if (!profile) return null; const items = state.activity.filter((item) => item.profileId === profile.id && (category === "all" || item.category === category)); return <PageFrame title="Activity and audit history" description="A local audit trail of professional actions across shared work."><div className="mb-5 max-w-xs"><label className="text-sm font-bold text-slate-700">Filter activity<select className={`${fieldClass} mt-1`} value={category} onChange={(e) => setCategory(e.target.value)}><option value="all">All activity</option>{["requests", "reviews", "quotations", "messages", "consultations", "documents", "profile", "system"].map((item) => <option key={item}>{item}</option>)}</select></label></div>{items.length ? <Card><ol className="divide-y divide-slate-100">{items.map((item) => <li key={item.id} className="py-4"><div className="flex items-start justify-between gap-4"><div><p className="font-bold text-slate-900">{item.description}</p><p className="mt-1 text-xs font-semibold uppercase text-slate-400">{item.category} · {item.type.replace(/_/g, " ")}</p></div><time className="text-xs text-slate-400">{formatDate(item.createdAt)}</time></div></li>)}</ol></Card> : <EmptyState title="No activity" description="Actions are recorded here as you work." />}</PageFrame>; }
